Repository sxs-collaboration/spectre, pull requests merged in 2018-12, with the labels that each got.

#1210 Fix gcc8 issues
  external/SPHEREPACK/CMakeLists.txt
  src/Utilities/Gsl.hpp
Labels: updated

#1186 Add 2-index constraint
  src/Evolution/Systems/GeneralizedHarmonic/Constraints.cpp
  src/Evolution/Systems/GeneralizedHarmonic/Constraints.hpp
  tests/Unit/Evolution/Systems/GeneralizedHarmonic/TestFunctions.py
  tests/Unit/Evolution/Systems/GeneralizedHarmonic/Test_Constraints.cpp
Labels: review help wanted, updated

#1216 Reduce build time and fix timeouts on Travis
  .travis/BuildLinux.sh
  cmake/AddSpectreExecutable.cmake
  docs/GroupDefs.hpp
  src/DataStructures/DataBox/DataBox.hpp
  src/Evolution/Executables/Burgers/EvolveBurgers.hpp
  src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivClean.hpp
  src/Evolution/Executables/ScalarWave/EvolveScalarWave.hpp
  src/Parallel/Algorithm.hpp
  src/Parallel/CharmMain.tpp
  src/Parallel/CharmRegistration.hpp
  src/Utilities/TMPL.hpp
  tests/Unit/DataStructures/Test_OrientVariablesOnSlice.cpp
  tests/Unit/NumericalAlgorithms/LinearSolver/ConjugateGradient/Test_ConjugateGradientAlgorithm.cpp
  tests/Unit/NumericalAlgorithms/LinearSolver/ConjugateGradient/Test_DistributedConjugateGradientAlgorithm.cpp
  tests/Unit/NumericalAlgorithms/LinearSolver/Gmres/Test_DistributedGmresAlgorithm.cpp
  tests/Unit/NumericalAlgorithms/LinearSolver/Gmres/Test_GmresAlgorithm.cpp
  tests/Unit/Parallel/Test_AlgorithmBadBoxApply.cpp
  tests/Unit/Parallel/Test_AlgorithmCore.cpp
  tests/Unit/Parallel/Test_AlgorithmNestedApply1.cpp
  tests/Unit/Parallel/Test_AlgorithmNestedApply2.cpp
  tests/Unit/Parallel/Test_AlgorithmNodelock.cpp
  tests/Unit/Parallel/Test_AlgorithmParallel.cpp
  tests/Unit/Parallel/Test_AlgorithmReduction.cpp
  tests/Unit/RunTests.cpp
  tools/FileTestDefs.sh
Labels: priority

#1062 Update extrinsic curvature documentation
  src/PointwiseFunctions/GeneralRelativity/ComputeSpacetimeQuantities.hpp
Labels: review help wanted

#1197 Add ObserveSurfaceIntegrals.
  src/NumericalAlgorithms/Interpolation/Callbacks/ObserveSurfaceIntegrals.hpp
  src/NumericalAlgorithms/Interpolation/InterpolationTarget.hpp
  tests/Unit/NumericalAlgorithms/Interpolation/CMakeLists.txt
  tests/Unit/NumericalAlgorithms/Interpolation/Test_ObserveSurfaceIntegrals.cpp
Labels: updated

#1178 Add regular grid interpolant
  src/NumericalAlgorithms/Interpolation/CMakeLists.txt
  src/NumericalAlgorithms/Interpolation/RegularGridInterpolant.cpp
  src/NumericalAlgorithms/Interpolation/RegularGridInterpolant.hpp
  src/NumericalAlgorithms/Spectral/Spectral.hpp
  tests/Unit/NumericalAlgorithms/Interpolation/CMakeLists.txt
  tests/Unit/NumericalAlgorithms/Interpolation/Test_RegularGridInterpolant.cpp
  tests/Unit/NumericalAlgorithms/Spectral/Test_Spectral.cpp
Labels: updated

#1128 Extend wedge_coordinate_maps to multiple layers
  src/Domain/DomainCreators/Shell.cpp
  src/Domain/DomainCreators/Shell.hpp
  src/Domain/DomainHelpers.cpp
  src/Domain/DomainHelpers.hpp
  tests/Unit/Domain/DomainCreators/Test_Shell.cpp
  tests/Unit/Domain/Test_DomainHelpers.cpp
Labels: priority, updated

#1214 Registration cleanup
  src/Evolution/EventsAndTriggers/Completion.hpp
  src/Evolution/EventsAndTriggers/Event.hpp
  src/Evolution/EventsAndTriggers/EventsAndTriggers.hpp
  src/Evolution/EventsAndTriggers/LogicalTriggers.hpp
  src/Evolution/EventsAndTriggers/Trigger.hpp
  src/Evolution/Executables/Burgers/EvolveBurgers.hpp
  src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivClean.hpp
  src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivCleanAnalyticData.hpp
  src/Evolution/Executables/ScalarWave/EvolveScalarWave.hpp
  src/Time/StepChoosers/Cfl.hpp
  src/Time/StepChoosers/Constant.hpp
  src/Time/StepChoosers/Increase.hpp
  src/Time/StepChoosers/StepChooser.hpp
  src/Time/Triggers/EveryNSlabs.hpp
  src/Time/Triggers/PastTime.hpp
  src/Time/Triggers/SpecifiedSlabs.hpp
  src/Time/Triggers/TimeTriggers.hpp
  src/Utilities/Registration.hpp
  tests/Unit/Evolution/EventsAndTriggers/Test_EventsAndTriggers.cpp
  tests/Unit/Time/Actions/Test_ChangeStepSize.cpp
  tests/Unit/Time/StepChoosers/Test_Cfl.cpp
  tests/Unit/Time/StepChoosers/Test_Constant.cpp
  tests/Unit/Time/StepChoosers/Test_Increase.cpp
  tests/Unit/Time/Test_EveryNSlabs.cpp
  tests/Unit/Time/Test_PastTime.cpp
  tests/Unit/Time/Test_SpecifiedSlabs.cpp
  tests/Unit/Utilities/CMakeLists.txt
  tests/Unit/Utilities/Test_Registration.cpp
Labels: priority, updated

#1193 Add Orszag-Tang vortex initial data
  docs/References.bib
  src/Evolution/Systems/GrMhd/ValenciaDivClean/System.hpp
  src/PointwiseFunctions/AnalyticData/GrMhd/BondiHoyleAccretion.hpp
  src/PointwiseFunctions/AnalyticData/GrMhd/CMakeLists.txt
  src/PointwiseFunctions/AnalyticData/GrMhd/OrszagTangVortex.cpp
  src/PointwiseFunctions/AnalyticData/GrMhd/OrszagTangVortex.hpp
  src/PointwiseFunctions/AnalyticSolutions/GeneralRelativity/Minkowski.hpp
  src/PointwiseFunctions/AnalyticSolutions/GrMhd/BondiMichel.hpp
  src/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/FishboneMoncriefDisk.hpp
  src/PointwiseFunctions/Hydro/Tags.hpp
  tests/Unit/PointwiseFunctions/AnalyticData/GrMhd/CMakeLists.txt
  tests/Unit/PointwiseFunctions/AnalyticData/GrMhd/TestFunctions.py
  tests/Unit/PointwiseFunctions/AnalyticData/GrMhd/Test_OrszagTangVortex.cpp
Labels: updated

#1205 Add elliptic ImposeBoundaryConditions action
  src/Elliptic/DiscontinuousGalerkin/ImposeBoundaryConditions.hpp
  tests/Unit/Elliptic/CMakeLists.txt
  tests/Unit/Elliptic/DiscontinuousGalerkin/CMakeLists.txt
  tests/Unit/Elliptic/DiscontinuousGalerkin/Test_ImposeBoundaryConditions.cpp
Labels: updated

#1220 VectorImpl template and macros
  src/DataStructures/CMakeLists.txt
  src/DataStructures/DataVector.cpp
  src/DataStructures/DataVector.hpp
  src/DataStructures/Variables.hpp
  src/DataStructures/VectorImpl.hpp
  src/Domain/LogicalCoordinates.cpp
  src/Domain/LogicalCoordinates.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Characteristics.hpp
  src/Utilities/DereferenceWrapper.hpp
  src/Utilities/PointerVector.hpp
  src/Utilities/StdArrayHelpers.hpp
  tests/Unit/Domain/Test_OrientationMap.cpp
  tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/Test_LiftFlux.cpp
  tests/Unit/Utilities/Test_StdArrayHelpers.cpp
  tools/Iwyu/iwyu.imp
Labels: updated

#1207 Add elliptic DgElementArray and initializers
  src/Elliptic/DiscontinuousGalerkin/DgElementArray.hpp
  src/Elliptic/DiscontinuousGalerkin/InitializeElement.hpp
  src/Elliptic/Initialization/Derivatives.hpp
  src/Elliptic/Initialization/DiscontinuousGalerkin.hpp
  src/Elliptic/Initialization/Domain.hpp
  src/Elliptic/Initialization/Interface.hpp
  src/Elliptic/Initialization/LinearSolver.hpp
  src/Elliptic/Initialization/System.hpp
  tests/Unit/Elliptic/CMakeLists.txt
  tests/Unit/Elliptic/Initialization/CMakeLists.txt
  tests/Unit/Elliptic/Initialization/Test_Derivatives.cpp
  tests/Unit/Elliptic/Initialization/Test_DiscontinuousGalerkin.cpp
  tests/Unit/Elliptic/Initialization/Test_Domain.cpp
  tests/Unit/Elliptic/Initialization/Test_Interface.cpp
  tests/Unit/Elliptic/Initialization/Test_LinearSolver.cpp
  tests/Unit/Elliptic/Initialization/Test_System.cpp
Labels: updated

#1228 Update Minerva environment
  cmake/AddCxxFlag.cmake
  support/Environments/minerva_gcc.sh
Labels: updated

#1247 VectorImpl generic math tests
  src/DataStructures/VectorImpl.hpp
  src/Utilities/ContainerHelpers.hpp
  src/Utilities/DereferenceWrapper.hpp
  src/Utilities/TypeTraits.hpp
  tests/Unit/DataStructures/CMakeLists.txt
  tests/Unit/DataStructures/Test_DataVector.cpp
  tests/Unit/DataStructures/Test_VectorImplTestHelper.cpp
  tests/Unit/DataStructures/VectorImplTestHelper.hpp
  tests/Unit/TestHelpers.hpp
  tests/Unit/Utilities/Test_ContainerHelpers.cpp
  tests/Unit/Utilities/Test_TypeTraits.cpp
  tests/Utilities/MakeWithRandomValues.hpp
Labels: updated
