Repository sxs-collaboration/spectre, pull requests merged in 2018-11, with the labels that each got.

#1131 Correct names in parallel interpolator
  src/NumericalAlgorithms/Interpolation/InterpolationTargetReceiveVars.hpp
  src/NumericalAlgorithms/Interpolation/SendPointsToInterpolator.hpp
  tests/Unit/NumericalAlgorithms/Interpolation/Test_InterpolationTargetLineSegment.cpp
  tests/Unit/NumericalAlgorithms/Interpolation/Test_InterpolationTargetReceiveVars.cpp
Labels: priority

#1113 Test parallel interpolator
  tests/Unit/NumericalAlgorithms/Interpolation/CMakeLists.txt
  tests/Unit/NumericalAlgorithms/Interpolation/Test_ParallelInterpolator.cpp
Labels: priority

#1093 Add wedge-section torus InterpolationTarget
  src/NumericalAlgorithms/Interpolation/BarycentricRational.hpp
  src/NumericalAlgorithms/Interpolation/CMakeLists.txt
  src/NumericalAlgorithms/Interpolation/InterpolationTargetLineSegment.hpp
  src/NumericalAlgorithms/Interpolation/InterpolationTargetWedgeSectionTorus.cpp
  src/NumericalAlgorithms/Interpolation/InterpolationTargetWedgeSectionTorus.hpp
  src/NumericalAlgorithms/Interpolation/Intrp.hpp
  src/NumericalAlgorithms/Interpolation/IntrpOptionHolders.hpp
  tests/Unit/NumericalAlgorithms/Interpolation/CMakeLists.txt
  tests/Unit/NumericalAlgorithms/Interpolation/InterpolationTargetTestHelpers.hpp
  tests/Unit/NumericalAlgorithms/Interpolation/Test_InterpolationTargetLineSegment.cpp
  tests/Unit/NumericalAlgorithms/Interpolation/Test_InterpolationTargetWedgeSectionTorus.cpp
Labels: priority

#1144 Enable fallback primitive variable inversion schemes.
  src/Evolution/Conservative/UpdatePrimitives.hpp
  src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivClean.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/NewmanHamlin.cpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/PrimitiveFromConservative.cpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/PrimitiveFromConservative.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/PrimitiveRecoveryData.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/System.hpp
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Test_PrimitiveFromConservative.cpp
Labels: breaking change, priority

#866 Add Poisson system
  docs/References.bib
  src/Elliptic/Systems/Poisson/CMakeLists.txt
  src/Elliptic/Systems/Poisson/Equations.cpp
  src/Elliptic/Systems/Poisson/Equations.hpp
  src/Elliptic/Systems/Poisson/FirstOrderSystem.hpp
  tests/Unit/Elliptic/Systems/Poisson/CMakeLists.txt
  tests/Unit/Elliptic/Systems/Poisson/Test_Equations.cpp
  tests/Unit/Elliptic/Systems/Poisson/Test_Tags.cpp
Labels: new design

#1183 Add Libsharp to Blue Waters, ComputeCanada, and Wheeler environments
  support/Environments/bluewaters_gcc.sh
  support/Environments/compute_canada_gcc.sh
  support/Environments/wheeler_clang.sh
  support/Environments/wheeler_gcc.sh
Labels: priority

#1176 Get derivatives of lapse from GH variables
  src/PointwiseFunctions/GeneralRelativity/ComputeGhQuantities.cpp
  src/PointwiseFunctions/GeneralRelativity/ComputeGhQuantities.hpp
  tests/Unit/PointwiseFunctions/GeneralRelativity/TestFunctions.py
  tests/Unit/PointwiseFunctions/GeneralRelativity/Test_ComputeGhQuantities.cpp
Labels: updated
