Repository sxs-collaboration/spectre, pull requests merged in 2018-10, with the labels that each got.

#1006 GrMhd executable: Initialization
  src/Evolution/Conservative/UpdatePrimitives.hpp
  src/Evolution/DiscontinuousGalerkin/DgElementArray.hpp
  src/Evolution/Executables/Burgers/EvolveBurgers.hpp
  src/Evolution/Executables/CMakeLists.txt
  src/Evolution/Executables/GrMhd/CMakeLists.txt
  src/Evolution/Executables/GrMhd/ValenciaDivClean/CMakeLists.txt
  src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivClean.hpp
  src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivCleanFwd.hpp
  src/Evolution/Executables/ScalarWave/EvolveScalarWave.hpp
  src/Evolution/Initialization/ConservativeSystem.hpp
  src/Evolution/Initialization/DiscontinuousGalerkin.hpp
  src/Evolution/Initialization/Domain.hpp
  src/Evolution/Initialization/Evolution.hpp
  src/Evolution/Initialization/Helpers.hpp
  src/Evolution/Initialization/Interface.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/CMakeLists.txt
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Characteristics.cpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Characteristics.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Initialize.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Observe.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/PrimitiveFromConservative.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/System.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Tags.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/TagsDeclarations.hpp
  src/NumericalAlgorithms/DiscontinuousGalerkin/NumericalFluxes/Hll.hpp
  src/NumericalAlgorithms/DiscontinuousGalerkin/NumericalFluxes/LocalLaxFriedrichs.hpp
  src/PointwiseFunctions/AnalyticSolutions/GrMhd/AlfvenWave.cpp
  src/PointwiseFunctions/AnalyticSolutions/GrMhd/AlfvenWave.hpp
  src/PointwiseFunctions/AnalyticSolutions/GrMhd/SmoothFlow.cpp
  src/PointwiseFunctions/AnalyticSolutions/GrMhd/SmoothFlow.hpp
  src/PointwiseFunctions/Hydro/Tags.hpp
  src/PointwiseFunctions/Hydro/TagsDeclarations.hpp
  tests/InputFiles/GrMhd/ValenciaDivClean/GrMhd.yaml
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/CMakeLists.txt
  tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/NumericalFluxes/Test_Hll.cpp
  tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/NumericalFluxes/Test_LocalLaxFriedrichs.cpp
  tests/Unit/PointwiseFunctions/AnalyticSolutions/GrMhd/Test_AlfvenWave.cpp
  tests/Unit/PointwiseFunctions/AnalyticSolutions/GrMhd/Test_SmoothFlow.cpp
  tests/Unit/PointwiseFunctions/Hydro/Test_Tags.cpp
Labels: breaking change, new design, priority

#978 Add Dirichlet Boundary Conditions
  src/Domain/ElementId.cpp
  src/Domain/ElementId.hpp
  src/Domain/FaceNormal.hpp
  src/Domain/LogicalCoordinates.hpp
  src/Domain/Tags.hpp
  src/Evolution/DiscontinuousGalerkin/InitializeElement.hpp
  src/Evolution/Executables/Burgers/EvolveBurgers.hpp
  src/Evolution/Executables/ScalarWave/EvolveScalarWave.hpp
  src/Evolution/Initialization/DiscontinuousGalerkin.hpp
  src/Evolution/Initialization/Interface.hpp
  src/NumericalAlgorithms/DiscontinuousGalerkin/Actions/FluxCommunication.hpp
  src/NumericalAlgorithms/DiscontinuousGalerkin/Actions/ImposeBoundaryConditions.hpp
  src/NumericalAlgorithms/DiscontinuousGalerkin/Actions/InterfaceActionHelpers.hpp
  src/PointwiseFunctions/AnalyticSolutions/Tags.hpp
  tests/Unit/Domain/Test_ElementId.cpp
  tests/Unit/Domain/Test_FaceNormal.cpp
  tests/Unit/Domain/Test_InterfaceItems.cpp
  tests/Unit/Evolution/DiscontinuousGalerkin/Test_InitializeElement.cpp
  tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/Actions/CMakeLists.txt
  tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/Actions/Test_ImposeBoundaryConditions.cpp
Labels: priority

#1056 Enable source terms in GrMhd executable
  src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivClean.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Fluxes.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Initialize.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Sources.cpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Sources.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/System.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Tags.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/TagsDeclarations.hpp
  tests/InputFiles/GrMhd/ValenciaDivClean/GrMhd.yaml
  tests/Unit/DataStructures/Test_Variables.cpp
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/TestFunctions.py
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Test_Sources.cpp
  tests/Unit/TestHelpers.hpp
Labels: priority

#1064 Enable minmod limiter for GrMhd
  src/Evolution/Executables/GrMhd/ValenciaDivClean/CMakeLists.txt
  src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivClean.hpp
  src/Evolution/Initialization/Limiter.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Initialize.hpp
  tests/InputFiles/GrMhd/ValenciaDivClean/GrMhd.yaml
Labels: priority

#792 Add conjugate gradient linear solver
  cmake/SetupClangTidy.cmake
  docs/GroupDefs.hpp
  src/NumericalAlgorithms/LinearSolver/ConjugateGradient/ConjugateGradient.hpp
  src/NumericalAlgorithms/LinearSolver/ConjugateGradient/ElementActions.hpp
  src/NumericalAlgorithms/LinearSolver/ConjugateGradient/InitializeElement.hpp
  src/NumericalAlgorithms/LinearSolver/ConjugateGradient/ResidualMonitor.hpp
  src/NumericalAlgorithms/LinearSolver/ConjugateGradient/ResidualMonitorActions.hpp
  src/NumericalAlgorithms/LinearSolver/Tags.hpp
  tests/Unit/ActionTesting.hpp
  tests/Unit/NumericalAlgorithms/LinearSolver/CMakeLists.txt
  tests/Unit/NumericalAlgorithms/LinearSolver/ConjugateGradient/CMakeLists.txt
  tests/Unit/NumericalAlgorithms/LinearSolver/ConjugateGradient/Test_ConjugateGradientAlgorithm.cpp
  tests/Unit/NumericalAlgorithms/LinearSolver/ConjugateGradient/Test_ConjugateGradientAlgorithm.input
  tests/Unit/NumericalAlgorithms/LinearSolver/ConjugateGradient/Test_DistributedConjugateGradientAlgorithm.cpp
  tests/Unit/NumericalAlgorithms/LinearSolver/ConjugateGradient/Test_DistributedConjugateGradientAlgorithm.input
  tests/Unit/NumericalAlgorithms/LinearSolver/ConjugateGradient/Test_ElementActions.cpp
  tests/Unit/NumericalAlgorithms/LinearSolver/ConjugateGradient/Test_ResidualMonitorActions.cpp
Labels: new design

#1052 Add InterpolationTargetLineSegment
  src/NumericalAlgorithms/Interpolation/InterpolatedVars.hpp
  src/NumericalAlgorithms/Interpolation/InterpolationTargetLineSegment.hpp
  src/NumericalAlgorithms/Interpolation/Interpolator.hpp
  src/NumericalAlgorithms/Interpolation/SendPointsToInterpolator.hpp
  tests/Unit/NumericalAlgorithms/Interpolation/CMakeLists.txt
  tests/Unit/NumericalAlgorithms/Interpolation/Test_InitializeInterpolator.cpp
  tests/Unit/NumericalAlgorithms/Interpolation/Test_InterpolationTargetLineSegment.cpp
Labels: priority

#1069 Cleanup relativistic hydro solutions interface
  src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivClean.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/CMakeLists.txt
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Initialize.hpp
  src/PointwiseFunctions/AnalyticSolutions/GrMhd/AlfvenWave.cpp
  src/PointwiseFunctions/AnalyticSolutions/GrMhd/AlfvenWave.hpp
  src/PointwiseFunctions/AnalyticSolutions/GrMhd/CMakeLists.txt
  src/PointwiseFunctions/AnalyticSolutions/GrMhd/SmoothFlow.cpp
  src/PointwiseFunctions/AnalyticSolutions/GrMhd/SmoothFlow.hpp
  src/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/CMakeLists.txt
  src/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/FishboneMoncriefDisk.cpp
  src/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/FishboneMoncriefDisk.hpp
  src/PointwiseFunctions/Hydro/EquationsOfState/PolytropicFluid.hpp
  tests/InputFiles/GrMhd/ValenciaDivClean/GrMhd.yaml
  tests/Unit/PointwiseFunctions/AnalyticSolutions/GrMhd/TestFunctions.py
  tests/Unit/PointwiseFunctions/AnalyticSolutions/GrMhd/Test_AlfvenWave.cpp
  tests/Unit/PointwiseFunctions/AnalyticSolutions/GrMhd/Test_SmoothFlow.cpp
  tests/Unit/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/TestFunctions.py
  tests/Unit/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/Test_FishboneMoncriefDisk.cpp
Labels: priority

#1082 Interpolator receive volume data
  src/NumericalAlgorithms/Interpolation/InterpolatedVars.hpp
  src/NumericalAlgorithms/Interpolation/InterpolatorReceiveVolumeData.hpp
  src/NumericalAlgorithms/Interpolation/TryToInterpolate.hpp
  tests/Unit/NumericalAlgorithms/Interpolation/CMakeLists.txt
  tests/Unit/NumericalAlgorithms/Interpolation/Test_InterpolatorReceiveVolumeData.cpp
Labels: priority

#1088 Add CleanUpInterpolator.
  src/NumericalAlgorithms/Interpolation/CleanUpInterpolator.hpp
  src/NumericalAlgorithms/Interpolation/InitializeInterpolator.hpp
  src/NumericalAlgorithms/Interpolation/InterpolatedVars.hpp
  src/NumericalAlgorithms/Interpolation/Tags.hpp
  tests/Unit/NumericalAlgorithms/Interpolation/CMakeLists.txt
  tests/Unit/NumericalAlgorithms/Interpolation/Test_CleanUpInterpolator.cpp
Labels: priority

#1100 Grmhd boundary conditions
  src/DataStructures/DataBox/DataBox.hpp
  src/Evolution/DiscontinuousGalerkin/InitializeElement.hpp
  src/Evolution/Executables/GrMhd/ValenciaDivClean/CMakeLists.txt
  src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivClean.hpp
  src/Evolution/Initialization/ConservativeSystem.hpp
  src/Evolution/Initialization/DiscontinuousGalerkin.hpp
  src/Evolution/Initialization/Evolution.hpp
  src/Evolution/Systems/Burgers/System.hpp
  src/Evolution/Systems/CurvedScalarWave/System.hpp
  src/Evolution/Systems/GeneralizedHarmonic/System.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Characteristics.cpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Characteristics.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Initialize.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/PrimitiveFromConservative.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/System.hpp
  src/Evolution/Systems/NewtonianEuler/System.hpp
  src/Evolution/Systems/RelativisticEuler/Valencia/System.hpp
  src/Evolution/Systems/ScalarWave/System.hpp
  src/NumericalAlgorithms/DiscontinuousGalerkin/Actions/ImposeBoundaryConditions.hpp
  src/PointwiseFunctions/AnalyticSolutions/GeneralRelativity/CMakeLists.txt
  src/PointwiseFunctions/AnalyticSolutions/GeneralRelativity/KerrSchild.cpp
  src/PointwiseFunctions/AnalyticSolutions/GeneralRelativity/KerrSchild.hpp
  src/PointwiseFunctions/AnalyticSolutions/GrMhd/AlfvenWave.cpp
  src/PointwiseFunctions/AnalyticSolutions/GrMhd/AlfvenWave.hpp
  src/PointwiseFunctions/AnalyticSolutions/GrMhd/CMakeLists.txt
  src/PointwiseFunctions/AnalyticSolutions/GrMhd/SmoothFlow.cpp
  src/PointwiseFunctions/AnalyticSolutions/GrMhd/SmoothFlow.hpp
  src/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/CMakeLists.txt
  src/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/FishboneMoncriefDisk.cpp
  src/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/FishboneMoncriefDisk.hpp
  src/Time/Tags.hpp
  tests/Unit/Evolution/DiscontinuousGalerkin/Test_InitializeElement.cpp
  tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/Actions/Test_ImposeBoundaryConditions.cpp
  tests/Unit/PointwiseFunctions/AnalyticSolutions/GrMhd/Test_AlfvenWave.cpp
  tests/Unit/PointwiseFunctions/AnalyticSolutions/GrMhd/Test_SmoothFlow.cpp
  tests/Unit/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/Test_FishboneMoncriefDisk.cpp
Labels: priority

#1075 Add InterpolationTargetReceiveVars.
  src/NumericalAlgorithms/Interpolation/InterpolationTargetReceiveVars.hpp
  tests/Unit/NumericalAlgorithms/Interpolation/CMakeLists.txt
  tests/Unit/NumericalAlgorithms/Interpolation/Test_InterpolationTargetReceiveVars.cpp
Labels: priority

#1096 Add Options to Shell for number of Wedge3Ds to have
  src/Domain/DomainCreators/Shell.cpp
  src/Domain/DomainCreators/Shell.hpp
  src/Domain/DomainHelpers.cpp
  src/Domain/DomainHelpers.hpp
  tests/Unit/Domain/DomainCreators/Test_Shell.cpp
  tests/Unit/Domain/Test_DomainHelpers.cpp
Labels: priority

#1106 Add InterpolatorReceivePoints.
  src/NumericalAlgorithms/Interpolation/InterpolatorReceivePoints.hpp
  tests/Unit/NumericalAlgorithms/Interpolation/CMakeLists.txt
  tests/Unit/NumericalAlgorithms/Interpolation/Test_InterpolatorReceivePoints.cpp
Labels: priority

#1102 Add additional variable fixers for GRMHD
  src/Evolution/CMakeLists.txt
  src/Evolution/Systems/GrMhd/ValenciaDivClean/CMakeLists.txt
  src/Evolution/Systems/GrMhd/ValenciaDivClean/FixConservatives.cpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/FixConservatives.hpp
  src/Evolution/VariableFixing/Actions.hpp
  src/Evolution/VariableFixing/CMakeLists.txt
  src/Evolution/VariableFixing/FixToAtmosphere.cpp
  src/Evolution/VariableFixing/FixToAtmosphere.hpp
  src/Evolution/VariableFixing/RadiallyFallingFloor.cpp
  src/Evolution/VariableFixing/RadiallyFallingFloor.hpp
  src/Evolution/VariableFixing/Tags.hpp
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/CMakeLists.txt
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Test_FixConservatives.cpp
  tests/Unit/Evolution/VariableFixing/CMakeLists.txt
  tests/Unit/Evolution/VariableFixing/Test_Actions.cpp
  tests/Unit/Evolution/VariableFixing/Test_FixToAtmosphere.cpp
  tests/Unit/Evolution/VariableFixing/Test_RadiallyFallingFloor.cpp
Labels: priority

#1118 Fix root-finding bounds in BondiMichel
  src/PointwiseFunctions/AnalyticSolutions/GrMhd/BondiMichel.cpp
  src/PointwiseFunctions/AnalyticSolutions/GrMhd/BondiMichel.hpp
  tests/Unit/PointwiseFunctions/AnalyticSolutions/GrMhd/TestFunctions.py
  tests/Unit/PointwiseFunctions/AnalyticSolutions/GrMhd/Test_BondiMichel.cpp
Labels: priority

#1116 Add variable fixing to GrMhd executable
  src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivClean.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/CMakeLists.txt
  src/Evolution/Systems/GrMhd/ValenciaDivClean/FixConservatives.cpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/FixConservatives.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Initialize.hpp
  src/Evolution/VariableFixing/FixToAtmosphere.hpp
  tests/InputFiles/GrMhd/ValenciaDivClean/GrMhd.yaml
Labels: priority
