Repository sxs-collaboration/spectre, pull requests merged in 2018-09, with the labels that each got.

#915 Finish LTS initialization, enable in EvolveBurgers
  src/Evolution/DiscontinuousGalerkin/DgElementArray.hpp
  src/Evolution/DiscontinuousGalerkin/InitializeElement.hpp
  src/Evolution/Executables/Burgers/EvolveBurgers.hpp
  src/Evolution/Executables/ScalarWave/EvolveScalarWave.hpp
  src/Evolution/Systems/Burgers/Equations.hpp
  src/NumericalAlgorithms/DiscontinuousGalerkin/Actions/ApplyBoundaryFluxesGlobalTimeStepping.hpp
  src/NumericalAlgorithms/DiscontinuousGalerkin/Actions/ApplyBoundaryFluxesLocalTimeStepping.hpp
  src/Time/Actions/ChangeStepSize.hpp
  tests/InputFiles/Burgers/Linear.yaml
  tests/Unit/Evolution/DiscontinuousGalerkin/Test_InitializeElement.cpp
  tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/Actions/Test_ApplyBoundaryFluxesGlobalTimeStepping.cpp
  tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/Actions/Test_ApplyBoundaryFluxesLocalTimeStepping.cpp
  tests/Unit/Time/Actions/Test_ChangeStepSize.cpp
Labels: priority

#921 Refactor interface items
  src/ApparentHorizons/CMakeLists.txt
  src/DataStructures/DataBox/DataBox.hpp
  src/DataStructures/DataBox/Prefixes.hpp
  src/Domain/Mesh.hpp
  src/Domain/Tags.hpp
  src/Evolution/DiscontinuousGalerkin/InitializeElement.hpp
  src/Evolution/Systems/Burgers/Tags.hpp
  src/Evolution/Systems/ScalarWave/Tags.hpp
  src/NumericalAlgorithms/LinearSolver/Tags.hpp
  src/PointwiseFunctions/AnalyticSolutions/EinsteinSolutions/CMakeLists.txt
  tests/Unit/Domain/Test_FaceNormal.cpp
  tests/Unit/Domain/Test_InterfaceItems.cpp
  tests/Unit/Domain/Test_Mesh.cpp
  tests/Unit/Evolution/DiscontinuousGalerkin/Test_InitializeElement.cpp
  tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/Actions/Test_ComputeNonconservativeBoundaryFluxes.cpp
  tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/Actions/Test_FluxCommunication.cpp
  tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/Actions/Test_FluxCommunicationLts.cpp
Labels: breaking change, priority

#918 Observer registration
  cmake/SpectreParseTests.py
  docs/GroupDefs.hpp
  src/IO/CMakeLists.txt
  src/IO/Observer/Actions.hpp
  src/IO/Observer/ArrayComponentId.cpp
  src/IO/Observer/ArrayComponentId.hpp
  src/IO/Observer/Initialize.hpp
  src/IO/Observer/ObserverComponent.hpp
  src/IO/Observer/Tags.hpp
  src/IO/Observer/TypeOfObservation.cpp
  src/IO/Observer/TypeOfObservation.hpp
  src/Parallel/Algorithm.hpp
  src/Parallel/NodeLock.hpp
  src/Parallel/SimpleActionVisitation.hpp
  tests/Unit/ActionTesting.hpp
  tests/Unit/IO/CMakeLists.txt
  tests/Unit/IO/Observers/Test_ArrayComponentId.cpp
  tests/Unit/IO/Observers/Test_Initialize.cpp
  tests/Unit/IO/Observers/Test_RegisterElements.cpp
  tests/Unit/IO/Observers/Test_Tags.cpp
  tests/Unit/IO/Observers/Test_TypeOfObservation.cpp
Labels: priority

#901 Add Newman and Hamlin method for inverting GRMHD variables
  src/Evolution/Systems/GrMhd/ValenciaDivClean/CMakeLists.txt
  src/Evolution/Systems/GrMhd/ValenciaDivClean/NewmanHamlin.cpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/NewmanHamlin.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/PrimitiveFromConservative.cpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/PrimitiveFromConservative.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/PrimitiveRecoveryData.hpp
  src/Evolution/Systems/RelativisticEuler/Valencia/PrimitiveFromConservative.cpp
  src/PointwiseFunctions/EquationsOfState/CMakeLists.txt
  src/PointwiseFunctions/EquationsOfState/DarkEnergyFluid.cpp
  src/PointwiseFunctions/EquationsOfState/DarkEnergyFluid.hpp
  src/PointwiseFunctions/EquationsOfState/EquationOfState.hpp
  src/PointwiseFunctions/EquationsOfState/IdealFluid.cpp
  src/PointwiseFunctions/EquationsOfState/IdealFluid.hpp
  src/PointwiseFunctions/EquationsOfState/PolytropicFluid.cpp
  src/PointwiseFunctions/EquationsOfState/PolytropicFluid.hpp
  src/PointwiseFunctions/EquationsOfState/SpecificEnthalpy.cpp
  src/PointwiseFunctions/EquationsOfState/SpecificEnthalpy.hpp
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/CMakeLists.txt
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Test_PrimitiveFromConservative.cpp
  tests/Unit/Evolution/Systems/RelativisticEuler/Valencia/Test_PrimitiveFromConservative.cpp
  tests/Unit/PointwiseFunctions/EquationsOfState/CMakeLists.txt
  tests/Unit/PointwiseFunctions/EquationsOfState/TestFunctions.py
  tests/Unit/PointwiseFunctions/EquationsOfState/TestHelpers.hpp
  tests/Unit/PointwiseFunctions/EquationsOfState/Test_DarkEnergyFluid.cpp
  tests/Unit/PointwiseFunctions/EquationsOfState/Test_SpecificEnthalpy.cpp
Labels: priority

#916 Add RadiallyFallingFloor
  cmake/SpectreParseTests.py
  docs/GroupDefs.hpp
  src/Evolution/VariableFixing/RadiallyFallingFloor.hpp
  tests/Unit/Evolution/CMakeLists.txt
  tests/Unit/Evolution/VariableFixing/CMakeLists.txt
  tests/Unit/Evolution/VariableFixing/Test_RadiallyFallingFloor.cpp
Labels: priority

#830 Adopt base tag for derivative compute item
  src/Evolution/DiscontinuousGalerkin/InitializeElement.hpp
  src/Evolution/Systems/CurvedScalarWave/Equations.hpp
  src/Evolution/Systems/GeneralizedHarmonic/Equations.hpp
  src/Evolution/Systems/ScalarWave/Equations.hpp
  src/NumericalAlgorithms/LinearOperators/PartialDerivatives.hpp
  tests/Unit/Evolution/DiscontinuousGalerkin/Test_InitializeElement.cpp
  tests/Unit/NumericalAlgorithms/LinearOperators/Test_PartialDerivatives.cpp
Labels: breaking change

#940 Revive Travis
  .travis.yml
  .travis/BuildLinux.sh
  .travis/MacOsBuild.sh
  .travis/MacOsBuildDependencies.sh
  .travis/TravisPushDocumentation.sh
  CMakeLists.txt
  cmake/SetupBuildStageTargets.cmake
  cmake/SetupPch.cmake
  cmake/SpectreAddLibraries.cmake
  containers/Dockerfile.travis
  docs/DevGuide/Travis.md
  src/ApparentHorizons/CMakeLists.txt
  src/ControlSystem/CMakeLists.txt
  src/DataStructures/CMakeLists.txt
  src/Domain/Amr/CMakeLists.txt
  src/Domain/CoordinateMaps/CMakeLists.txt
  src/Domain/DomainCreators/CMakeLists.txt
  src/ErrorHandling/CMakeLists.txt
  src/Evolution/DiscontinuousGalerkin/SlopeLimiters/CMakeLists.txt
  src/Evolution/Systems/Burgers/CMakeLists.txt
  src/Evolution/Systems/CurvedScalarWave/CMakeLists.txt
  src/Evolution/Systems/GeneralizedHarmonic/CMakeLists.txt
  src/Evolution/Systems/GrMhd/ValenciaDivClean/CMakeLists.txt
  src/Evolution/Systems/NewtonianEuler/CMakeLists.txt
  src/Evolution/Systems/NewtonianEuler/NewtonianEulerSources/CMakeLists.txt
  src/Evolution/Systems/RelativisticEuler/Valencia/CMakeLists.txt
  src/Evolution/Systems/ScalarWave/CMakeLists.txt
  src/IO/CMakeLists.txt
  src/Informer/CMakeLists.txt
  src/NumericalAlgorithms/DiscontinuousGalerkin/CMakeLists.txt
  src/NumericalAlgorithms/Interpolation/CMakeLists.txt
  src/NumericalAlgorithms/LinearAlgebra/CMakeLists.txt
  src/NumericalAlgorithms/LinearOperators/CMakeLists.txt
  src/NumericalAlgorithms/LinearSolver/CMakeLists.txt
  src/NumericalAlgorithms/RootFinding/CMakeLists.txt
  src/NumericalAlgorithms/Spectral/CMakeLists.txt
  src/PointwiseFunctions/AnalyticSolutions/Burgers/CMakeLists.txt
  src/PointwiseFunctions/AnalyticSolutions/EinsteinSolutions/CMakeLists.txt
  src/PointwiseFunctions/AnalyticSolutions/NewtonianEulerSolutions/CMakeLists.txt
  src/PointwiseFunctions/AnalyticSolutions/Poisson/CMakeLists.txt
  src/PointwiseFunctions/AnalyticSolutions/WaveEquation/CMakeLists.txt
  src/PointwiseFunctions/EquationsOfState/CMakeLists.txt
  src/PointwiseFunctions/GeneralRelativity/CMakeLists.txt
  src/PointwiseFunctions/MathFunctions/CMakeLists.txt
  src/Time/CMakeLists.txt
  src/Utilities/CMakeLists.txt
  tests/Unit/Domain/CoordinateMaps/Test_CubicScale.cpp
  tools/SpectrePch.hpp
Labels: breaking change

#953 Action testing mock simple actions
  src/Parallel/Algorithm.hpp
  src/Parallel/ConstGlobalCache.ci
  src/Parallel/ConstGlobalCache.hpp
  src/Parallel/Main.hpp
  src/PointwiseFunctions/AnalyticSolutions/EinsteinSolutions/KerrSchild.cpp
  src/PointwiseFunctions/AnalyticSolutions/EinsteinSolutions/KerrSchild.hpp
  src/PointwiseFunctions/AnalyticSolutions/NewtonianEulerSolutions/IsentropicVortex.cpp
  src/PointwiseFunctions/AnalyticSolutions/NewtonianEulerSolutions/IsentropicVortex.hpp
  src/Utilities/TaggedTuple.hpp
  tests/Unit/ActionTesting.hpp
  tests/Unit/CMakeLists.txt
  tests/Unit/Evolution/Actions/Test_ComputeVolumeDuDt.cpp
  tests/Unit/Evolution/Actions/Test_ComputeVolumeFluxes.cpp
  tests/Unit/Evolution/Actions/Test_ComputeVolumeSources.cpp
  tests/Unit/Evolution/DiscontinuousGalerkin/Test_InitializeElement.cpp
  tests/Unit/Evolution/EventsAndTriggers/Test_EventsAndTriggers.cpp
  tests/Unit/Evolution/VariableFixing/Test_Actions.cpp
  tests/Unit/IO/Observers/Test_Initialize.cpp
  tests/Unit/IO/Observers/Test_RegisterElements.cpp
  tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/Actions/Test_ApplyBoundaryFluxesGlobalTimeStepping.cpp
  tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/Actions/Test_ApplyBoundaryFluxesLocalTimeStepping.cpp
  tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/Actions/Test_ComputeNonconservativeBoundaryFluxes.cpp
  tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/Actions/Test_FluxCommunication.cpp
  tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/Actions/Test_FluxCommunicationLts.cpp
  tests/Unit/Parallel/Test_ConstGlobalCache.cpp
  tests/Unit/Test_ActionTesting.cpp
  tests/Unit/Time/Actions/Test_AdvanceTime.cpp
  tests/Unit/Time/Actions/Test_ChangeStepSize.cpp
  tests/Unit/Time/Actions/Test_FinalTime.cpp
  tests/Unit/Time/Actions/Test_RecordTimeStepperData.cpp
  tests/Unit/Time/Actions/Test_UpdateU.cpp
Labels: breaking change

#994 Simplify reductions
  docs/GroupDefs.hpp
  src/Parallel/Algorithm.hpp
  src/Parallel/Reduction.hpp
  src/Utilities/Numeric.hpp
  tests/Unit/Parallel/Test_AlgorithmReduction.cpp
  tests/Unit/Utilities/Test_Numeric.cpp
Labels: breaking change
