Repository sxs-collaboration/spectre, pull requests merged in 2019-05, with the labels that each got.

#1517 Fix building without python bindings
  src/IO/CMakeLists.txt
Labels: priority

#1478 Add compute items for spatial Christoffels
  src/PointwiseFunctions/GeneralRelativity/Christoffel.hpp
  src/PointwiseFunctions/GeneralRelativity/Tags.hpp
  src/PointwiseFunctions/GeneralRelativity/TagsDeclarations.hpp
  tests/Unit/PointwiseFunctions/GeneralRelativity/Test_Christoffel.cpp
Labels: updated

#1468 Compute items for SpacetimeMetric, SpatialMetric, Det and Inverse of SpatialMetric
  src/DataStructures/Tensor/EagerMath/DeterminantAndInverse.hpp
  src/PointwiseFunctions/GeneralRelativity/ComputeSpacetimeQuantities.hpp
  src/PointwiseFunctions/GeneralRelativity/Tags.hpp
  src/PointwiseFunctions/GeneralRelativity/TagsDeclarations.hpp
  tests/Unit/DataStructures/Tensor/EagerMath/Test_DeterminantAndInverse.cpp
  tests/Unit/PointwiseFunctions/GeneralRelativity/Test_ComputeSpacetimeQuantities.cpp
Labels: updated

#1476 Add compute items for dt of lapse, shift, 3metric
  src/PointwiseFunctions/GeneralRelativity/ComputeGhQuantities.hpp
  tests/Unit/PointwiseFunctions/GeneralRelativity/Test_ComputeGhQuantities.cpp
Labels: updated

#1477 Add compute items for spacetime Christoffels
  src/PointwiseFunctions/GeneralRelativity/Christoffel.hpp
  src/PointwiseFunctions/GeneralRelativity/Tags.hpp
  src/PointwiseFunctions/GeneralRelativity/TagsDeclarations.hpp
  tests/Unit/PointwiseFunctions/GeneralRelativity/Test_Christoffel.cpp
Labels: updated

#1473 Add compute items for GH Phi, Pi and ExtrinsicCurvature
  src/PointwiseFunctions/GeneralRelativity/ComputeGhQuantities.hpp
  tests/Unit/PointwiseFunctions/GeneralRelativity/Test_ComputeGhQuantities.cpp
Labels: updated

#1474 Add compute items for trace of ExtrinsicCurvature and derivatives of SpacetimeMetric
  src/PointwiseFunctions/GeneralRelativity/ComputeGhQuantities.hpp
  src/PointwiseFunctions/GeneralRelativity/ComputeSpacetimeQuantities.hpp
  src/PointwiseFunctions/GeneralRelativity/Tags.hpp
  src/PointwiseFunctions/GeneralRelativity/TagsDeclarations.hpp
  tests/Unit/PointwiseFunctions/GeneralRelativity/Test_ComputeGhQuantities.cpp
  tests/Unit/PointwiseFunctions/GeneralRelativity/Test_ComputeSpacetimeQuantities.cpp
Labels: updated

#1497 Update GH `System` with tags needed for evolution
  src/Evolution/Systems/GeneralizedHarmonic/System.hpp
Labels: updated

#1469 Compute items for SqrtDetSpatialMetric
  src/DataStructures/Tensor/EagerMath/Magnitude.hpp
  src/PointwiseFunctions/GeneralRelativity/ComputeSpacetimeQuantities.hpp
  tests/Unit/DataStructures/Tensor/EagerMath/Test_Magnitude.cpp
  tests/Unit/PointwiseFunctions/GeneralRelativity/Test_ComputeSpacetimeQuantities.cpp
Labels: updated

#1470 Compute items for Lapse, Shift and InverseSpacetimeMetric
  src/PointwiseFunctions/GeneralRelativity/ComputeSpacetimeQuantities.hpp
  src/PointwiseFunctions/GeneralRelativity/Tags.hpp
  src/PointwiseFunctions/GeneralRelativity/TagsDeclarations.hpp
  tests/Unit/PointwiseFunctions/GeneralRelativity/Test_ComputeSpacetimeQuantities.cpp
Labels: updated

#1475 Add compute items for deriv of lapse, shift, 3metric
  src/PointwiseFunctions/GeneralRelativity/ComputeGhQuantities.hpp
  tests/Unit/PointwiseFunctions/GeneralRelativity/Test_ComputeGhQuantities.cpp
Labels: updated

#1471 Compute items for SpacetimeNormal{OneForm, Vector}
  src/PointwiseFunctions/GeneralRelativity/ComputeSpacetimeQuantities.hpp
  tests/Unit/PointwiseFunctions/GeneralRelativity/Test_ComputeSpacetimeQuantities.cpp
Labels: updated

#1444 Add compute items for GH constraints
  src/Evolution/Systems/GeneralizedHarmonic/Tags.hpp
  src/Evolution/Systems/GeneralizedHarmonic/TagsDeclarations.hpp
  src/PointwiseFunctions/GeneralRelativity/ComputeGhQuantities.hpp
  tests/Unit/Evolution/Systems/GeneralizedHarmonic/Test_Constraints.cpp
Labels: updated

#1499 Add wrapper class to make AnalyticSolutions compatible with GH
  src/PointwiseFunctions/AnalyticSolutions/GeneralRelativity/CMakeLists.txt
  src/PointwiseFunctions/AnalyticSolutions/GeneralRelativity/WrappedGr.cpp
  src/PointwiseFunctions/AnalyticSolutions/GeneralRelativity/WrappedGr.hpp
  src/PointwiseFunctions/GeneralRelativity/Tags.hpp
  tests/Unit/PointwiseFunctions/AnalyticSolutions/GeneralRelativity/CMakeLists.txt
  tests/Unit/PointwiseFunctions/AnalyticSolutions/GeneralRelativity/Test_WrappedGr.cpp
Labels: updated

#1542 Move EventAndTriggers OptionTag into its own file
  src/Evolution/EventsAndTriggers/Actions/RunEventsAndTriggers.hpp
  src/Evolution/EventsAndTriggers/EventsAndTriggers.hpp
  src/Evolution/EventsAndTriggers/Tags.hpp
  src/Evolution/Executables/Burgers/EvolveBurgers.hpp
  src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivClean.hpp
  src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivCleanAnalyticData.hpp
  src/Evolution/Executables/ScalarWave/EvolveScalarWave.hpp
  src/Time/Tags.hpp
  tests/Unit/Evolution/EventsAndTriggers/Test_EventsAndTriggers.cpp
Labels: breaking change
