Repository sxs-collaboration/spectre, pull requests merged in 2019-03, with the labels that each got.

#1391 Add indefinite integral
  src/NumericalAlgorithms/LinearOperators/CMakeLists.txt
  src/NumericalAlgorithms/LinearOperators/IndefiniteIntegral.cpp
  src/NumericalAlgorithms/LinearOperators/IndefiniteIntegral.hpp
  src/NumericalAlgorithms/Spectral/Chebyshev.cpp
  src/NumericalAlgorithms/Spectral/Legendre.cpp
  src/NumericalAlgorithms/Spectral/Spectral.cpp
  src/NumericalAlgorithms/Spectral/Spectral.hpp
  tests/Unit/NumericalAlgorithms/LinearOperators/CMakeLists.txt
  tests/Unit/NumericalAlgorithms/LinearOperators/Test_CoefficientTransforms.cpp
  tests/Unit/NumericalAlgorithms/LinearOperators/Test_IndefiniteIntegral.cpp
  tests/Unit/NumericalAlgorithms/Spectral/CMakeLists.txt
  tests/Unit/NumericalAlgorithms/Spectral/Test_IndefiniteIntegral.cpp
Labels: updated

#1217 Improve Documentation of Tags and DataBox in DevGuide
  docs/DevGuide/Databox.md
  docs/DevGuide/DevGuide.md
  docs/DevGuide/DomainConcepts.md
  docs/DevGuide/Tmp.md
  src/DataStructures/DataBox/DataBox.hpp
  tests/Unit/DataStructures/DataBox/CMakeLists.txt
  tests/Unit/DataStructures/DataBox/Test_DataBoxDocumentation.cpp
Labels: documentation, updated

#1423 Add ability to exclude Blocks in AlignedLattice
  src/Domain/Creators/AlignedLattice.cpp
  src/Domain/Creators/AlignedLattice.hpp
  tests/Unit/Domain/Creators/Test_AlignedLattice.cpp
Labels: priority

#1400 add missing includes in ReductionActions and LinearSolver tests
  src/IO/Observer/ReductionActions.hpp
  src/IO/Observer/Tags.hpp
  src/Parallel/Algorithm.hpp
  src/Parallel/NodeLock.hpp
  tests/Unit/ActionTesting.hpp
  tests/Unit/NumericalAlgorithms/LinearSolver/ResidualMonitorActionsTestHelpers.hpp
Labels: updated

#1298 Add constitutive relation for linear elasticity
  cmake/SetupBuildStageTargets.cmake
  cmake/SpectreParseTests.py
  src/Elliptic/Systems/CMakeLists.txt
  src/Elliptic/Systems/Elasticity/CMakeLists.txt
  src/Elliptic/Systems/Elasticity/Tags.hpp
  src/Elliptic/Systems/ThermalNoise/Tags.hpp
  src/PointwiseFunctions/CMakeLists.txt
  src/PointwiseFunctions/Elasticity/CMakeLists.txt
  src/PointwiseFunctions/Elasticity/ConstitutiveRelations/CMakeLists.txt
  src/PointwiseFunctions/Elasticity/ConstitutiveRelations/ConstitutiveRelation.cpp
  src/PointwiseFunctions/Elasticity/ConstitutiveRelations/ConstitutiveRelation.hpp
  src/PointwiseFunctions/Elasticity/ConstitutiveRelations/IsotropicHomogeneous.cpp
  src/PointwiseFunctions/Elasticity/ConstitutiveRelations/IsotropicHomogeneous.hpp
  src/PointwiseFunctions/Elasticity/ConstitutiveRelations/Tags.hpp
  tests/Unit/Elliptic/Systems/CMakeLists.txt
  tests/Unit/Elliptic/Systems/Elasticity/CMakeLists.txt
  tests/Unit/Elliptic/Systems/Elasticity/Test_Tags.cpp
  tests/Unit/Elliptic/Systems/ThermalNoise/Test_ThermalNoiseTags.cpp
  tests/Unit/PointwiseFunctions/CMakeLists.txt
  tests/Unit/PointwiseFunctions/Elasticity/CMakeLists.txt
  tests/Unit/PointwiseFunctions/Elasticity/ConstitutiveRelations/CMakeLists.txt
  tests/Unit/PointwiseFunctions/Elasticity/ConstitutiveRelations/IsotropicHomogeneous.py
  tests/Unit/PointwiseFunctions/Elasticity/ConstitutiveRelations/Test_IsotropicHomogeneous.cpp
  tests/Unit/PointwiseFunctions/Elasticity/ConstitutiveRelations/Test_Tags.cpp
Labels: updated

#1390 Update Newtonian Euler interface
  src/Evolution/Systems/NewtonianEuler/CMakeLists.txt
  src/Evolution/Systems/NewtonianEuler/Characteristics.cpp
  src/Evolution/Systems/NewtonianEuler/Characteristics.hpp
  src/Evolution/Systems/NewtonianEuler/ConservativeFromPrimitive.cpp
  src/Evolution/Systems/NewtonianEuler/ConservativeFromPrimitive.hpp
  src/Evolution/Systems/NewtonianEuler/PrimitiveFromConservative.cpp
  src/Evolution/Systems/NewtonianEuler/PrimitiveFromConservative.hpp
  src/Evolution/Systems/NewtonianEuler/SoundSpeedSquared.cpp
  src/Evolution/Systems/NewtonianEuler/SoundSpeedSquared.hpp
  src/Evolution/Systems/NewtonianEuler/Tags.hpp
  src/Evolution/Systems/NewtonianEuler/TagsDeclarations.hpp
  src/PointwiseFunctions/Hydro/EquationsOfState/DarkEnergyFluid.hpp
  src/PointwiseFunctions/Hydro/EquationsOfState/IdealFluid.hpp
  src/PointwiseFunctions/Hydro/EquationsOfState/PolytropicFluid.hpp
  tests/Unit/Evolution/Systems/NewtonianEuler/CMakeLists.txt
  tests/Unit/Evolution/Systems/NewtonianEuler/TestFunctions.py
  tests/Unit/Evolution/Systems/NewtonianEuler/Test_Characteristics.cpp
  tests/Unit/Evolution/Systems/NewtonianEuler/Test_ConservativeFromPrimitive.cpp
  tests/Unit/Evolution/Systems/NewtonianEuler/Test_PrimitiveFromConservative.cpp
  tests/Unit/Evolution/Systems/NewtonianEuler/Test_SoundSpeedSquared.cpp
  tests/Unit/Evolution/Systems/NewtonianEuler/Test_Tags.cpp
Labels: updated

#1426 add check to not include lrtslock.h
  docs/DevGuide/CodeReviewGuide.md
  tools/FileTestDefs.sh
Labels: enhancement

#1357 Improvements to Frustum
  docs/DevGuide/DevGuide.md
  docs/DevGuide/RedistributingGridpoints.md
  docs/Images/Domain/CoordinateMaps/BilinearVProjective.png
  docs/Images/Domain/CoordinateMaps/ProjectionOfCube.png
  docs/Images/Domain/CoordinateMaps/ProjectionOntoPlane.png
  docs/Images/Domain/CoordinateMaps/frustum_table1.png
  src/Domain/CoordinateMaps/Frustum.cpp
  src/Domain/CoordinateMaps/Frustum.hpp
  src/Domain/Creators/CMakeLists.txt
  src/Domain/Creators/DomainCreator.hpp
  src/Domain/Creators/FrustalCloak.cpp
  src/Domain/Creators/FrustalCloak.hpp
  src/Domain/DomainHelpers.cpp
  src/Domain/DomainHelpers.hpp
  tests/Unit/Domain/CoordinateMaps/Test_Frustum.cpp
  tests/Unit/Domain/Creators/CMakeLists.txt
  tests/Unit/Domain/Creators/Test_FrustalCloak.cpp
  tests/Unit/Domain/Test_DomainHelpers.cpp
Labels: documentation, enhancement, updated

#1441 Update Viz docs for EveryNSlabs
  docs/Tutorials/Visualization.md
Labels: documentation, priority
