Repository sxs-collaboration/spectre, pull requests merged in 2019-02, with the labels that each got.

#1273 Add contributing guide and code of conduct
  LICENSE.txt
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
  docs/DevGuide/Travis.md
  docs/MainSite/Main.md
  docs/MainSite/ReportingGuide.md
  docs/config/doxygen.css
  docs/config/footer.html
  docs/config/header.html
  tools/FileTestDefs.sh
Labels: updated

#1287 cleanup Fishbone-Moncrief disk
  docs/References.bib
  src/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/FishboneMoncriefDisk.cpp
  src/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/FishboneMoncriefDisk.hpp
  tests/InputFiles/GrMhd/ValenciaDivClean/GrMhd.yaml
  tests/Unit/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/TestFunctions.py
  tests/Unit/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/Test_FishboneMoncriefDisk.cpp
Labels: updated

#1306 Allow MAKE_GENERATOR to take a seed
  tests/Unit/TestHelpers.hpp
  tests/Unit/Test_TestHelpers.cpp
Labels: updated

#1177 Get derivatives of shift from GH variables
  src/DataStructures/Variables.hpp
  src/PointwiseFunctions/GeneralRelativity/ComputeGhQuantities.cpp
  src/PointwiseFunctions/GeneralRelativity/ComputeGhQuantities.hpp
  tests/Unit/PointwiseFunctions/GeneralRelativity/TestFunctions.py
  tests/Unit/PointwiseFunctions/GeneralRelativity/Test_ComputeGhQuantities.cpp
Labels: priority

#1135 Add ComplexDataView
  src/NumericalAlgorithms/Spectral/CMakeLists.txt
  src/NumericalAlgorithms/Spectral/ComplexDataView.cpp
  src/NumericalAlgorithms/Spectral/ComplexDataView.hpp
  tests/Unit/NumericalAlgorithms/Spectral/CMakeLists.txt
  tests/Unit/NumericalAlgorithms/Spectral/Test_ComplexDataView.cpp
Labels: updated

#1347 Update Isentropic Vortex Interface
  docs/References.bib
  src/Evolution/Systems/NewtonianEuler/Fluxes.hpp
  src/Evolution/Systems/NewtonianEuler/Tags.hpp
  src/Evolution/Systems/NewtonianEuler/TagsDeclarations.hpp
  src/PointwiseFunctions/AnalyticSolutions/NewtonianEuler/IsentropicVortex.cpp
  src/PointwiseFunctions/AnalyticSolutions/NewtonianEuler/IsentropicVortex.hpp
  tests/Unit/Evolution/Systems/NewtonianEuler/CMakeLists.txt
  tests/Unit/Evolution/Systems/NewtonianEuler/Test_Tags.cpp
  tests/Unit/PointwiseFunctions/AnalyticSolutions/NewtonianEuler/TestFunctions.py
  tests/Unit/PointwiseFunctions/AnalyticSolutions/NewtonianEuler/Test_IsentropicVortex.cpp
Labels: updated

#1343 Add to Numpy from Matrix Function
  src/DataStructures/Python/Bindings.cpp
  src/DataStructures/Python/CMakeLists.txt
  src/DataStructures/Python/Matrix.cpp
  src/DataStructures/Python/Matrix.hpp
  src/DataStructures/Python/Numpy.hpp
  src/DataStructures/Python/ToNumpy.cpp
  src/DataStructures/Python/ToNumpy.hpp
  tests/Unit/DataStructures/Test_Matrix.py
Labels: updated

#1380 Add function to get collapsed index from mesh
  src/DataStructures/Index.cpp
  src/DataStructures/Index.hpp
  src/Domain/Mesh.hpp
  tests/Unit/DataStructures/Test_Index.cpp
  tests/Unit/Domain/Test_DomainHelpers.cpp
  tests/Unit/Domain/Test_Mesh.cpp
Labels: updated

#1393 Fix reference of Minerbo1978
  docs/References.bib
Labels: documentation
