Repository sxs-collaboration/spectre, pull requests merged in 2020-01, with the labels that each got.

#1879 Increase minimum macOS version to 10.9
  cmake/SetupMacOsx.cmake
Labels: small

#1886 Increase FConstraint tolerance
  tests/Unit/Evolution/Systems/GeneralizedHarmonic/Test_Constraints.cpp
Labels: small

#1857 Compute tag to take the trace of spatial Christoffel 2nd kind
  src/PointwiseFunctions/GeneralRelativity/Christoffel.hpp
  tests/Unit/PointwiseFunctions/GeneralRelativity/Test_Christoffel.cpp
Labels: small, updated

#1731 Add Ah finder to GH exec
  src/Evolution/Executables/GeneralizedHarmonic/CMakeLists.txt
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGeneralizedHarmonic.hpp
  tests/InputFiles/GeneralizedHarmonic/KerrSchild.yaml
Labels: updated

#1905 Specify blaze version in installation instructions
  docs/Installation/Installation.md
Labels: small

#1760 Add characteristics for curved-scalar-wave system
  src/Evolution/Systems/CurvedScalarWave/CMakeLists.txt
  src/Evolution/Systems/CurvedScalarWave/Characteristics.cpp
  src/Evolution/Systems/CurvedScalarWave/Characteristics.hpp
  src/Evolution/Systems/CurvedScalarWave/Constraints.hpp
  src/Evolution/Systems/CurvedScalarWave/Equations.cpp
  src/Evolution/Systems/CurvedScalarWave/Equations.hpp
  src/Evolution/Systems/CurvedScalarWave/System.hpp
  src/Evolution/Systems/CurvedScalarWave/Tags.hpp
  src/Evolution/Systems/CurvedScalarWave/TagsDeclarations.hpp
  tests/Unit/Evolution/Systems/CurvedScalarWave/CMakeLists.txt
  tests/Unit/Evolution/Systems/CurvedScalarWave/Characteristics.py
  tests/Unit/Evolution/Systems/CurvedScalarWave/Test_Characteristics.cpp
Labels: priority, updated

#1914 Add static assert in base tag storage type metafunction
  src/DataStructures/DataBox/DataBoxTag.hpp
Labels: small

#1794 Fix Latex in IsotropicHomogeneous docs
  src/PointwiseFunctions/Elasticity/ConstitutiveRelations/ConstitutiveRelation.hpp
  src/PointwiseFunctions/Elasticity/ConstitutiveRelations/IsotropicHomogeneous.hpp
Labels: small

#1759 Add constraints for the scalar-wave system in curved spacetime
  src/Evolution/Systems/CurvedScalarWave/CMakeLists.txt
  src/Evolution/Systems/CurvedScalarWave/Constraints.cpp
  src/Evolution/Systems/CurvedScalarWave/Constraints.hpp
  src/Evolution/Systems/CurvedScalarWave/Equations.hpp
  src/Evolution/Systems/CurvedScalarWave/Tags.hpp
  tests/Unit/Evolution/Systems/CurvedScalarWave/CMakeLists.txt
  tests/Unit/Evolution/Systems/CurvedScalarWave/Constraints.py
  tests/Unit/Evolution/Systems/CurvedScalarWave/Test_Constraints.cpp
Labels: priority, updated

#1751 Add characteristics for the scalar-wave system
  src/Evolution/Systems/ScalarWave/CMakeLists.txt
  src/Evolution/Systems/ScalarWave/Characteristics.cpp
  src/Evolution/Systems/ScalarWave/Characteristics.hpp
  src/Evolution/Systems/ScalarWave/Equations.cpp
  src/Evolution/Systems/ScalarWave/Equations.hpp
  src/Evolution/Systems/ScalarWave/System.hpp
  src/Evolution/Systems/ScalarWave/Tags.hpp
  src/Evolution/Systems/ScalarWave/TagsDeclarations.hpp
  tests/Unit/Evolution/Systems/ScalarWave/CMakeLists.txt
  tests/Unit/Evolution/Systems/ScalarWave/Characteristics.py
  tests/Unit/Evolution/Systems/ScalarWave/Test_Characteristics.cpp
Labels: updated

#1771 Add penalty flux for scalar waves
  src/Evolution/Systems/ScalarWave/Equations.cpp
  src/Evolution/Systems/ScalarWave/Equations.hpp
  tests/Unit/Evolution/Systems/ScalarWave/PenaltyFlux.py
  tests/Unit/Evolution/Systems/ScalarWave/Test_Equations.cpp
Labels: updated
