Repository sxs-collaboration/spectre, pull requests merged in 2020-03, with the labels that each got.

#1963 Make HDF5 an imported target in CMake
  cmake/SetupHdf5.cmake
  cmake/SpectreAddTestLibs.cmake
  src/Evolution/Systems/Cce/CMakeLists.txt
  src/IO/CMakeLists.txt
  src/IO/H5/Python/CMakeLists.txt
  tests/Unit/NumericalAlgorithms/Interpolation/CMakeLists.txt
  tests/Unit/ParallelAlgorithms/Events/CMakeLists.txt
Labels: in progress

#1906 Add Ocean batch submit script
  support/SubmitScripts/Ocean.sh
Labels: updated

#2085 Add a target to build all Pybindings
  cmake/SpectreSetupPythonPackage.cmake
Labels: small

#2083 Add expand_tuple utility
  src/Utilities/Tuple.hpp
  tests/Unit/PointwiseFunctions/AnalyticSolutions/FirstOrderEllipticSolutionsTestHelpers.hpp
  tests/Unit/Utilities/Test_Tuple.cpp
Labels: small

#2113 Revive CI
  .github/workflows/Tests.yaml
  CMakeLists.txt
  cmake/StripSymbols.cmake
  docs/DevGuide/BuildSystem.md
  tests/Unit/CMakeLists.txt
Labels: priority

#2119 Fix missing includes
  src/Domain/CoordinateMaps/CubicScale.hpp
  src/Utilities/TaggedTuple.hpp
Labels: priority

#2155 Fix typo in `SetupBoost.cmake`
  cmake/SetupBoost.cmake
Labels: priority

#2114 Blaze upgrade
  cmake/SetupBlaze.cmake
  containers/Dockerfile.buildenv
  docs/Installation/Installation.md
  src/DataStructures/ComplexDataVector.hpp
  src/DataStructures/ComplexDiagonalModalOperator.hpp
  src/DataStructures/ComplexModalVector.hpp
  src/DataStructures/DenseMatrix.hpp
  src/DataStructures/DiagonalModalOperator.hpp
  src/DataStructures/ModalVector.hpp
  src/DataStructures/Python/Matrix.cpp
  src/DataStructures/Variables.hpp
  src/DataStructures/VectorImpl.hpp
  src/NumericalAlgorithms/Interpolation/IrregularInterpolant.hpp
  src/NumericalAlgorithms/LinearAlgebra/FindGeneralizedEigenvalues.cpp
  src/NumericalAlgorithms/LinearOperators/ApplyMatrices.cpp
  src/NumericalAlgorithms/LinearOperators/PartialDerivatives.tpp
  src/NumericalAlgorithms/LinearSolver/Lapack.cpp
  src/NumericalAlgorithms/Spectral/Spectral.cpp
  src/Utilities/Blaze.hpp
  src/Utilities/PointerVector.hpp
  tests/Unit/DataStructures/Test_DenseMatrix.cpp
  tests/Unit/Framework/TestHelpers.hpp
  tests/Unit/Helpers/ParallelAlgorithms/LinearSolver/DistributedLinearSolverAlgorithmTestHelpers.hpp
  tests/Unit/NumericalAlgorithms/LinearOperators/Test_Linearize.cpp
  tests/Unit/NumericalAlgorithms/Spectral/Test_Filtering.cpp
  tests/Unit/NumericalAlgorithms/Spectral/Test_IndefiniteIntegral.cpp
  tests/Unit/NumericalAlgorithms/Spectral/Test_Spectral.cpp
Labels: breaking change

#2166 Fix building with shared libs on develop
  .github/workflows/Tests.yaml
  cmake/PrintUsefulCMakeInfo.cmake
  cmake/SpectreAddLibraries.cmake
  containers/Dockerfile.buildenv
  src/Domain/CMakeLists.txt
  src/Domain/Creators/CMakeLists.txt
  src/Domain/Creators/TimeDependence/CMakeLists.txt
  tests/Unit/DataStructures/Tensor/EagerMath/CMakeLists.txt
  tests/Unit/Domain/CMakeLists.txt
  tests/Unit/Evolution/Conservative/CMakeLists.txt
Labels: priority

#2172 Fix linking with AppleClang
  src/Domain/CMakeLists.txt
  src/Domain/Creators/TimeDependence/CMakeLists.txt
  tests/Unit/DataStructures/CMakeLists.txt
  tests/Unit/DataStructures/Tensor/EagerMath/CMakeLists.txt
  tests/Unit/Domain/CMakeLists.txt
  tests/Unit/Evolution/Conservative/CMakeLists.txt
Labels: priority

#1977 Init function vs times from file
  src/IO/Importers/ReadSpecThirdOrderPiecewisePolynomial.hpp
  src/IO/Importers/Tags.hpp
  tests/Unit/IO/Importers/CMakeLists.txt
  tests/Unit/IO/Importers/Test_ReadSpecThirdOrderPiecewisePolynomial.cpp
Labels: updated
