Repository sxs-collaboration/spectre, pull requests merged in 2020-08, with the labels that each got.

#2402 Avoid clang FPE in Test_Gmres.cpp
  src/Utilities/Array.hpp
  tests/Unit/NumericalAlgorithms/LinearSolver/Test_Gmres.cpp
Labels: small

#2414 Reduce bounds of random variables to prevent approx test failure
  tests/Unit/Evolution/Systems/GeneralizedHarmonic/Test_Characteristics.cpp
Labels: priority

#2431 Fix missed Tag::name usage
  src/NumericalAlgorithms/Interpolation/Callbacks/ObserveTimeSeriesOnSurface.hpp
Labels: priority

#2451 Add ocean clang env (no container)
  support/Environments/ocean_clang.sh
  support/SubmitScripts/OceanClang.sh
Labels: dependent
