Repository sxs-collaboration/spectre, pull requests merged in 2020-12, with the labels that each got.

#2649 Fix Boost version across CMake versions
  cmake/SetupBoost.cmake
Labels: bugfix

#2648 Fix typo in clang-tidy runs
  tools/ClangTidyAll.sh
  tools/ClangTidyHash.sh
Labels: bugfix

#2647 Fix typo in an error message
  tools/CheckPythonFormatting.sh
Labels: bugfix

#2651 Update catch2 on ocean
  support/Environments/ocean_clang.sh
  support/Environments/ocean_gcc.sh
  support/Environments/ocean_orca0_gcc.sh
Labels: small

#2661 Remove suggested values from ObserveFields
  src/ParallelAlgorithms/Events/ObserveFields.hpp
Labels: small

#2665 Make DampingFunctions return by not_null
  src/Evolution/Systems/GeneralizedHarmonic/ConstraintDamping/DampingFunction.hpp
  src/Evolution/Systems/GeneralizedHarmonic/ConstraintDamping/GaussianPlusConstant.cpp
  src/Evolution/Systems/GeneralizedHarmonic/ConstraintDamping/GaussianPlusConstant.hpp
  src/PointwiseFunctions/GeneralRelativity/GeneralizedHarmonic/ConstraintGammas.hpp
  tests/Unit/Helpers/Evolution/Systems/GeneralizedHarmonic/ConstraintDamping/TestHelpers.hpp
Labels: small

#2666 Fetch upstream tags on forks to fix CI
  .github/workflows/Tests.yaml
Labels: bugfix

#2668 Raise a sigtrap so debuggers work without having to specify env variables
  src/ErrorHandling/AbortWithErrorMessage.cpp
  src/ErrorHandling/Breakpoint.cpp
  src/ErrorHandling/Breakpoint.hpp
  src/ErrorHandling/CMakeLists.txt
  src/Parallel/Abort.hpp
Labels: bugfix

#2688 Update ocean to cmake 3.18.5
  support/Environments/ocean_clang.sh
  support/Environments/ocean_gcc.sh
Labels: small

#2660 Update wheeler environments
  support/Environments/wheeler_clang.sh
  support/Environments/wheeler_gcc.sh
Labels: priority

#2684 Fix SetupJemalloc with CMake 3.12
  cmake/SetupJemalloc.cmake
Labels: bugfix, priority

#2707 Add CMake hints to find Pybind11 in more cases
  cmake/SetupPybind11.cmake
Labels: bugfix

#2708 Ensure GlobalCache contents are serializable in ActionTesting
  src/Evolution/Systems/Cce/Initialize/InitializeJ.hpp
  src/NumericalAlgorithms/Interpolation/InterpolationTargetKerrHorizon.cpp
  tests/Unit/ApparentHorizons/Test_ApparentHorizonFinder.cpp
  tests/Unit/Evolution/Systems/Cce/Actions/Test_CharacteristicEvolutionBondiCalculations.cpp
  tests/Unit/Evolution/Systems/Cce/Actions/Test_GhBoundaryCommunication.cpp
  tests/Unit/Evolution/Systems/Cce/Actions/Test_H5BoundaryCommunication.cpp
  tests/Unit/Evolution/Systems/Cce/Actions/Test_InitializeCharacteristicEvolution.cpp
  tests/Unit/Evolution/Systems/Cce/Actions/Test_InitializeFirstHypersurface.cpp
  tests/Unit/Evolution/Systems/Cce/Actions/Test_InsertInterpolationScriData.cpp
  tests/Unit/Evolution/Systems/Cce/Actions/Test_RequestBoundaryData.cpp
  tests/Unit/Evolution/Systems/Cce/Actions/Test_ScriObserveInterpolated.cpp
  tests/Unit/Evolution/Systems/Cce/Actions/Test_SendNextTimeToCce.cpp
  tests/Unit/Evolution/Systems/GeneralizedHarmonic/GaugeSourceFunctions/Test_InitializeDampedHarmonic.cpp
  tests/Unit/Framework/MockRuntimeSystem.hpp
  tests/Unit/Helpers/Evolution/DiscontinuousGalerkin/Actions/ComputeTimeDerivativeImpl.tpp
  tests/Unit/NumericalAlgorithms/Interpolation/Test_AddTemporalIdsToInterpolationTarget.cpp
  tests/Unit/NumericalAlgorithms/Interpolation/Test_ElementReceiveInterpPoints.cpp
  tests/Unit/NumericalAlgorithms/Interpolation/Test_InitializeInterpolationTarget.cpp
  tests/Unit/NumericalAlgorithms/Interpolation/Test_InterpolationTargetApparentHorizon.cpp
  tests/Unit/NumericalAlgorithms/Interpolation/Test_InterpolationTargetKerrHorizon.cpp
  tests/Unit/NumericalAlgorithms/Interpolation/Test_InterpolationTargetLineSegment.cpp
  tests/Unit/NumericalAlgorithms/Interpolation/Test_InterpolationTargetReceiveVars.cpp
  tests/Unit/NumericalAlgorithms/Interpolation/Test_InterpolationTargetVarsFromElement.cpp
  tests/Unit/NumericalAlgorithms/Interpolation/Test_InterpolationTargetWedgeSectionTorus.cpp
  tests/Unit/NumericalAlgorithms/Interpolation/Test_InterpolatorReceivePoints.cpp
  tests/Unit/NumericalAlgorithms/Interpolation/Test_InterpolatorReceiveVolumeData.cpp
  tests/Unit/NumericalAlgorithms/Interpolation/Test_ObserveTimeSeriesOnSurface.cpp
  tests/Unit/NumericalAlgorithms/Interpolation/Test_ParallelInterpolator.cpp
  tests/Unit/ParallelAlgorithms/DiscontinuousGalerkin/Test_InitializeInterfaces.cpp
  tests/Unit/Time/Actions/Test_AdvanceTime.cpp
  tests/Unit/Time/Actions/Test_ChangeSlabSize.cpp
  tests/Unit/Time/Actions/Test_ChangeStepSize.cpp
  tests/Unit/Time/Actions/Test_SelfStartActions.cpp
  tests/Unit/Time/Actions/Test_UpdateU.cpp
Labels: bugfix
