Repository sxs-collaboration/spectre, pull requests merged in 2020-04, with the labels that each got.

#2004 Update documentation for DH
  src/Evolution/Systems/GeneralizedHarmonic/GaugeSourceFunctions/DampedHarmonic.hpp
Labels: small, updated

#1770 Upwind flux for the CurvedScalarWave system
  src/Evolution/Systems/CurvedScalarWave/Equations.cpp
  src/Evolution/Systems/CurvedScalarWave/Equations.hpp
  tests/Unit/Evolution/Systems/CurvedScalarWave/CMakeLists.txt
  tests/Unit/Evolution/Systems/CurvedScalarWave/Fluxes.py
  tests/Unit/Evolution/Systems/CurvedScalarWave/Test_UpwindFlux.cpp
Labels: priority, updated

#1946 Add constraint damping to ScalarWave
  src/Evolution/Executables/ScalarWave/EvolveScalarWave.hpp
  src/Evolution/Systems/ScalarWave/Characteristics.hpp
  src/Evolution/Systems/ScalarWave/Constraints.hpp
  src/Evolution/Systems/ScalarWave/Equations.cpp
  src/Evolution/Systems/ScalarWave/Equations.hpp
  src/Evolution/Systems/ScalarWave/Initialize.hpp
  src/Evolution/Systems/ScalarWave/System.hpp
  src/NumericalAlgorithms/DiscontinuousGalerkin/Protocols.hpp
  tests/InputFiles/ScalarWave/Input1DPeriodic.yaml
  tests/Unit/Evolution/Systems/ScalarWave/Test_Characteristics.cpp
  tests/Unit/Evolution/Systems/ScalarWave/Test_Constraints.cpp
  tests/Unit/Evolution/Systems/ScalarWave/Test_Equations.cpp
  tests/Unit/PointwiseFunctions/AnalyticSolutions/WaveEquation/Test_SemidiscretizedDg.cpp
Labels: updated

#1947 Update SW executable to evolve a spherical wave
  src/Evolution/Executables/ScalarWave/CMakeLists.txt
  src/Evolution/Executables/ScalarWave/EvolveScalarWave.hpp
  src/Evolution/Executables/ScalarWave/EvolveScalarWaveFwd.hpp
  tests/InputFiles/ScalarWave/Input1DPeriodic.yaml
  tests/InputFiles/ScalarWave/Input2DPeriodic.yaml
  tests/InputFiles/ScalarWave/Input3DPeriodic.yaml
  tests/InputFiles/ScalarWave/ObserveExample.yaml
  tests/Unit/IO/Test_VolumeData.py
Labels: updated

#2224 Increase timeout for binary factory tests
  tests/Unit/Domain/Creators/Test_BinaryCompactObject.cpp
Labels: priority

#2207 Fix ObserveVolumeIntegrals: use DetInvJacobian in databox
  src/Evolution/Initialization/DgDomain.hpp
  src/ParallelAlgorithms/DiscontinuousGalerkin/InitializeDomain.hpp
  src/ParallelAlgorithms/Events/ObserveVolumeIntegrals.hpp
  tests/Unit/Evolution/Initialization/Test_DgDomain.cpp
  tests/Unit/ParallelAlgorithms/DiscontinuousGalerkin/Test_InitializeDomain.cpp
  tests/Unit/ParallelAlgorithms/Events/Test_ObserveVolumeIntegrals.cpp
Labels: updated
