Repository sxs-collaboration/spectre, pull requests merged in 2020-09, with the labels that each got.

#2300 Template MathFunctions on Dimension and Frame
  src/Evolution/Executables/ScalarWave/EvolveScalarWave.hpp
  src/PointwiseFunctions/AnalyticSolutions/WaveEquation/PlaneWave.cpp
  src/PointwiseFunctions/AnalyticSolutions/WaveEquation/PlaneWave.hpp
  src/PointwiseFunctions/AnalyticSolutions/WaveEquation/RegularSphericalWave.cpp
  src/PointwiseFunctions/AnalyticSolutions/WaveEquation/RegularSphericalWave.hpp
  src/PointwiseFunctions/MathFunctions/Gaussian.cpp
  src/PointwiseFunctions/MathFunctions/Gaussian.hpp
  src/PointwiseFunctions/MathFunctions/MathFunction.hpp
  src/PointwiseFunctions/MathFunctions/PowX.cpp
  src/PointwiseFunctions/MathFunctions/PowX.hpp
  src/PointwiseFunctions/MathFunctions/Sinusoid.cpp
  src/PointwiseFunctions/MathFunctions/Sinusoid.hpp
  src/PointwiseFunctions/MathFunctions/TensorProduct.cpp
  src/PointwiseFunctions/MathFunctions/TensorProduct.hpp
  tests/Unit/Evolution/Conservative/Test_ConservativeDuDt.cpp
  tests/Unit/Evolution/Systems/ScalarWave/Test_Characteristics.cpp
  tests/Unit/Evolution/Systems/ScalarWave/Test_Constraints.cpp
  tests/Unit/Evolution/Systems/ScalarWave/Test_Equations.cpp
  tests/Unit/Helpers/PointwiseFunctions/MathFunctions/TestHelpers.hpp
  tests/Unit/NumericalAlgorithms/Interpolation/Test_IrregularInterpolant.cpp
  tests/Unit/NumericalAlgorithms/Interpolation/Test_RegularGridInterpolant.cpp
  tests/Unit/NumericalAlgorithms/LinearOperators/Test_Divergence.cpp
  tests/Unit/PointwiseFunctions/AnalyticData/CurvedWaveEquation/Test_ScalarWaveGr.cpp
  tests/Unit/PointwiseFunctions/AnalyticSolutions/WaveEquation/Test_PlaneWave.cpp
  tests/Unit/PointwiseFunctions/AnalyticSolutions/WaveEquation/Test_RegularSphericalWave.cpp
  tests/Unit/PointwiseFunctions/MathFunctions/Python/TestFunctions.py
  tests/Unit/PointwiseFunctions/MathFunctions/Test_Gaussian.cpp
  tests/Unit/PointwiseFunctions/MathFunctions/Test_PowX.cpp
  tests/Unit/PointwiseFunctions/MathFunctions/Test_Sinusoid.cpp
  tests/Unit/PointwiseFunctions/MathFunctions/Test_TensorProduct.cpp
Labels: breaking change, updated

#2476 Use verbs charm on ocean
  support/Environments/ocean_clang.sh
Labels: small

#2484 Fix SetupBlas for cmake<3.12
  cmake/SetupBlas.cmake
Labels: priority
