Repository sxs-collaboration/spectre, pull requests merged in 2021-08, with the labels that each got.

#3408 Fix the compilation error when the inertial coordinates are evolved
  src/Evolution/Executables/Cce/CharacteristicExtract.hpp
  src/Evolution/Systems/Cce/Components/CharacteristicEvolution.hpp
  src/Evolution/Systems/Cce/System.hpp
Labels: bugfix

#3399 Fix AH find
  src/Evolution/Executables/GeneralizedHarmonic/CMakeLists.txt
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGeneralizedHarmonicWithHorizon.hpp
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGeneralizedHarmonicWithoutHorizon.hpp
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGeneralizedHarmonicWithoutHorizonFwd.hpp
  tests/InputFiles/GeneralizedHarmonic/KerrSchild.yaml
Labels: bugfix

#3418 Add option to apply Persson TCI to GRMHD TildeB
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/InitialDataTci.cpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnDgGrid.cpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnFdGrid.cpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnFdGrid.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOptions.cpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOptions.hpp
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_InitialDataTci.cpp
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_TciOnDgGrid.cpp
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_TciOnFdGrid.cpp
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_TciOptions.cpp
Labels: priority

#3413 Add NeighborPackagedData to GRMHD
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/CMakeLists.txt
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/NeighborPackagedData.hpp
  src/PointwiseFunctions/AnalyticSolutions/GrMhd/BondiMichel.hpp
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/CMakeLists.txt
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_NeighborPackagedData.cpp
Labels: priority

#3428 A few minor fixes
  src/ApparentHorizons/ComputeHorizonVolumeQuantities.tpp
  src/Domain/Structure/ElementId.hpp
  src/NumericalAlgorithms/Interpolation/CMakeLists.txt
Labels: bugfix

#3427 Switch GRMHD executable to support DG-subcell
  src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivClean.hpp
  tests/InputFiles/GrMhd/ValenciaDivClean/BlastWave.yaml
  tests/InputFiles/GrMhd/ValenciaDivClean/FishboneMoncriefDisk.yaml
Labels: priority

#3443 Fix order of multigrid actions in XCTS executable
  src/Elliptic/Executables/Xcts/SolveXcts.hpp
Labels: bugfix

#3100 Add analytic data for a plane wave in Minkowski background
  src/PointwiseFunctions/AnalyticData/CurvedWaveEquation/CMakeLists.txt
  src/PointwiseFunctions/AnalyticData/CurvedWaveEquation/PlaneWave3DKerrSchild.cpp
  src/PointwiseFunctions/AnalyticData/CurvedWaveEquation/PlaneWave3DKerrSchild.hpp
  src/PointwiseFunctions/AnalyticData/CurvedWaveEquation/PlaneWaveMinkowski.cpp
  src/PointwiseFunctions/AnalyticData/CurvedWaveEquation/RegularSphericalWave3DKerrSchild.cpp
  src/PointwiseFunctions/AnalyticData/CurvedWaveEquation/RegularSphericalWave3DKerrSchild.hpp
  tests/Unit/PointwiseFunctions/AnalyticData/CurvedWaveEquation/Test_ScalarWaveGr.cpp
Labels: updated

#3449 Remove incorrect assertion in component mocking
  src/Parallel/GlobalCache.hpp
  src/Time/StepChoosers/StepChooser.hpp
  src/Utilities/TypeTraits/CreateGetStaticMemberVariableOrDefault.hpp
  src/Utilities/TypeTraits/CreateGetTypeAliasOrDefault.hpp
  tests/Unit/Framework/Tests/Test_ActionTesting.cpp
  tests/Unit/Utilities/TypeTraits/Test_CreateGetStaticMemberVariableOrDefault.cpp
  tests/Unit/Utilities/TypeTraits/Test_CreateGetTypeAliasOrDefault.cpp
Labels: bugfix

#3472 Move test functions into anonymous namespace
  tests/Unit/ControlSystem/Test_Averager.cpp
  tests/Unit/ControlSystem/Test_TimescaleTuner.cpp
Labels: priority, bugfix

#3480 Add missing include to DeterminantAndInverse.hpp
  src/DataStructures/Tensor/EagerMath/DeterminantAndInverse.hpp
Labels: small, bugfix
