Repository sxs-collaboration/spectre, pull requests merged in 2021-09, with the labels that each got.

#3487 Update visualization docs
  docs/Tutorials/Visualization.md
Labels: small

#3488 Add orcid ID (Yoonsoo Kim)
  Metadata.yaml
Labels: small

#3464 Support per-core reductions
  src/IO/Observer/CMakeLists.txt
  src/IO/Observer/ReductionActions.cpp
  src/IO/Observer/ReductionActions.hpp
  src/ParallelAlgorithms/Events/ObserveTimeStep.hpp
  src/ParallelAlgorithms/LinearSolver/Schwarz/ElementActions.hpp
  src/ParallelAlgorithms/LinearSolver/Schwarz/Tags.hpp
  tests/InputFiles/Elasticity/BentBeam.yaml
  tests/InputFiles/Elasticity/HalfSpaceMirror.yaml
  tests/InputFiles/Poisson/ProductOfSinusoids1D.yaml
  tests/InputFiles/Poisson/ProductOfSinusoids2D.yaml
  tests/InputFiles/Poisson/ProductOfSinusoids3D.yaml
  tests/InputFiles/Xcts/Schwarzschild.yaml
  tests/Unit/IO/CMakeLists.txt
  tests/Unit/IO/Observers/Test_ReductionObserver.cpp
  tests/Unit/ParallelAlgorithms/Events/Test_ObserveTimeStep.cpp
  tests/Unit/ParallelAlgorithms/LinearSolver/Schwarz/Test_SchwarzAlgorithm.yaml
Labels: new feature

#3500 Fix superluminal velocities in Kastaun recovery scheme
  src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivClean.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/KastaunEtAl.cpp
Labels: priority

#3501 Add domain::Tags::JacobianCompute to docs
  src/Domain/Tags.hpp
Labels: small

#3498 Fix doc-coverage with Doxygen 1.9.1
  cmake/SetupDoxygen.cmake
Labels: priority, bugfix

#3496 Compress docs upload on CI
  .github/workflows/Tests.yaml
Labels: small

#3490 Find yapf consistent with Python
  cmake/FindYapf.cmake
Labels: small, bugfix

#3508 Add CenterOfStar interpolation to magnetized TOV
  src/Evolution/Executables/GrMhd/ValenciaDivClean/CMakeLists.txt
Labels: small

#3468 Add BBH exec
  src/Evolution/Executables/GeneralizedHarmonic/CMakeLists.txt
  src/Evolution/Executables/GeneralizedHarmonic/EvolveBinaryBlackHole.hpp
  src/Evolution/Executables/GeneralizedHarmonic/EvolveBinaryBlackHoleFwd.hpp
  tests/InputFiles/GeneralizedHarmonic/BinaryBlackHole.yaml
Labels: updated

#3510 Fix LTS dense output at initial time
  src/Evolution/Actions/RunEventsAndDenseTriggers.hpp
  tests/InputFiles/ScalarWave/PlaneWave2D.yaml
Labels: bugfix

#3515 Make doxygen installation correct in buildenv
  containers/Dockerfile.buildenv
Labels: small, bugfix

#3520 Rename BBH exec, clarify why it doesn't use GHBase
  src/Evolution/Executables/GeneralizedHarmonic/CMakeLists.txt
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGhBinaryBlackHole.hpp
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGhBinaryBlackHoleFwd.hpp
Labels: small

#3521 Increase test timeout for ASAN builds
  cmake/AddInputFileTests.cmake
  cmake/SpectreAddCatchTests.cmake
Labels: small, bugfix

#3522 Build Doxygen with bugfixes in container
  containers/Dockerfile.buildenv
  docs/Doxyfile.in
  docs/config/header.html
  docs/config/js/jquery.js
  docs/config/js/spectre.js
  tools/FileTestDefs.sh
Labels: priority, bugfix

#3518 Update ocean doxygen to 1.9.1
  support/Environments/ocean_clang.sh
Labels: small

#3537 Remove template from UpdateFunctionOfTime functions
  src/ControlSystem/UpdateFunctionOfTime.hpp
  tests/Unit/ControlSystem/Test_UpdateFunctionOfTime.cpp
Labels: small

#3527 Print Charm++ startup time
  src/Informer/Informer.cpp
Labels: small

#3519 Update installation docs
  docs/Installation/Installation.md
Labels: documentation, small
