Repository sxs-collaboration/spectre, pull requests merged in 2021-04, with the labels that each got.

#2997 Utilites for spacetime quantities on 2-surfaces
  src/PointwiseFunctions/GeneralRelativity/CMakeLists.txt
  src/PointwiseFunctions/GeneralRelativity/InterfaceNullNormal.cpp
  src/PointwiseFunctions/GeneralRelativity/InterfaceNullNormal.hpp
  src/PointwiseFunctions/GeneralRelativity/ProjectionOperators.cpp
  src/PointwiseFunctions/GeneralRelativity/ProjectionOperators.hpp
  tests/Unit/PointwiseFunctions/GeneralRelativity/CMakeLists.txt
  tests/Unit/PointwiseFunctions/GeneralRelativity/InterfaceNullNormal.py
  tests/Unit/PointwiseFunctions/GeneralRelativity/ProjectionOperators.py
  tests/Unit/PointwiseFunctions/GeneralRelativity/Test_InterfaceNullNormal.cpp
  tests/Unit/PointwiseFunctions/GeneralRelativity/Test_ProjectionOperators.cpp
Labels: updated

#3029 Improve YlmSpherepack documentation
  src/ApparentHorizons/YlmSpherepack.hpp
Labels: documentation

#3081 Fix issue with link.h being unavailable on some platforms
  src/Utilities/ErrorHandling/AbortWithErrorMessage.cpp
Labels: bugfix, priority

#3075 Loosen tolerance in GRMHD char test
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Test_Characteristics.cpp
Labels: bugfix

#3072 Loosen tolerance in RelativisticEuler cons2prim
  tests/Unit/Evolution/Systems/RelativisticEuler/Valencia/Test_PrimitiveFromConservative.cpp
Labels: bugfix

#3087 Allow non-static library for `moduleLB`
  cmake/FindCharm.cmake
Labels: bugfix

#3097 Restore CI: Use a cmake variable in M1 system
  src/Evolution/Systems/RadiationTransport/M1Grey/BoundaryConditions/CMakeLists.txt
Labels: bugfix, priority

#3112 Update parallelization docs on action types
  docs/DevGuide/Parallelization.md
  tests/Unit/Parallel/Test_AlgorithmCore.cpp
  tests/Unit/Parallel/Test_AlgorithmNodelock.cpp
  tests/Unit/Parallel/Test_AlgorithmReduction.cpp
Labels: documentation
