Repository sxs-collaboration/spectre, pull requests merged in 2021-01, with the labels that each got.

#2724 Make git description in build system more robust, make sure release tags are annotated
  .github/workflows/Tests.yaml
  cmake/PrintUsefulCMakeInfo.cmake
  cmake/SpectreGetGitHash.cmake
Labels: bugfix

#2711 Fix AppleClang 12 warnings about non-reference iterators
  src/Evolution/Systems/Cce/AnalyticSolutions/LinearizedBondiSachs.cpp
  src/Evolution/Systems/Cce/AnalyticSolutions/RotatingSchwarzschild.cpp
  src/Evolution/Systems/Cce/AnalyticSolutions/SphericalMetricData.cpp
  src/Evolution/Systems/Cce/AnalyticSolutions/TeukolskyWave.cpp
  src/Evolution/Systems/Cce/AnalyticSolutions/WorldtubeData.cpp
  src/Evolution/Systems/Cce/BoundaryData.cpp
  src/Evolution/Systems/Cce/GaugeTransformBoundaryData.cpp
  src/Evolution/Systems/Cce/Initialize/InitializeJ.cpp
  src/Evolution/Systems/Cce/Initialize/InverseCubic.cpp
  src/Evolution/Systems/Cce/WorldtubeDataManager.cpp
  src/NumericalAlgorithms/Spectral/SwshCoefficients.cpp
  src/NumericalAlgorithms/Spectral/SwshDerivatives.cpp
  src/NumericalAlgorithms/Spectral/SwshFiltering.cpp
  src/NumericalAlgorithms/Spectral/SwshTransform.cpp
  src/ParallelAlgorithms/LinearSolver/Schwarz/Weighting.cpp
  tests/Unit/DataStructures/Test_ApplyMatrices.cpp
  tests/Unit/Domain/Structure/Test_Hypercube.cpp
  tests/Unit/Evolution/Systems/Cce/Actions/Test_FilterSwshVolumeQuantity.cpp
  tests/Unit/Evolution/Systems/Cce/AnalyticSolutions/Test_BouncingBlackHole.cpp
  tests/Unit/Evolution/Systems/Cce/Test_BoundaryData.cpp
  tests/Unit/Evolution/Systems/Cce/Test_GaugeTransformBoundaryData.cpp
  tests/Unit/Evolution/Systems/Cce/Test_LinearSolve.cpp
  tests/Unit/Helpers/Evolution/DiscontinuousGalerkin/Limiters/TestHelpers.hpp
  tests/Unit/Helpers/Evolution/Systems/Cce/AnalyticSolutions/AnalyticDataHelpers.hpp
  tests/Unit/Helpers/Evolution/Systems/Cce/BoundaryTestHelpers.hpp
  tests/Unit/NumericalAlgorithms/Spectral/Test_SwshCoefficients.cpp
  tests/Unit/NumericalAlgorithms/Spectral/Test_SwshCollocation.cpp
  tests/Unit/NumericalAlgorithms/Spectral/Test_SwshFiltering.cpp
  tests/Unit/Time/TimeSteppers/Test_AdamsBashforthN.cpp
Labels: bugfix

#2714 Fix false negatives in db::apply callable check
  docs/GroupDefs.hpp
  src/DataStructures/DataBox/DataBox.hpp
  src/DataStructures/DataBox/DataBoxTag.hpp
  src/Domain/InterfaceHelpers.hpp
  tests/Unit/DataStructures/DataBox/Test_DataBox.cpp
Labels: bugfix

#2712 Run Python executables in correct environment
  cmake/SpectrePythonExecutable.sh
  cmake/SpectreSetupPythonPackage.cmake
  docs/DevGuide/PythonBindings.md
  src/Visualization/Python/CMakeLists.txt
Labels: bugfix

#2731 [restore CI on develop] Fix catch labels to run in correct CI stage
  tests/Unit/Parallel/CMakeLists.txt
Labels: bugfix

#2729 Fix Py_None reference counting in pypp, prevent modification of RunSingleTest/CMakeLists.txt, check for TODO comments
  docs/DevGuide/Travis.md
  src/DataStructures/Tensor/Expressions/Product.hpp
  src/Domain/CreateInitialElement.cpp
  tests/Unit/Framework/PyppFundamentals.hpp
  tools/CheckFiles.sh
  tools/FileTestDefs.sh
  tools/Hooks/pre-commit.sh
Labels: bugfix

#2745 Fix an error handling include to restore CI
  src/Elliptic/BoundaryConditions/BoundaryConditionType.cpp
Labels: bugfix, priority

#2747 Update libxsmm on ocean to 1.16.1
  support/Environments/ocean_clang.sh
Labels: priority, small

#2738 Fix automatic versioning on protected branch, enable reviewing releases before they are dispatched
  .github/scripts/requirements-release.txt
  .github/workflows/Tests.yaml
  docs/DevGuide/AutomaticVersioning.md
  tests/tools/Test_CompileReleaseNotes.py
Labels: priority

#2749 Update Wheeler env, LIBXSSM+Pybind11
  support/Environments/wheeler_clang.sh
  support/Environments/wheeler_gcc.sh
Labels: bugfix, priority

#2756 Fix version name validation in release workflow
  .github/workflows/Tests.yaml
Labels: bugfix

#2759 Fix arguments not passed to Python executables
  cmake/SpectrePythonExecutable.sh
Labels: bugfix, priority

#2764 Remove extra comma in python init files
  cmake/SpectreSetupPythonPackage.cmake
Labels: bugfix

#2763 Fix protocol assert_conforms_to, relax NumericalFlux requirements for evolution DG transition
  src/NumericalAlgorithms/DiscontinuousGalerkin/Protocols.hpp
  src/Utilities/ProtocolHelpers.hpp
Labels: bugfix

#2776 Use unsorted generic indices in AddSub
  src/DataStructures/Tensor/Expressions/AddSubtract.hpp
  src/DataStructures/Tensor/Expressions/TensorExpression.hpp
Labels: small

#2782 Fix PCH dependencies
  cmake/SetupPch.cmake
  cmake/SpectreAddLibraries.cmake
  cmake/SpectreAddTestLibs.cmake
  cmake/UpdateAddExecutables.cmake
Labels: bugfix, priority

#2785 Restore clang-tidy on CI
  cmake/SetupClangTidy.cmake
  cmake/SetupPch.cmake
Labels: bugfix

#2784 Fix uninitialized array in OuterProduct
  src/DataStructures/Tensor/Expressions/Product.hpp
Labels: bugfix, small

#2773 Don't disrupt PRs between releases
  .github/workflows/Tests.yaml
Labels: bugfix

#2755 Make sure Python headers are consistent with interpreter
  cmake/SetupPypp.cmake
Labels: bugfix

#2801 Register Newtonian Euler Rusanov solver in test
  tests/Unit/Evolution/Systems/NewtonianEuler/BoundaryCorrections/Test_Rusanov.cpp
Labels: bugfix, priority
