Repository sxs-collaboration/spectre, pull requests merged in 2021-07, with the labels that each got.

#3338 Fix ghmhd analytic data
  src/Evolution/Executables/GrMhd/GhValenciaDivClean/CMakeLists.txt
  src/Evolution/Executables/GrMhd/GhValenciaDivClean/EvolveGhValenciaDivCleanFwd.hpp
  src/Evolution/Executables/GrMhd/GhValenciaDivClean/EvolveGhValenciaDivCleanWithHorizonFwd.hpp
  src/Evolution/Executables/GrMhd/GhValenciaDivClean/GhValenciaDivCleanBase.hpp
Labels: bugfix

#3346 Add Timeout to TovStar input file test
  tests/InputFiles/GrMhd/GhValenciaDivClean/GhMhdTovStar.yaml
Labels: bugfix

#3340 Fix segfault in test for clang12
  src/NumericalAlgorithms/LinearOperators/ExponentialFilter.cpp
  tests/Unit/IO/Test_H5.cpp
Labels: bugfix

#3172 BoundaryCondition class for GH
  docs/References.bib
  src/Evolution/Systems/GeneralizedHarmonic/BoundaryConditions/Bjorhus.cpp
  src/Evolution/Systems/GeneralizedHarmonic/BoundaryConditions/Bjorhus.hpp
  src/Evolution/Systems/GeneralizedHarmonic/BoundaryConditions/BoundaryCondition.hpp
  src/Evolution/Systems/GeneralizedHarmonic/BoundaryConditions/CMakeLists.txt
  src/Evolution/Systems/GeneralizedHarmonic/BoundaryConditions/Factory.hpp
  src/Evolution/Systems/GeneralizedHarmonic/BoundaryConditions/RegisterDerivedWithCharm.cpp
  src/Evolution/Systems/GeneralizedHarmonic/TimeDerivative.cpp
  src/Evolution/Systems/GeneralizedHarmonic/TimeDerivative.hpp
  tests/Unit/Evolution/Systems/GeneralizedHarmonic/BoundaryConditions/Bjorhus.py
  tests/Unit/Evolution/Systems/GeneralizedHarmonic/BoundaryConditions/Test_Bjorhus.cpp
  tests/Unit/Evolution/Systems/GeneralizedHarmonic/CMakeLists.txt
  tests/Unit/Evolution/Systems/GeneralizedHarmonic/Test_DuDt.cpp
  tests/Unit/Helpers/PointwiseFunctions/AnalyticSolutions/GeneralRelativity/VerifyGrSolution.hpp
  tests/Unit/PointwiseFunctions/GeneralRelativity/ComputeGhQuantities.py
  tests/Unit/PointwiseFunctions/GeneralRelativity/ComputeSpacetimeQuantities.py
Labels: updated

#3320 Make GRMHD conserved variable fixing faster and more robust in atmosphere
  src/Evolution/Systems/GrMhd/ValenciaDivClean/FixConservatives.cpp
Labels: small

#3363 Fix missing renames of GrMhd BlastWave
  src/Evolution/Executables/GrMhd/GhValenciaDivClean/CMakeLists.txt
  tests/InputFiles/GrMhd/ValenciaDivClean/BlastWave.yaml
  tests/Unit/PointwiseFunctions/AnalyticData/GrMhd/Test_BlastWave.cpp
Labels: small

#3116 Port over upwind flux for curved scalar waves as a BoundaryCorrection
  src/Evolution/Systems/CurvedScalarWave/BoundaryCorrections/BoundaryCorrection.hpp
  src/Evolution/Systems/CurvedScalarWave/BoundaryCorrections/CMakeLists.txt
  src/Evolution/Systems/CurvedScalarWave/BoundaryCorrections/Factory.hpp
  src/Evolution/Systems/CurvedScalarWave/BoundaryCorrections/RegisterDerived.cpp
  src/Evolution/Systems/CurvedScalarWave/BoundaryCorrections/RegisterDerived.hpp
  src/Evolution/Systems/CurvedScalarWave/BoundaryCorrections/UpwindPenalty.cpp
  src/Evolution/Systems/CurvedScalarWave/BoundaryCorrections/UpwindPenalty.hpp
  src/Evolution/Systems/CurvedScalarWave/CMakeLists.txt
  src/Evolution/Systems/CurvedScalarWave/Characteristics.cpp
  src/Evolution/Systems/CurvedScalarWave/Characteristics.hpp
  src/Evolution/Systems/CurvedScalarWave/System.hpp
  src/Evolution/Systems/CurvedScalarWave/TimeDerivative.cpp
  src/Evolution/Systems/CurvedScalarWave/TimeDerivative.hpp
  src/Evolution/Systems/CurvedScalarWave/UpwindPenaltyCorrection.cpp
  src/Evolution/Systems/CurvedScalarWave/UpwindPenaltyCorrection.hpp
  tests/Unit/Evolution/Systems/CurvedScalarWave/BoundaryCorrections/Test_UpwindPenalty.cpp
  tests/Unit/Evolution/Systems/CurvedScalarWave/BoundaryCorrections/UpwindPenalty.py
  tests/Unit/Evolution/Systems/CurvedScalarWave/BoundaryCorrections/__init__.py
  tests/Unit/Evolution/Systems/CurvedScalarWave/CMakeLists.txt
  tests/Unit/Evolution/Systems/CurvedScalarWave/Test_Characteristics.cpp
  tests/Unit/Evolution/Systems/CurvedScalarWave/Test_TimeDerivative.cpp
  tests/Unit/Evolution/Systems/CurvedScalarWave/Test_UpwindPenaltyCorrection.cpp
  tests/Unit/Evolution/Systems/CurvedScalarWave/__init__.py
Labels: updated

#3249 Add multigrid solver
  docs/References.bib
  src/Domain/Structure/ChildSize.cpp
  src/Domain/Structure/ChildSize.hpp
  src/Elliptic/DiscontinuousGalerkin/DgElementArray.hpp
  src/IO/Observer/CMakeLists.txt
  src/IO/Observer/GetSectionObservationKey.hpp
  src/IO/Observer/Tags.hpp
  src/Parallel/CMakeLists.txt
  src/Parallel/GetSection.hpp
  src/Parallel/Protocols/ArrayElementsAllocator.hpp
  src/Parallel/Protocols/CMakeLists.txt
  src/ParallelAlgorithms/LinearSolver/AsynchronousSolvers/ElementActions.hpp
  src/ParallelAlgorithms/LinearSolver/Gmres/ElementActions.hpp
  src/ParallelAlgorithms/LinearSolver/Gmres/Gmres.hpp
  src/ParallelAlgorithms/LinearSolver/Multigrid/Actions/CMakeLists.txt
  src/ParallelAlgorithms/LinearSolver/Multigrid/Actions/RestrictFields.hpp
  src/ParallelAlgorithms/LinearSolver/Multigrid/CMakeLists.txt
  src/ParallelAlgorithms/LinearSolver/Multigrid/ElementActions.hpp
  src/ParallelAlgorithms/LinearSolver/Multigrid/ElementsAllocator.hpp
  src/ParallelAlgorithms/LinearSolver/Multigrid/Multigrid.hpp
  src/ParallelAlgorithms/LinearSolver/Multigrid/ObserveVolumeData.hpp
  src/ParallelAlgorithms/LinearSolver/Multigrid/Tags.hpp
  src/ParallelAlgorithms/LinearSolver/Richardson/Richardson.hpp
  src/ParallelAlgorithms/LinearSolver/Schwarz/ElementActions.hpp
  src/ParallelAlgorithms/LinearSolver/Schwarz/Schwarz.hpp
  tests/Unit/Domain/Structure/CMakeLists.txt
  tests/Unit/Domain/Structure/Test_ChildSize.cpp
  tests/Unit/Helpers/ParallelAlgorithms/LinearSolver/DistributedLinearSolverAlgorithmTestHelpers.hpp
  tests/Unit/Helpers/ParallelAlgorithms/LinearSolver/LinearSolverAlgorithmTestHelpers.hpp
  tests/Unit/Helpers/ParallelAlgorithms/LinearSolver/Multigrid/Helpers.hpp
  tests/Unit/IO/Observers/Test_Tags.cpp
  tests/Unit/ParallelAlgorithms/LinearSolver/Gmres/Test_DistributedGmresAlgorithm.cpp
  tests/Unit/ParallelAlgorithms/LinearSolver/Gmres/Test_DistributedGmresPreconditionedAlgorithm.cpp
  tests/Unit/ParallelAlgorithms/LinearSolver/Gmres/Test_ElementActions.cpp
  tests/Unit/ParallelAlgorithms/LinearSolver/Multigrid/Actions/CMakeLists.txt
  tests/Unit/ParallelAlgorithms/LinearSolver/Multigrid/Actions/Test_RestrictFields.cpp
  tests/Unit/ParallelAlgorithms/LinearSolver/Multigrid/CMakeLists.txt
  tests/Unit/ParallelAlgorithms/LinearSolver/Multigrid/Test_MultigridAlgorithm.cpp
  tests/Unit/ParallelAlgorithms/LinearSolver/Multigrid/Test_MultigridAlgorithm.yaml
  tests/Unit/ParallelAlgorithms/LinearSolver/Multigrid/Test_MultigridAlgorithmMassive.yaml
  tests/Unit/ParallelAlgorithms/LinearSolver/Multigrid/Test_MultigridPreconditionedGmresAlgorithm.cpp
  tests/Unit/ParallelAlgorithms/LinearSolver/Multigrid/Test_MultigridPreconditionedGmresAlgorithm.yaml
  tests/Unit/ParallelAlgorithms/LinearSolver/Multigrid/Test_Tags.cpp
  tools/FileTestDefs.sh
Labels: new feature

#3398 Clean up ExportCoordinates reduction files
  tests/InputFiles/ExportCoordinates/Input1D.yaml
  tests/InputFiles/ExportCoordinates/Input2D.yaml
  tests/InputFiles/ExportCoordinates/Input3D.yaml
  tests/InputFiles/ExportCoordinates/InputTimeDependent3D.yaml
Labels: bugfix
