Repository sxs-collaboration/spectre, pull requests merged in 2021-02, with the labels that each got.

#2810 Make TensorExpression member variables non-const
  src/DataStructures/Tensor/Expressions/AddSubtract.hpp
  src/DataStructures/Tensor/Expressions/Contract.hpp
  src/DataStructures/Tensor/Expressions/Product.hpp
Labels: small

#2819 Rename elliptic fluxes and sources computer type aliases
  src/Elliptic/DiscontinuousGalerkin/ImposeInhomogeneousBoundaryConditionsOnSource.hpp
  src/Elliptic/Executables/Elasticity/SolveElasticityProblem.hpp
  src/Elliptic/Executables/Poisson/SolvePoissonProblem.hpp
  src/Elliptic/Systems/Elasticity/FirstOrderSystem.hpp
  src/Elliptic/Systems/Poisson/FirstOrderSystem.hpp
  tests/Unit/Elliptic/DiscontinuousGalerkin/Test_ImposeInhomogeneousBoundaryConditionsOnSource.cpp
  tests/Unit/Elliptic/Systems/Poisson/Test_Equations.cpp
  tests/Unit/Helpers/Elliptic/FirstOrderSystem.hpp
  tests/Unit/Helpers/PointwiseFunctions/AnalyticSolutions/FirstOrderEllipticSolutionsTestHelpers.hpp
  tests/Unit/PointwiseFunctions/AnalyticSolutions/Elasticity/Test_BentBeam.cpp
  tests/Unit/PointwiseFunctions/AnalyticSolutions/Elasticity/Test_HalfSpaceMirror.cpp
  tests/Unit/PointwiseFunctions/AnalyticSolutions/Poisson/Test_Lorentzian.cpp
  tests/Unit/PointwiseFunctions/AnalyticSolutions/Poisson/Test_Moustache.cpp
  tests/Unit/PointwiseFunctions/AnalyticSolutions/Poisson/Test_ProductOfSinusoids.cpp
Labels: small

#2834 Restore CI: Fix a renamed type alias
  tests/Unit/PointwiseFunctions/AnalyticSolutions/Elasticity/Test_Zero.cpp
  tests/Unit/PointwiseFunctions/AnalyticSolutions/Poisson/Test_Zero.cpp
Labels: bugfix, priority

#2825 Restore behaviour of InitializeMortars
  src/ParallelAlgorithms/DiscontinuousGalerkin/InitializeDomain.hpp
  src/ParallelAlgorithms/DiscontinuousGalerkin/InitializeMortars.hpp
  tests/Unit/ParallelAlgorithms/DiscontinuousGalerkin/Test_InitializeMortars.cpp
Labels: bugfix

#2842 Fix linking of DomainBoundaryConditions lib
  src/Domain/BoundaryConditions/CMakeLists.txt
Labels: bugfix, priority

#2835 Update Ocean to blaze 3.8
  support/Environments/ocean_clang.sh
  support/Environments/ocean_gcc.sh
  support/Environments/ocean_orca0_gcc.sh
Labels: small

#2856 Fix an error message in an assert
  src/DataStructures/ApplyMatrices.hpp
Labels: bugfix

#2881 Support addition and subtraction of doubles with TensorExpressions
  src/DataStructures/Tensor/Expressions/AddSubtract.hpp
  tests/Unit/DataStructures/Tensor/Expressions/Test_AddSubtract.cpp
Labels: updated

#2897 Pin a package version for release script
  .github/scripts/requirements-release.txt
Labels: bugfix

#2896 Fix an issue with CMake <3.15
  cmake/SpectreSetupPythonPackage.cmake
Labels: bugfix

#2890 Fix round-robin element allocation in elliptic executables
  src/Elliptic/DiscontinuousGalerkin/DgElementArray.hpp
Labels: small

#2895 Remove Doxygen from TensorExpression Product cpp test file
  tests/Unit/DataStructures/Tensor/Expressions/Test_Product.cpp
Labels: small

#2870 Add python bindings for get_dimension of VolumeData and pickling support for mesh
  src/IO/H5/Python/VolumeData.cpp
  src/NumericalAlgorithms/Spectral/Python/Mesh.cpp
  tests/Unit/IO/Test_VolumeData.py
  tests/Unit/NumericalAlgorithms/Spectral/Python/Test_Mesh.py
Labels: small
