Repository sxs-collaboration/spectre, pull requests merged in 2021-06, with the labels that each got.

#3237 Loosen approx for Teukolsky test
  tests/Unit/Evolution/Systems/Cce/AnalyticSolutions/Test_TeukolskyWave.cpp
Labels: bugfix, small

#3236 Add radial partitioning check and improve help strings
  src/Domain/Creators/Shell.cpp
  src/Domain/Creators/Shell.hpp
Labels: small

#3231 Add hydro tag LorentzFactorTimesSpatialVelocity
  src/PointwiseFunctions/Hydro/Tags.hpp
  src/PointwiseFunctions/Hydro/TagsDeclarations.hpp
  tests/Unit/PointwiseFunctions/Hydro/Test_Tags.cpp
Labels: small

#3000 Constraint-preserving boundary terms for VMinus (GH)
  docs/References.bib
  src/Evolution/Systems/GeneralizedHarmonic/BoundaryConditions/BjorhusImpl.cpp
  src/Evolution/Systems/GeneralizedHarmonic/BoundaryConditions/BjorhusImpl.hpp
  tests/Unit/Evolution/Systems/GeneralizedHarmonic/BoundaryConditions/Bjorhus.py
  tests/Unit/Evolution/Systems/GeneralizedHarmonic/BoundaryConditions/Test_BjorhusImpl.cpp
  tests/Unit/PointwiseFunctions/GeneralRelativity/Test_WeylPropagating.cpp
  tests/Unit/PointwiseFunctions/GeneralRelativity/WeylPropagating.py
Labels: updated

#3251 Increase timeout for Schwarzschild input file test
  tests/InputFiles/Xcts/Schwarzschild.yaml
Labels: bugfix, priority

#3252 Add explicit instantiation: Kastaun, NewmanHamlin, Palenzuela to PrimitiveFromConservative
  src/Evolution/Systems/GrMhd/ValenciaDivClean/PrimitiveFromConservative.cpp
Labels: small

#3250 Fix RicciScalarScalar Argument Tag
  src/ApparentHorizons/Tags.hpp
  src/ApparentHorizons/TagsDeclarations.hpp
  tests/Unit/ApparentHorizons/Test_Tags.cpp
Labels: bugfix

#3265 Subcell resize dt(vars) and link IO lib
  src/Evolution/DgSubcell/Actions/Initialize.hpp
  src/Evolution/DgSubcell/CMakeLists.txt
  tests/Unit/Evolution/DgSubcell/Actions/Test_Initialize.cpp
Labels: small

#3259 Work around a bug in gcc 7.3
  tests/Unit/Elliptic/DiscontinuousGalerkin/Test_DgOperator.cpp
Labels: bugfix

#3277 Fix doxygen formatting
  src/PointwiseFunctions/GeneralRelativity/Transform.hpp
Labels: bugfix

#3296 Test_CylindricalSide: Don't put proj point near edge.
  tests/Unit/Domain/CoordinateMaps/Test_CylindricalSide.cpp
Labels: bugfix

#3301 Load updated git module on Caltech HPC
  support/Environments/caltech_hpc_gcc.sh
Labels: bugfix, small

#3308 fix slicing `inverse_spatial_metric` onto boundary for systems with curved backgrounds
  src/Evolution/DiscontinuousGalerkin/Actions/BoundaryConditionsImpl.hpp
Labels: bugfix, small

#3305 Change stride argument type from `float` to `int` in InterpolateVolumeData
  src/Visualization/Python/InterpolateVolumeData.py
Labels: bugfix, small

#3245 Compute AddSub symmetry using operand symmetries and index orders
  src/DataStructures/Tensor/Expressions/AddSubtract.hpp
  tests/Unit/DataStructures/Tensor/Expressions/CMakeLists.txt
  tests/Unit/DataStructures/Tensor/Expressions/Test_AddSubSymmetry.cpp
  tests/Unit/DataStructures/Tensor/Expressions/Test_AddSubtract.cpp
Labels: bugfix, updated

#3313 Fix linking in DenseTriggerHelpers and GhGrMhd
  src/PointwiseFunctions/AnalyticData/GhGrMhd/CMakeLists.txt
  src/PointwiseFunctions/AnalyticSolutions/GhGrMhd/CMakeLists.txt
  src/PointwiseFunctions/AnalyticSolutions/GhRelativisticEuler/CMakeLists.txt
  tests/Unit/Helpers/Evolution/EventsAndDenseTriggers/DenseTriggers/CMakeLists.txt
Labels: bugfix

#3314 fix format for doxygen grouping
  src/DataStructures/Tensor/Expressions/AddSubtract.hpp
Labels: bugfix

#3318 Fix some more linking
  src/Elliptic/DiscontinuousGalerkin/CMakeLists.txt
  src/Evolution/Systems/Burgers/CMakeLists.txt
  src/Evolution/Systems/CurvedScalarWave/CMakeLists.txt
  src/Evolution/Systems/CurvedScalarWave/Equations.hpp
  src/Evolution/Systems/GeneralizedHarmonic/CMakeLists.txt
  src/Evolution/Systems/GeneralizedHarmonic/GaugeSourceFunctions/CMakeLists.txt
  src/Evolution/Systems/GrMhd/GhValenciaDivClean/CMakeLists.txt
  src/Evolution/Systems/GrMhd/ValenciaDivClean/CMakeLists.txt
  src/Evolution/Systems/NewtonianEuler/Sources/CMakeLists.txt
  src/Evolution/Systems/ScalarWave/CMakeLists.txt
  src/PointwiseFunctions/AnalyticData/NewtonianEuler/CMakeLists.txt
  tests/Unit/Elliptic/CMakeLists.txt
  tests/Unit/Helpers/ControlSystem/CMakeLists.txt
  tests/Unit/Helpers/DataStructures/CMakeLists.txt
  tests/Unit/Helpers/DataStructures/DataBox/CMakeLists.txt
  tests/Unit/Helpers/Domain/CMakeLists.txt
  tests/Unit/Helpers/Time/TimeSteppers/CMakeLists.txt
  tests/Unit/Helpers/Time/TimeSteppers/TimeStepperTestUtils.hpp
Labels: bugfix

#3316 Bayliss Turkel documentation correction
  src/Evolution/Systems/ScalarWave/BoundaryConditions/ConstraintPreservingSphericalRadiation.hpp
Labels: bugfix, documentation, small

#3269 Support generic spatial indices for spacetime indices in TensorExpressions except AddSub
  src/DataStructures/Tensor/Expressions/CMakeLists.txt
  src/DataStructures/Tensor/Expressions/Contract.hpp
  src/DataStructures/Tensor/Expressions/Evaluate.hpp
  src/DataStructures/Tensor/Expressions/LhsTensorSymmAndIndices.hpp
  src/DataStructures/Tensor/Expressions/SpatialSpacetimeIndex.hpp
  src/DataStructures/Tensor/Expressions/TensorAsExpression.hpp
  src/DataStructures/Tensor/IndexType.hpp
  src/DataStructures/Tensor/Tensor.hpp
  tests/Unit/DataStructures/Tensor/Expressions/CMakeLists.txt
  tests/Unit/DataStructures/Tensor/Expressions/Test_Contract.cpp
  tests/Unit/DataStructures/Tensor/Expressions/Test_EvaluateSpatialSpacetimeIndex.cpp
  tests/Unit/DataStructures/Tensor/Expressions/Test_Product.cpp
  tests/Unit/DataStructures/Tensor/Expressions/Test_SquareRoot.cpp
Labels: updated

#3334 Fix factory creation in new GH+MHD executable
  src/Evolution/Executables/GrMhd/GhValenciaDivClean/EvolveGhValenciaDivCleanWithHorizon.hpp
  src/Evolution/Executables/GrMhd/GhValenciaDivClean/GhValenciaDivCleanBase.hpp
Labels: bugfix, priority

#3332 Make the Krivodonova limiter copyable
  src/Evolution/DiscontinuousGalerkin/Limiters/Krivodonova.hpp
Labels: small
