Repository sxs-collaboration/spectre, pull requests merged in 2022-04, with the labels that each got.

#3906 Fix test linking on macOS
  src/DataStructures/MathWrapper.hpp
  tests/Unit/Helpers/DataStructures/CMakeLists.txt
  tests/Unit/Helpers/DataStructures/MathWrapper.hpp
  tests/Unit/Helpers/DataStructures/MathWrapperDetail.cpp
  tests/Unit/Helpers/DataStructures/MathWrapperDetail.hpp
Labels: priority, bugfix

#3908 Increase timeout of a test
  tests/Unit/Domain/Creators/Test_BinaryCompactObject.cpp
Labels: small, bugfix

#3913 Make element_logical_coordinates deterministic
  src/Domain/ElementLogicalCoordinates.cpp
  src/Domain/ElementLogicalCoordinates.hpp
  tests/Unit/Domain/Test_BlockAndElementLogicalCoordinates.cpp
Labels: priority

#3920 Simplify control system observations
  src/ControlSystem/WriteData.hpp
  tests/Unit/ControlSystem/Test_WriteData.cpp
Labels: small

#3922 Add a missing newline in error message
  src/ParallelAlgorithms/NonlinearSolver/NewtonRaphson/ResidualMonitorActions.hpp
Labels: small, bugfix

#3925 Remove some unnecessary time stuff
  src/Evolution/Executables/Burgers/EvolveBurgers.hpp
  src/Evolution/Executables/CurvedScalarWave/EvolveCurvedScalarWave.hpp
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGhBinaryBlackHole.hpp
  src/Evolution/Executables/GeneralizedHarmonic/GeneralizedHarmonicBase.hpp
  src/Evolution/Executables/GrMhd/GhValenciaDivClean/GhValenciaDivCleanBase.hpp
  src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivClean.hpp
  src/Evolution/Executables/NewtonianEuler/EvolveNewtonianEuler.hpp
  src/Evolution/Executables/RadiationTransport/M1Grey/EvolveM1Grey.hpp
  src/Evolution/Executables/RelativisticEuler/Valencia/EvolveValencia.hpp
  src/Evolution/Executables/ScalarAdvection/EvolveScalarAdvection.hpp
  src/Evolution/Executables/ScalarWave/EvolveScalarWave.hpp
  src/Evolution/Initialization/Evolution.hpp
  src/Evolution/Systems/Cce/Actions/InitializeCharacteristicEvolutionTime.hpp
  src/Time/Actions/SelfStartActions.hpp
  src/Time/StepChoosers/Cfl.hpp
  src/Time/StepChoosers/ElementSizeCfl.hpp
  src/Time/Tags.hpp
  tests/Unit/Evolution/DiscontinuousGalerkin/Actions/Test_ApplyBoundaryCorrections.cpp
  tests/Unit/Time/Actions/Test_SelfStartActions.cpp
  tests/Unit/Time/Actions/Test_UpdateU.cpp
  tests/Unit/Time/StepChoosers/Test_Cfl.cpp
  tests/Unit/Time/StepChoosers/Test_ElementSizeCfl.cpp
  tests/Unit/Time/Test_Tags.cpp
  tests/Unit/Time/Test_TakeStep.cpp
Labels: auto-merge

#3932 Update GitHub checkout action to v3.0.1
  .github/workflows/NewContributors.yaml
  .github/workflows/PostRelease.yaml
  .github/workflows/Tests.yaml
Labels: priority, bugfix

#3935 Fix CI failure on develop
  .github/workflows/Tests.yaml
Labels: bugfix

#3918 Add LinearLeastSquares solver
  src/NumericalAlgorithms/Interpolation/CMakeLists.txt
  src/NumericalAlgorithms/Interpolation/LinearLeastSquares.cpp
  src/NumericalAlgorithms/Interpolation/LinearLeastSquares.hpp
  tests/Unit/NumericalAlgorithms/Interpolation/CMakeLists.txt
  tests/Unit/NumericalAlgorithms/Interpolation/Test_LinearLeastSquares.cpp
Labels: auto-merge

#3944 Fix ComputeVarsToInterpolate protocol
  src/ParallelAlgorithms/Interpolation/Protocols/ComputeVarsToInterpolate.hpp
Labels: small, bugfix

#3947 Enable compile flags for toggling SpECTRE inlining
  CMakeLists.txt
  cmake/SetupSpectreInlining.cmake
  docs/DevGuide/BuildSystem.md
  src/Utilities/ForceInline.hpp
Labels: small

#3946 Allow MockDistributedObject to be sized
  tests/Unit/Framework/MockDistributedObject.hpp
  tests/Unit/Framework/Tests/Test_ActionTesting.cpp
Labels: small

#3943 Add function to determine if element is zeroth element
  src/Domain/Structure/ElementId.cpp
  src/Domain/Structure/ElementId.hpp
  tests/Unit/Domain/Structure/Test_ElementId.cpp
Labels: small
