Repository sxs-collaboration/spectre, pull requests merged in 2022-09, with the labels that each got.

#4194 Disable HDF5 default initialize datasets
  src/IO/H5/Helpers.cpp
Labels: small

#4193 Push new `demo` Docker image on PostRelease workflow
  .github/workflows/DemoContainer.yaml
  .github/workflows/PostRelease.yaml
  docs/DevGuide/QuickStartDockerVSCode.md
  docs/Images/Tutorials/beginners_tutorial/beginners_paraview_left.png
  docs/Images/Tutorials/beginners_tutorial/beginners_paraview_top.png
  docs/Images/Tutorials/beginners_tutorial/paraview_connect.png
  docs/Images/Tutorials/beginners_tutorial/paraview_server.png
  docs/Installation/Installation.md
  docs/Tutorials/BeginnersTutorial.md
  support/DevEnvironments/.devcontainer/cmake-kits.json
  support/DevEnvironments/.devcontainer/devcontainer.json
Labels: documentation

#4188 Upgrade docs stylesheets
  cmake/SetupDoxygen.cmake
  docs/Doxyfile.in
  docs/config/doxygen-awesome-fragment-copy-button.js
  docs/config/doxygen-awesome-paragraph-link.js
  docs/config/doxygen-awesome-sidebar-only.css
  docs/config/doxygen-awesome.css
  docs/config/header.html
  tools/FileTestDefs.sh
Labels: documentation

#4203 Increase timeouts of expensive tests
  tests/InputFiles/Cce/AnalyticTestRobinsonTrautman.yaml
  tests/InputFiles/ExportCoordinates/InputTimeDependent3D.yaml
  tests/InputFiles/Xcts/BinaryBlackHole.yaml
  tests/Unit/Evolution/Systems/GeneralizedHarmonic/Test_Constraints.cpp
Labels: small

#4204 Check only actual #includes in file test
  tools/FileTestDefs.sh
Labels: bugfix

#4111 Allow TOV executables to use generic equations of state
  src/Evolution/Executables/GrMhd/GhValenciaDivClean/EvolveGhValenciaDivClean.hpp
  src/Evolution/Executables/GrMhd/GhValenciaDivClean/GhValenciaDivCleanBase.hpp
  src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivClean.hpp
  src/Evolution/Executables/NewtonianEuler/EvolveNewtonianEuler.hpp
  src/Evolution/Executables/RelativisticEuler/Valencia/EvolveValencia.hpp
  src/Evolution/Initialization/ConservativeSystem.hpp
  src/NumericalAlgorithms/Interpolation/CubicSpline.cpp
  src/NumericalAlgorithms/Interpolation/CubicSpline.hpp
  src/PointwiseFunctions/AnalyticData/GrMhd/MagnetizedTovStar.cpp
  src/PointwiseFunctions/AnalyticData/GrMhd/MagnetizedTovStar.hpp
  src/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/Tov.cpp
  src/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/Tov.hpp
  src/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/TovStar.cpp
  src/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/TovStar.hpp
  src/PointwiseFunctions/Hydro/EquationsOfState/CMakeLists.txt
  src/PointwiseFunctions/Hydro/EquationsOfState/DarkEnergyFluid.cpp
  src/PointwiseFunctions/Hydro/EquationsOfState/DarkEnergyFluid.hpp
  src/PointwiseFunctions/Hydro/EquationsOfState/Enthalpy.cpp
  src/PointwiseFunctions/Hydro/EquationsOfState/Enthalpy.hpp
  src/PointwiseFunctions/Hydro/EquationsOfState/EquationOfState.hpp
  src/PointwiseFunctions/Hydro/EquationsOfState/HybridEos.cpp
  src/PointwiseFunctions/Hydro/EquationsOfState/HybridEos.hpp
  src/PointwiseFunctions/Hydro/EquationsOfState/IdealFluid.cpp
  src/PointwiseFunctions/Hydro/EquationsOfState/IdealFluid.hpp
  src/PointwiseFunctions/Hydro/EquationsOfState/PolytropicFluid.cpp
  src/PointwiseFunctions/Hydro/EquationsOfState/PolytropicFluid.hpp
  src/PointwiseFunctions/Hydro/EquationsOfState/RegisterDerivedWithCharm.cpp
  src/PointwiseFunctions/Hydro/EquationsOfState/RegisterDerivedWithCharm.hpp
  src/PointwiseFunctions/Hydro/EquationsOfState/Spectral.cpp
  src/PointwiseFunctions/Hydro/EquationsOfState/Spectral.hpp
  src/PointwiseFunctions/Hydro/Tags.hpp
  tests/InputFiles/GrMhd/GhValenciaDivClean/GhMhdTovStar.yaml
  tests/Unit/Evolution/Initialization/CMakeLists.txt
  tests/Unit/Evolution/Initialization/Test_ConservativeSystem.cpp
  tests/Unit/Evolution/Initialization/Test_SetVariables.cpp
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_GrTagsForHydro.cpp
  tests/Unit/Helpers/PointwiseFunctions/Hydro/EquationsOfState/TestHelpers.hpp
  tests/Unit/NumericalAlgorithms/Interpolation/Test_CubicSpline.cpp
  tests/Unit/NumericalAlgorithms/Interpolation/Test_IrregularInterpolant.cpp
  tests/Unit/PointwiseFunctions/AnalyticData/GrMhd/Test_MagnetizedTovStar.cpp
  tests/Unit/PointwiseFunctions/AnalyticSolutions/GhRelativisticEuler/Test_InstantiateWrappedGr.cpp
  tests/Unit/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/Python/Test_Tov.py
  tests/Unit/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/Test_Tov.cpp
  tests/Unit/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/Test_TovStar.cpp
  tests/Unit/PointwiseFunctions/Hydro/EquationsOfState/Test_DarkEnergyFluid.cpp
  tests/Unit/PointwiseFunctions/Hydro/EquationsOfState/Test_Enthalpy.cpp
  tests/Unit/PointwiseFunctions/Hydro/EquationsOfState/Test_HybridEos.cpp
  tests/Unit/PointwiseFunctions/Hydro/EquationsOfState/Test_IdealFluid.cpp
  tests/Unit/PointwiseFunctions/Hydro/EquationsOfState/Test_PolytropicFluid.cpp
  tests/Unit/PointwiseFunctions/Hydro/EquationsOfState/Test_SpectralEoS.cpp
Labels: in progress

#4220 Add TimeAndPrevious tag
  src/Time/Tags.hpp
  tests/Unit/Time/Test_Tags.cpp
Labels: small

#4211 Change default InitializeJ in input file for CharacteristicExtract
  docs/Tutorials/CCE.md
  tests/InputFiles/Cce/CharacteristicExtract.yaml
Labels: small

#4182 Fix doc bugs in CurvedScalarWave's TimeDerivative
  src/Evolution/Systems/CurvedScalarWave/TimeDerivative.hpp
Labels: documentation

#4224 Clarify Tutorial Instructions
  docs/Tutorials/BeginnersTutorial.md
  docs/Tutorials/CCE.md
  docs/Tutorials/Visualization.md
Labels: documentation, review help wanted, small

#4214 Fix vector size bug in FreeOutflow boundary condition
  src/Evolution/Systems/GrMhd/ValenciaDivClean/BoundaryConditions/FreeOutflow.cpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/BoundaryConditions/FreeOutflow.hpp
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/BoundaryConditions/FreeOutflow.py
Labels: bugfix

#4228 Add Leo in Contributors, and umiss in Affiliations
  Metadata.yaml
Labels: small

#4202 Add more docs about Tags::Time
  src/Time/Actions/AdvanceTime.hpp
  src/Time/Tags.hpp
Labels: documentation

#4234 Update ocean to gnu 11, clang 13, smp charm 7
  support/Environments/ocean_clang.sh
Labels: small

#4221 Fix the AnalyticTestCharacteristicExtract bug when inertial coordinates are evolved
  src/Evolution/Executables/Cce/CharacteristicExtract.hpp
  src/Evolution/Systems/Cce/Actions/InitializeFirstHypersurface.hpp
  src/Evolution/Systems/Cce/Components/CharacteristicEvolution.hpp
  src/Evolution/Systems/Cce/Initialize/RegisterInitializeJWithCharm.hpp
  tests/Unit/Evolution/Systems/Cce/Actions/Test_CharacteristicEvolutionBondiCalculations.cpp
  tests/Unit/Evolution/Systems/Cce/Actions/Test_InitializeFirstHypersurface.cpp
Labels: bugfix

#4237 Put GR variables on right grid for FixToAtmosphere
  src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivClean.hpp
Labels: small

#4233 Add missing target link libraries to SetupPch.cmake
  cmake/SetupPch.cmake
Labels: small, bugfix

#4242 Add Pajkos to contributors list
  Metadata.yaml
Labels: documentation, review help wanted, small

#4248 fix a mistake in the CCE tutorial
  docs/Tutorials/CCE.md
Labels: small

#4251 Put missing sqrt function in DG FreeOutflow boundary condition
  src/Evolution/Systems/GrMhd/ValenciaDivClean/BoundaryConditions/FreeOutflow.cpp
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/BoundaryConditions/FreeOutflow.py
Labels: small, bugfix

#4250 Fix a typo in the comment of GaugeUpdateInertialTimeDerivatives
  src/Evolution/Systems/Cce/GaugeTransformBoundaryData.cpp
Labels: small

#4255 Make execution order of events deterministic
  docs/Tutorials/EventsAndTriggers.md
  src/Evolution/EventsAndDenseTriggers/EventsAndDenseTriggers.cpp
  src/Evolution/EventsAndDenseTriggers/EventsAndDenseTriggers.hpp
  src/ParallelAlgorithms/EventsAndTriggers/EventsAndTriggers.hpp
  tests/InputFiles/Burgers/Step.yaml
  tests/InputFiles/CurvedScalarWave/PlaneWaveMinkowski1D.yaml
  tests/InputFiles/CurvedScalarWave/PlaneWaveMinkowski2D.yaml
  tests/InputFiles/CurvedScalarWave/PlaneWaveMinkowski3D.yaml
  tests/InputFiles/Elasticity/BentBeam.yaml
  tests/InputFiles/Elasticity/HalfSpaceMirror.yaml
  tests/InputFiles/ExportCoordinates/Input1D.yaml
  tests/InputFiles/ExportCoordinates/Input2D.yaml
  tests/InputFiles/ExportCoordinates/Input3D.yaml
  tests/InputFiles/ExportCoordinates/InputTimeDependent3D.yaml
  tests/InputFiles/GeneralizedHarmonic/BinaryBlackHole.yaml
  tests/InputFiles/GeneralizedHarmonic/GaugeWave1D.yaml
  tests/InputFiles/GeneralizedHarmonic/GaugeWave3D.yaml
  tests/InputFiles/GeneralizedHarmonic/KerrSchild.yaml
  tests/InputFiles/GrMhd/GhValenciaDivClean/GhMhdBondiMichel.yaml
  tests/InputFiles/GrMhd/GhValenciaDivClean/GhMhdTovStar.yaml
  tests/InputFiles/GrMhd/ValenciaDivClean/BlastWave.yaml
  tests/InputFiles/GrMhd/ValenciaDivClean/FishboneMoncriefDisk.yaml
  tests/InputFiles/NewtonianEuler/RiemannProblem1D.yaml
  tests/InputFiles/NewtonianEuler/RiemannProblem2D.yaml
  tests/InputFiles/NewtonianEuler/RiemannProblem3D.yaml
  tests/InputFiles/Poisson/ProductOfSinusoids1D.yaml
  tests/InputFiles/Poisson/ProductOfSinusoids2D.yaml
  tests/InputFiles/Poisson/ProductOfSinusoids3D.yaml
  tests/InputFiles/RadiationTransport/M1Grey/ConstantM1.yaml
  tests/InputFiles/RelativisticEuler/Valencia/SmoothFlow1D.yaml
  tests/InputFiles/RelativisticEuler/Valencia/SmoothFlow2D.yaml
  tests/InputFiles/RelativisticEuler/Valencia/SmoothFlow3D.yaml
  tests/InputFiles/ScalarAdvection/Krivodonova1D.yaml
  tests/InputFiles/ScalarAdvection/Kuzmin2D.yaml
  tests/InputFiles/ScalarAdvection/Sinusoid1D.yaml
  tests/InputFiles/ScalarWave/PlaneWave1D.yaml
  tests/InputFiles/ScalarWave/PlaneWave1DEventsAndTriggersExample.yaml
  tests/InputFiles/ScalarWave/PlaneWave1DObserveExample.yaml
  tests/InputFiles/ScalarWave/PlaneWave2D.yaml
  tests/InputFiles/ScalarWave/PlaneWave3D.yaml
  tests/InputFiles/Xcts/BinaryBlackHole.yaml
  tests/InputFiles/Xcts/KerrSchild.yaml
  tests/Unit/ControlSystem/Actions/Test_InitializeMeasurements.cpp
  tests/Unit/Evolution/Actions/Test_RunEventsAndDenseTriggers.cpp
  tests/Unit/Evolution/EventsAndDenseTriggers/Test_EventsAndDenseTriggers.cpp
  tests/Unit/IO/Observers/Test_RegisterEvents.cpp
  tests/Unit/ParallelAlgorithms/EventsAndTriggers/Test_EventsAndTriggers.cpp
Labels: bugfix

#4253 Slightly improving test helper floating point error
  tests/Unit/Framework/TestHelpers.hpp
  tests/Unit/Framework/Tests/Test_TestHelpers.cpp
Labels: small
