Repository sxs-collaboration/spectre, pull requests merged in 2022-01, with the labels that each got.

#3745 Add check for wrong number of names in reduction call
  src/IO/Observer/ReductionActions.hpp
Labels: small

#3748 Fix rendering of BibTeX entry in README
  README.md
Labels: bugfix

#3749 Fix CI issue with BibTeX entry
  .github/scripts/Release.py
Labels: bugfix

#3751 Fix `PYTHONPATH` in Python tests
  cmake/SpectreSetupPythonPackage.cmake
Labels: small, bugfix

#3757 Use Flattener instead of pointwise fixing in GRMHD
  src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivClean.hpp
Labels: small

#3747 Add performance section to dev guide
  docs/DevGuide/DevGuide.md
  docs/DevGuide/PerformanceGuidelines.md
Labels: documentation

#3761 Fix PCH builds with Spack
  tools/WrapPchCompiler.sh
Labels: bugfix

#3758 Add installation instructions with Spack, scheduled CI test
  .github/workflows/Spack.yaml
  docs/Installation/Installation.md
Labels: new feature

#3760 Fix BibTeX entry in publication policies
  docs/PublicationPolicy.md
Labels: documentation, bugfix

#3763 Improve error message in file comparison-type tests
  tools/CheckOutputFiles.py
Labels: small

#3770 Fix a missing function rename
  src/ApparentHorizons/StrahlkorperGr.cpp
Labels: small, bugfix
