Repository sxs-collaboration/spectre, pull requests merged in 2022-07, with the labels that each got.

#4090 Disallow antisymmetries in TensorExpressions
  src/DataStructures/Tensor/Expressions/Evaluate.hpp
  src/DataStructures/Tensor/Expressions/TensorAsExpression.hpp
Labels: small

#4094 Store number of indices in Tensor class
  src/DataStructures/Tensor/Tensor.hpp
Labels: small

#4106 Fix non-positive times in get_data_by_element
  src/IO/H5/VolumeData.cpp
  tests/Unit/Helpers/IO/VolumeData.cpp
  tests/Unit/IO/H5/Test_VolumeData.cpp
Labels: bugfix

#4110 Pin Spack version on CI
  .github/workflows/Tests.yaml
Labels: bugfix

#4120 Fix post-release workflow
  .github/workflows/PostRelease.yaml
Labels: bugfix

#4119 Update dev container and Docker/VSCode install docs
  docs/DevGuide/QuickStartDockerVSCode.md
  docs/Installation/Installation.md
  support/DevEnvironments/.devcontainer/cmake-kits.json
  support/DevEnvironments/.devcontainer/devcontainer.json
Labels: auto-merge

#4125 Fix GenerateXdmf for 2D non-surface output
  src/Visualization/Python/GenerateXdmf.py
Labels: small, bugfix

#4131 Update gfortran in cmake kit
  support/DevEnvironments/.devcontainer/cmake-kits.json
Labels: priority, small, bugfix
