Repository sxs-collaboration/spectre, pull requests merged in 2022-02, with the labels that each got.

#3776 Fix an issue with encoded accents in bib entry
  .github/scripts/Release.py
  README.md
  citation.bib
Labels: small, bugfix

#3773 Fix linking, static test libs on macOS, remove cyclic CceAnalyticSolutions lib
  cmake/SpectreAddTestLibs.cmake
  src/ApparentHorizons/CMakeLists.txt
  src/Evolution/Executables/Cce/CMakeLists.txt
  src/Evolution/Systems/Cce/AnalyticSolutions/CMakeLists.txt
  src/Evolution/Systems/Cce/CMakeLists.txt
  src/Evolution/Systems/GrMhd/ValenciaDivClean/CMakeLists.txt
  src/Evolution/Systems/RadiationTransport/M1Grey/CMakeLists.txt
  src/Evolution/Systems/RelativisticEuler/Valencia/CMakeLists.txt
  src/Evolution/Systems/ScalarAdvection/CMakeLists.txt
  tests/Unit/Evolution/Systems/Cce/Actions/CMakeLists.txt
  tests/Unit/Evolution/Systems/Cce/AnalyticSolutions/CMakeLists.txt
  tests/Unit/Helpers/Domain/CMakeLists.txt
  tests/Unit/Helpers/Evolution/DiscontinuousGalerkin/Actions/CMakeLists.txt
  tests/Unit/Helpers/Evolution/EventsAndDenseTriggers/DenseTriggers/CMakeLists.txt
  tests/Unit/Helpers/Evolution/Systems/Cce/AnalyticSolutions/CMakeLists.txt
  tests/Unit/Helpers/Evolution/Systems/Cce/CMakeLists.txt
  tests/Unit/Helpers/Time/TimeSteppers/CMakeLists.txt
Labels: bugfix

#3775 Spack CI test: disable debug symbols
  .github/workflows/Spack.yaml
Labels: small

#3777 Remove unused functions from ComputeTimeDerivative
  src/Evolution/DiscontinuousGalerkin/Actions/ComputeTimeDerivative.hpp
Labels: small

#3785 Add time to AH finder printed output
  src/ParallelAlgorithms/Interpolation/Callbacks/FindApparentHorizon.hpp
Labels: small

#3791 Print nodes on wheeler
  support/SubmitScripts/Wheeler.sh
Labels: small

#3797 Load correct libz in ocean_clang.sh
  support/Environments/ocean_clang.sh
Labels: auto-merge

#2326 Add DevGuide documentation of Brigand
  docs/DevGuide/Brigand.md
  docs/DevGuide/DevGuide.md
  docs/Installation/Installation.md
  src/Utilities/TMPL.hpp
  tests/Unit/Utilities/CMakeLists.txt
  tests/Unit/Utilities/Test_TMPLDocumentation.cpp
Labels: documentation

#3802 Fix missing Boost headers pre v1.67
  src/Elliptic/DiscontinuousGalerkin/SubdomainOperator/SubdomainOperator.hpp
  src/Elliptic/SubdomainPreconditioners/MinusLaplacian.hpp
Labels: bugfix, auto-merge

#3809 Fix Charm++ include paths on Frontera
  cmake/FindCharm.cmake
Labels: bugfix

#3821 Fix reference in brigand docs
  docs/DevGuide/Brigand.md
Labels: documentation, bugfix, auto-merge

#3762 Rename CurvedSW execs, move is_analytic_*, other analytic solution updates
  src/Elliptic/Actions/InitializeAnalyticSolution.hpp
  src/Elliptic/BoundaryConditions/AnalyticSolution.hpp
  src/Evolution/ComputeTags.hpp
  src/Evolution/DgSubcell/Events/ObserveFields.hpp
  src/Evolution/Executables/Burgers/EvolveBurgers.hpp
  src/Evolution/Executables/CurvedScalarWave/CMakeLists.txt
  src/Evolution/Executables/CurvedScalarWave/EvolveCurvedScalarWave.hpp
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGhBinaryBlackHole.hpp
  src/Evolution/Executables/GeneralizedHarmonic/GeneralizedHarmonicBase.hpp
  src/Evolution/Executables/GrMhd/GhValenciaDivClean/GhValenciaDivCleanBase.hpp
  src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivClean.hpp
  src/Evolution/Executables/NewtonianEuler/EvolveNewtonianEuler.hpp
  src/Evolution/Executables/RadiationTransport/M1Grey/EvolveM1Grey.hpp
  src/Evolution/Executables/RelativisticEuler/Valencia/EvolveValencia.hpp
  src/Evolution/Executables/ScalarAdvection/EvolveScalarAdvection.hpp
  src/Evolution/Executables/ScalarWave/EvolveScalarWave.hpp
  src/Evolution/Initialization/InitialData.hpp
  src/Evolution/Initialization/SetVariables.hpp
  src/Evolution/Systems/Burgers/BoundaryConditions/DirichletAnalytic.hpp
  src/Evolution/Systems/GeneralizedHarmonic/BoundaryConditions/DirichletAnalytic.hpp
  src/Evolution/Systems/GeneralizedHarmonic/Initialize.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/BoundaryConditions/DirichletAnalytic.hpp
  src/Evolution/Systems/NewtonianEuler/BoundaryConditions/DirichletAnalytic.hpp
  src/Evolution/Systems/NewtonianEuler/Tags.hpp
  src/Evolution/Systems/RadiationTransport/M1Grey/BoundaryConditions/DirichletAnalytic.hpp
  src/Evolution/Systems/RelativisticEuler/Valencia/BoundaryConditions/DirichletAnalytic.hpp
  src/Evolution/Systems/ScalarWave/BoundaryConditions/DirichletAnalytic.hpp
  src/Evolution/TypeTraits.hpp
  src/ParallelAlgorithms/Events/ObserveErrorNorms.hpp
  src/ParallelAlgorithms/Events/ObserveFields.hpp
  src/PointwiseFunctions/AnalyticData/AnalyticData.hpp
  src/PointwiseFunctions/AnalyticSolutions/AnalyticSolution.hpp
  src/PointwiseFunctions/AnalyticSolutions/Tags.hpp
  src/Utilities/CMakeLists.txt
  src/Utilities/OptionalHelpers.hpp
  tests/InputFiles/CurvedScalarWave/PlaneWaveMinkowski1D.yaml
  tests/InputFiles/CurvedScalarWave/PlaneWaveMinkowski2D.yaml
  tests/InputFiles/CurvedScalarWave/PlaneWaveMinkowski3D.yaml
  tests/Unit/Elliptic/Actions/Test_InitializeAnalyticSolution.cpp
  tests/Unit/Elliptic/BoundaryConditions/Test_AnalyticSolution.cpp
  tests/Unit/Elliptic/DiscontinuousGalerkin/Test_DgOperator.cpp
  tests/Unit/Evolution/CMakeLists.txt
  tests/Unit/Evolution/DgSubcell/Events/Test_ObserveFields.cpp
  tests/Unit/Evolution/Test_ComputeTags.cpp
  tests/Unit/Evolution/Test_TypeTraits.cpp
  tests/Unit/Helpers/PointwiseFunctions/AnalyticSolutions/Burgers/CheckBurgersSolution.hpp
  tests/Unit/Helpers/PointwiseFunctions/AnalyticSolutions/GeneralRelativity/VerifyGrSolution.hpp
  tests/Unit/Helpers/PointwiseFunctions/AnalyticSolutions/GrMhd/VerifyGrMhdSolution.hpp
  tests/Unit/ParallelAlgorithms/Events/Test_ObserveErrorNorms.cpp
  tests/Unit/ParallelAlgorithms/Events/Test_ObserveFields.cpp
  tests/Unit/PointwiseFunctions/AnalyticData/CMakeLists.txt
  tests/Unit/PointwiseFunctions/AnalyticData/GrMhd/Test_MagnetizedFmDisk.cpp
  tests/Unit/PointwiseFunctions/AnalyticData/GrMhd/Test_MagnetizedTovStar.cpp
  tests/Unit/PointwiseFunctions/AnalyticData/Test_AnalyticData.cpp
  tests/Unit/PointwiseFunctions/AnalyticSolutions/CMakeLists.txt
  tests/Unit/PointwiseFunctions/AnalyticSolutions/Test_AnalyticSolution.cpp
  tests/Unit/PointwiseFunctions/AnalyticSolutions/Test_Tags.cpp
  tests/Unit/Utilities/CMakeLists.txt
  tests/Unit/Utilities/Test_OptionalHelpers.cpp
Labels: auto-merge

#3827 Increase timeout of CylindricalBinaryCompactObject
  tests/Unit/Domain/Creators/Test_CylindricalBinaryCompactObject.cpp
Labels: small, auto-merge

#3816 Split ApparentHorizons/Tags.hpp
  src/ApparentHorizons/CMakeLists.txt
  src/ApparentHorizons/FastFlow.cpp
  src/ApparentHorizons/StrahlkorperGr.hpp
  src/ApparentHorizons/StrahlkorperInDifferentFrame.cpp
  src/ApparentHorizons/Tags.hpp
  src/ApparentHorizons/TagsDeclarations.hpp
  src/Evolution/Executables/CurvedScalarWave/EvolveCurvedScalarWave.hpp
  src/NumericalAlgorithms/SphericalHarmonics/CMakeLists.txt
  src/NumericalAlgorithms/SphericalHarmonics/StrahlkorperFunctions.hpp
  src/NumericalAlgorithms/SphericalHarmonics/Tags.cpp
  src/NumericalAlgorithms/SphericalHarmonics/Tags.hpp
  src/NumericalAlgorithms/SphericalHarmonics/TagsDeclarations.hpp
  src/NumericalAlgorithms/SphericalHarmonics/TagsTypeAliases.hpp
  src/ParallelAlgorithms/Interpolation/Targets/ApparentHorizon.hpp
  src/ParallelAlgorithms/Interpolation/Targets/KerrHorizon.hpp
  src/ParallelAlgorithms/Interpolation/Targets/Sphere.hpp
  tests/Unit/ApparentHorizons/Test_FastFlow.cpp
  tests/Unit/ApparentHorizons/Test_StrahlkorperGr.cpp
  tests/Unit/ApparentHorizons/Test_Tags.cpp
  tests/Unit/Helpers/ApparentHorizons/CMakeLists.txt
  tests/Unit/Helpers/NumericalAlgorithms/SphericalHarmonics/CMakeLists.txt
  tests/Unit/Helpers/NumericalAlgorithms/SphericalHarmonics/StrahlkorperTestHelpers.cpp
  tests/Unit/Helpers/NumericalAlgorithms/SphericalHarmonics/StrahlkorperTestHelpers.hpp
  tests/Unit/NumericalAlgorithms/SphericalHarmonics/CMakeLists.txt
  tests/Unit/NumericalAlgorithms/SphericalHarmonics/Test_Strahlkorper.cpp
  tests/Unit/NumericalAlgorithms/SphericalHarmonics/Test_StrahlkorperFunctions.cpp
  tests/Unit/NumericalAlgorithms/SphericalHarmonics/Test_Tags.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_ObserveTimeSeriesOnSurface.cpp
Labels: auto-merge

#3822 Add `file_system::glob`, support importing volume data from multiple files
  src/IO/Importers/Actions/ReadVolumeData.hpp
  src/IO/Importers/Tags.hpp
  src/Utilities/FileSystem.cpp
  src/Utilities/FileSystem.hpp
  tests/InputFiles/GeneralizedHarmonic/BinaryBlackHole.yaml
  tests/Unit/IO/Importers/CMakeLists.txt
  tests/Unit/IO/Importers/Test_Tags.cpp
  tests/Unit/IO/Importers/Test_VolumeDataReaderActions.cpp
  tests/Unit/IO/Importers/Test_VolumeDataReaderAlgorithm.hpp
  tests/Unit/IO/Importers/Test_VolumeDataReaderAlgorithm1D.yaml
  tests/Unit/IO/Importers/Test_VolumeDataReaderAlgorithm2D.yaml
  tests/Unit/IO/Importers/Test_VolumeDataReaderAlgorithm3D.yaml
  tests/Unit/Utilities/Test_FileSystem.cpp
Labels: new feature, auto-merge

#3824 Sort `list_observation_ids()`, support importing first or last observation ID from a volume file
  src/IO/H5/VolumeData.cpp
  src/IO/H5/VolumeData.hpp
  src/IO/Importers/Actions/ReadVolumeData.hpp
  src/IO/Importers/CMakeLists.txt
  src/IO/Importers/ObservationSelector.cpp
  src/IO/Importers/ObservationSelector.hpp
  src/IO/Importers/Tags.hpp
  tests/InputFiles/GeneralizedHarmonic/BinaryBlackHole.yaml
  tests/Unit/IO/H5/Test_VolumeData.cpp
  tests/Unit/IO/Importers/CMakeLists.txt
  tests/Unit/IO/Importers/Test_Tags.cpp
  tests/Unit/IO/Importers/Test_VolumeDataReaderActions.cpp
  tests/Unit/IO/Importers/Test_VolumeDataReaderAlgorithm.hpp
Labels: auto-merge

#3804 Add serialization, option creation to Blaze vector and matrix types
  src/DataStructures/CMakeLists.txt
  src/DataStructures/CompressedMatrix.hpp
  src/DataStructures/CompressedVector.hpp
  src/DataStructures/DynamicMatrix.hpp
  src/DataStructures/DynamicVector.hpp
  src/DataStructures/StaticMatrix.hpp
  src/DataStructures/StaticVector.hpp
  tests/Unit/DataStructures/CMakeLists.txt
  tests/Unit/DataStructures/Test_BlazeInteroperability.cpp
Labels: auto-merge

#3820 Add an example for running a BBH ID solve
  docs/Examples/BbhInitialData/.gitignore
  docs/Examples/BbhInitialData/BbhInitialData.ipynb
  src/Elliptic/Executables/Xcts/SolveXcts.hpp
  tests/InputFiles/Xcts/BinaryBlackHole.yaml
  tests/InputFiles/Xcts/KerrSchild.yaml
  tools/FileTestDefs.sh
Labels: auto-merge

#3831 Fix release checksum for Spack
  .github/workflows/PostRelease.yaml
Labels: bugfix
