Repository sxs-collaboration/spectre, pull requests merged in 2022-03, with the labels that each got.

#3836 Block implicit DataVector conversion to Variables
  src/DataStructures/Variables.hpp
  tests/Unit/DataStructures/Test_Variables.cpp
Labels: auto-merge

#3833 Enable sleef support
  cmake/FindSleef.cmake
  cmake/SetupBlaze.cmake
  docs/DevGuide/BuildSystem.md
Labels: auto-merge

#3795 Load initial data from XCTS solver in GH execs
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGeneralizedHarmonicWithHorizon.hpp
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGhBinaryBlackHole.hpp
  src/Evolution/Executables/GeneralizedHarmonic/GeneralizedHarmonicBase.hpp
  src/Evolution/Initialization/Evolution.hpp
  src/Evolution/Systems/GeneralizedHarmonic/Actions/CMakeLists.txt
  src/Evolution/Systems/GeneralizedHarmonic/Actions/NumericInitialData.hpp
  src/Evolution/Systems/GeneralizedHarmonic/CMakeLists.txt
  src/IO/Importers/Actions/ReadVolumeData.hpp
  src/IO/Importers/Actions/RegisterWithElementDataReader.hpp
  src/PointwiseFunctions/GeneralRelativity/CMakeLists.txt
  src/PointwiseFunctions/GeneralRelativity/TimeDerivativeOfSpatialMetric.cpp
  src/PointwiseFunctions/GeneralRelativity/TimeDerivativeOfSpatialMetric.hpp
  tests/InputFiles/GeneralizedHarmonic/BinaryBlackHole.yaml
  tests/Unit/Evolution/Systems/GeneralizedHarmonic/Actions/Test_NumericInitialData.cpp
  tests/Unit/Evolution/Systems/GeneralizedHarmonic/CMakeLists.txt
  tests/Unit/PointwiseFunctions/GeneralRelativity/CMakeLists.txt
  tests/Unit/PointwiseFunctions/GeneralRelativity/ComputeSpacetimeQuantities.py
  tests/Unit/PointwiseFunctions/GeneralRelativity/Test_ComputeSpacetimeQuantities.cpp
Labels: updated

#3735 Add polynomial interpolation and ability to read RotNS data
  .clang-tidy
  docs/References.bib
  src/Evolution/Executables/GrMhd/ValenciaDivClean/CMakeLists.txt
  src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivClean.hpp
  src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivCleanFwd.hpp
  src/NumericalAlgorithms/Interpolation/CMakeLists.txt
  src/NumericalAlgorithms/Interpolation/PolynomialInterpolation.cpp
  src/NumericalAlgorithms/Interpolation/PolynomialInterpolation.hpp
  src/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/CMakeLists.txt
  src/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/FishboneMoncriefDisk.hpp
  src/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/RotatingStar.cpp
  src/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/RotatingStar.hpp
  tests/Unit/NumericalAlgorithms/Interpolation/CMakeLists.txt
  tests/Unit/NumericalAlgorithms/Interpolation/Test_PolynomialInterpolation.cpp
  tests/Unit/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/CMakeLists.txt
  tests/Unit/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/RotatingStarId.dat
  tests/Unit/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/Test_RotatingStar.cpp
  tools/FileTestDefs.sh
Labels: priority, auto-merge

#3845 Fix failing exact comparison in Test_Divergence.cpp
  tests/Unit/NumericalAlgorithms/LinearOperators/Test_Divergence.cpp
Labels: bugfix

#3834 Render example notebooks in Doxygen documentation
  cmake/SetupDoxygen.cmake
  containers/Dockerfile.buildenv
  docs/Doxyfile.in
  docs/Examples/BbhInitialData/BbhInitialData.ipynb
  docs/Examples/Examples.md
  docs/Examples/plots.mplstyle
  docs/Installation/Installation.md
  docs/config/markdown-math-filter.pl
Labels: documentation, updated

#3846 Fix column numbering in ParallelInfo exec
  src/Executables/ParallelInfo/ParallelInfo.cpp
Labels: small

#3850 Use full namespace for tags in NewtonianEuler reconstructor codes
  src/Evolution/Systems/NewtonianEuler/FiniteDifference/AoWeno.hpp
  src/Evolution/Systems/NewtonianEuler/FiniteDifference/MonotisedCentral.hpp
Labels: small

#3854 Reduce log level of docs notebook conversion
  cmake/SetupDoxygen.cmake
Labels: small

#3865 Fix GH Phi tag docs
  src/Evolution/Systems/GeneralizedHarmonic/Tags.hpp
Labels: small

#3862 Xcts solver: observe shift magnitude, min and max quantities
  src/Elliptic/Executables/Xcts/SolveXcts.hpp
  tests/InputFiles/Xcts/BinaryBlackHole.yaml
Labels: small

#3858 Fix docs of KerrHorizonConforming map, disambiguate spin, add test
  src/Domain/CoordinateMaps/KerrHorizonConforming.cpp
  src/Domain/CoordinateMaps/KerrHorizonConforming.hpp
  tests/Unit/Domain/CoordinateMaps/CMakeLists.txt
  tests/Unit/Domain/CoordinateMaps/Test_KerrHorizonConforming.cpp
  tests/Unit/Elliptic/Systems/Xcts/BoundaryConditions/CMakeLists.txt
  tests/Unit/Elliptic/Systems/Xcts/BoundaryConditions/Test_ApparentHorizon.cpp
Labels: bugfix

#3869 Fix math rendering in AdamsBashforthN
  docs/config/markdown-math-filter.pl
Labels: bugfix

#3871 Fix hard coded path in CaltechHPC submit script
  support/SubmitScripts/CaltechHpc.sh
Labels: small, bugfix

#3875 Fix core devs email address in PublicationPolicy.md
  docs/PublicationPolicy.md
Labels: documentation, small

#3868 Add Factory.hpp for equations of state
  src/Evolution/Executables/GrMhd/GhValenciaDivClean/GhValenciaDivCleanBase.hpp
  src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivClean.hpp
  src/Evolution/Executables/NewtonianEuler/EvolveNewtonianEuler.hpp
  src/Evolution/Executables/RelativisticEuler/Valencia/EvolveValencia.hpp
  src/PointwiseFunctions/Hydro/EquationsOfState/CMakeLists.txt
  src/PointwiseFunctions/Hydro/EquationsOfState/EquationOfState.hpp
  src/PointwiseFunctions/Hydro/EquationsOfState/Factory.hpp
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Test_Flattener.cpp
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Test_PrimitiveFromConservative.cpp
  tests/Unit/Evolution/Systems/NewtonianEuler/Limiters/Test_Weno.cpp
  tests/Unit/Evolution/Systems/NewtonianEuler/Test_Characteristics.cpp
  tests/Unit/Evolution/Systems/RelativisticEuler/Valencia/Test_PrimitiveFromConservative.cpp
  tests/Unit/Evolution/VariableFixing/Test_FixToAtmosphere.cpp
  tests/Unit/PointwiseFunctions/AnalyticSolutions/GeneralRelativity/Test_Tov.cpp
  tests/Unit/PointwiseFunctions/Hydro/EquationsOfState/Test_DarkEnergyFluid.cpp
  tests/Unit/PointwiseFunctions/Hydro/EquationsOfState/Test_IdealFluid.cpp
  tests/Unit/PointwiseFunctions/Hydro/EquationsOfState/Test_PolytropicFluid.cpp
  tests/Unit/PointwiseFunctions/Hydro/EquationsOfState/Test_SpectralEoS.cpp
Labels: priority, small

#3879 Fix macOS CI build issue with Boost
  support/DevEnvironments/spack.yaml
Labels: bugfix

#3874 Make our registered names be consistent with Charm++'s
  src/Parallel/CharmRegistration.hpp
Labels: priority, small

#3881 Update FindApparentHorizon docs
  src/ParallelAlgorithms/Interpolation/Callbacks/FindApparentHorizon.hpp
Labels: small

#3884 Allow ReadSpecPiecewisePolynomial to create QuaternionFunctionsOfTime
  src/Domain/FunctionsOfTime/ReadSpecPiecewisePolynomial.cpp
  src/Domain/FunctionsOfTime/ReadSpecPiecewisePolynomial.hpp
  src/Domain/FunctionsOfTime/Tags.hpp
  tests/Unit/Domain/FunctionsOfTime/Test_ReadSpecPiecewisePolynomial.cpp
Labels: priority, bugfix

#3863 Compute numerical deriv diagnostic in ExportCoords
  src/Executables/ExportCoordinates/CMakeLists.txt
  src/Executables/ExportCoordinates/ExportCoordinates.hpp
  tests/InputFiles/ExportCoordinates/Input1D.yaml
  tests/InputFiles/ExportCoordinates/Input2D.yaml
  tests/InputFiles/ExportCoordinates/Input3D.yaml
  tests/InputFiles/ExportCoordinates/InputTimeDependent3D.yaml
Labels: small

#3897 Fix linking with GrSolutionsTestHelpers
  tests/Unit/Helpers/PointwiseFunctions/AnalyticSolutions/CMakeLists.txt
  tests/Unit/Helpers/PointwiseFunctions/AnalyticSolutions/GeneralRelativity/CMakeLists.txt
  tests/Unit/Helpers/PointwiseFunctions/AnalyticSolutions/GeneralRelativity/VerifyGrSolution.hpp
  tests/Unit/PointwiseFunctions/AnalyticSolutions/GeneralRelativity/CMakeLists.txt
Labels: small

#3893 Wrap HarmonicSchwarzschild solution for initial data solver
  src/PointwiseFunctions/AnalyticSolutions/Xcts/Factory.hpp
  src/PointwiseFunctions/AnalyticSolutions/Xcts/WrappedGr.cpp
  tests/Unit/PointwiseFunctions/AnalyticSolutions/Xcts/CMakeLists.txt
  tests/Unit/PointwiseFunctions/AnalyticSolutions/Xcts/Test_HarmonicSchwarzschild.cpp
Labels: small

#3894 Fix OrientationMap for Mesh
  src/Domain/Structure/OrientationMap.cpp
  src/Domain/Structure/OrientationMap.hpp
  src/Evolution/DiscontinuousGalerkin/Limiters/Krivodonova.hpp
  src/Evolution/DiscontinuousGalerkin/Limiters/Weno.hpp
  tests/Unit/Domain/Structure/Test_OrientationMap.cpp
  tests/Unit/Domain/Structure/Test_OrientationMapHelpers.cpp
Labels: bugfix
