Repository sxs-collaboration/spectre, pull requests merged in 2022-12, with the labels that each got.

#4439 Fix DistributedObject for tracing
  src/Parallel/DistributedObject.hpp
Labels: bugfix

#4444 GHMHD system class cleanup: use largest char speed and remove cyclic include
  src/Evolution/Executables/GrMhd/GhValenciaDivClean/EvolveGhValenciaDivCleanWithHorizon.hpp
  src/Evolution/Executables/GrMhd/GhValenciaDivClean/GhValenciaDivCleanBase.hpp
  src/Evolution/Systems/GrMhd/GhValenciaDivClean/System.hpp
  tests/Unit/Evolution/Systems/GrMhd/GhValenciaDivClean/BoundaryCorrections/Test_ProductOfCorrections.cpp
Labels: small

#4446 Fix depth when simplifying charm traces
  tools/CharmSimplifyTraces.py
Labels: small, bugfix

#4448 Increase a test timeout
  tests/Unit/ControlSystem/Systems/Test_RotScaleTrans.cpp
  tests/Unit/ControlSystem/Systems/Test_Shape.cpp
  tests/Unit/DataStructures/Test_ApplyMatrices.cpp
  tests/Unit/Domain/Creators/Test_BinaryCompactObject.cpp
  tests/Unit/Domain/Creators/Test_CylindricalBinaryCompactObject.cpp
  tests/Unit/Domain/Structure/Test_OrientationMapHelpers.cpp
  tests/Unit/Evolution/Systems/GrMhd/GhValenciaDivClean/FiniteDifference/Test_Derivatives.cpp
  tests/Unit/NumericalAlgorithms/FiniteDifference/Test_PositivityPreservingAdaptiveOrder.cpp
  tests/Unit/PointwiseFunctions/AnalyticSolutions/Xcts/Test_Schwarzschild.cpp
Labels: small, bugfix

#4447 Add newline to InitializeJ print statement
  src/Evolution/Systems/Cce/Initialize/InitializeJ.hpp
Labels: small

#4455 Build Python CLI with `click`, `rich` and shell completion, add `clean-output` as an example
  .github/workflows/Tests.yaml
  CMakeLists.txt
  cmake/AddInputFileTests.cmake
  cmake/ExecuteCheckOutputFilesAndClean.sh
  containers/Dockerfile.buildenv
  docs/Tutorials/Python.md
  src/PythonBindings/CMakeLists.txt
  src/PythonBindings/setup.cfg
  src/PythonBindings/shell-completion.bash
  src/PythonBindings/shell-completion.fish
  src/PythonBindings/shell-completion.zsh
  support/DevEnvironments/spack.yaml
  support/Python/__main__.py
  support/Python/requirements.txt
  tests/CMakeLists.txt
  tests/tools/CMakeLists.txt
  tests/tools/Test_CleanOutput.py
  tools/CMakeLists.txt
  tools/CleanOutput.py
Labels: new feature

#4454 Use ObserverInverseJacobian in GaugeAndDerivative tag
  src/Evolution/Systems/GeneralizedHarmonic/GaugeSourceFunctions/Tags/GaugeCondition.hpp
  tests/Unit/Evolution/Systems/GeneralizedHarmonic/GaugeSourceFunctions/Test_Tags.cpp
Labels: small

#4471 Installation dox: refer to new docker containers.
  docs/Installation/Installation.md
Labels: documentation, bugfix

#4458 Don't override functions of time in BBH
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGhBinaryBlackHole.hpp
  tests/InputFiles/GeneralizedHarmonic/BinaryBlackHole.yaml
Labels: small

#4466 Decouple metavariables and LTS in step chooser simple tags
  src/Evolution/Executables/Burgers/EvolveBurgers.hpp
  src/Evolution/Executables/CurvedScalarWave/EvolveCurvedScalarWave.hpp
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGhBinaryBlackHole.hpp
  src/Evolution/Executables/GeneralizedHarmonic/GeneralizedHarmonicBase.hpp
  src/Evolution/Executables/GrMhd/GhValenciaDivClean/GhValenciaDivCleanBase.hpp
  src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivClean.hpp
  src/Evolution/Executables/NewtonianEuler/EvolveNewtonianEuler.hpp
  src/Evolution/Executables/RadiationTransport/M1Grey/EvolveM1Grey.hpp
  src/Evolution/Executables/RelativisticEuler/Valencia/EvolveValencia.hpp
  src/Evolution/Executables/ScalarAdvection/EvolveScalarAdvection.hpp
  src/Evolution/Executables/ScalarWave/EvolveScalarWave.hpp
  src/Evolution/Initialization/Evolution.hpp
  src/Evolution/Systems/Cce/Actions/InitializeCharacteristicEvolutionVariables.hpp
  src/Time/StepChoosers/StepChooser.hpp
  tests/Unit/Evolution/Systems/Cce/Actions/Test_CharacteristicEvolutionBondiCalculations.cpp
  tests/Unit/Evolution/Systems/Cce/Actions/Test_GhBoundaryCommunication.cpp
  tests/Unit/Evolution/Systems/Cce/Actions/Test_H5BoundaryCommunication.cpp
  tests/Unit/Evolution/Systems/Cce/Actions/Test_InitializeCharacteristicEvolution.cpp
  tests/Unit/Evolution/Systems/Cce/Actions/Test_RequestBoundaryData.cpp
Labels: priority, bugfix

#4485 Fix bug in UpdateU
  src/Time/Actions/UpdateU.hpp
Labels: bugfix

#4470 Use Auto singleton info holder in singleton pack
  src/Parallel/ResourceInfo.hpp
  tests/InputFiles/GeneralizedHarmonic/BinaryBlackHole.yaml
  tests/Unit/Parallel/Test_ResourceInfo.cpp
Labels: small

#4465 Add piecewise polytrope EoS
  docs/References.bib
  src/PointwiseFunctions/Hydro/EquationsOfState/CMakeLists.txt
  src/PointwiseFunctions/Hydro/EquationsOfState/EquationOfState.hpp
  src/PointwiseFunctions/Hydro/EquationsOfState/Factory.hpp
  src/PointwiseFunctions/Hydro/EquationsOfState/PiecewisePolytropicFluid.cpp
  src/PointwiseFunctions/Hydro/EquationsOfState/PiecewisePolytropicFluid.hpp
  src/PointwiseFunctions/Hydro/EquationsOfState/Python/Bindings.cpp
  src/PointwiseFunctions/Hydro/EquationsOfState/Python/CMakeLists.txt
  src/PointwiseFunctions/Hydro/EquationsOfState/Python/PiecewisePolytropicFluid.cpp
  src/PointwiseFunctions/Hydro/EquationsOfState/Python/PiecewisePolytropicFluid.hpp
  tests/Unit/PointwiseFunctions/Hydro/EquationsOfState/CMakeLists.txt
  tests/Unit/PointwiseFunctions/Hydro/EquationsOfState/PiecewisePolytropicFluid.py
  tests/Unit/PointwiseFunctions/Hydro/EquationsOfState/Python/CMakeLists.txt
  tests/Unit/PointwiseFunctions/Hydro/EquationsOfState/Python/Test_PiecewisePolytropicFluid.py
  tests/Unit/PointwiseFunctions/Hydro/EquationsOfState/Test_PiecewisePolytropicFluid.cpp
Labels: new feature

#4497 Loosen d_a H_b tolerance in GH DuDt
  tests/Unit/Evolution/Systems/GeneralizedHarmonic/Test_DuDt.cpp
Labels: small

#4493 Fix tags in GHMHD dirichlet analytic boundary condition
  src/Evolution/Systems/GrMhd/GhValenciaDivClean/BoundaryConditions/DirichletAnalytic.hpp
  tests/Unit/Evolution/Systems/GrMhd/GhValenciaDivClean/BoundaryConditions/Test_DirichletAnalytic.cpp
Labels: small

#4499 Make constructor explicit in GH CP BC
  src/Evolution/Systems/GeneralizedHarmonic/BoundaryConditions/Bjorhus.hpp
Labels: small

#4501 Fix bugs in GRMHD NeighborPackagedData test
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_NeighborPackagedData.cpp
Labels: bugfix

#4505 Fix types in GHMHD reconstruction
  src/Evolution/Systems/GrMhd/GhValenciaDivClean/FiniteDifference/MonotonisedCentral.cpp
  tests/Unit/Helpers/Evolution/Systems/GrMhd/GhValenciaDivClean/FiniteDifference/PrimReconstructor.hpp
Labels: bugfix

#4451 Interpolator only recognizes targets that use the Interpolator
  src/ParallelAlgorithms/Interpolation/Actions/InterpolatorReceiveVolumeData.hpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_InterpolatorReceiveAndDumpVolumeData.cpp
Labels: bugfix

#4490 FixedSpeedCubic: add stream operator.
  src/Domain/FunctionsOfTime/FixedSpeedCubic.cpp
  src/Domain/FunctionsOfTime/FixedSpeedCubic.hpp
  tests/Unit/Domain/FunctionsOfTime/Test_FixedSpeedCubic.cpp
Labels: small

#4503 GHMHD pass variables to time derivative
  src/Evolution/Systems/GrMhd/GhValenciaDivClean/TimeDerivativeTerms.hpp
  src/Evolution/Systems/GrMhd/GhValenciaDivClean/VolumeTermsInstantiation.cpp
  tests/Unit/Evolution/Systems/GrMhd/GhValenciaDivClean/Test_TimeDerivativeTerms.cpp
Labels: dependent

#4516 Fix docs about GenerateXdmf
  docs/DevGuide/QuickStartDockerVSCode.md
  docs/Tutorials/BeginnersTutorial.md
  docs/Tutorials/Visualization.md
Labels: documentation, bugfix

#4519 Add subcell to GH+GRMHD executable
  src/Evolution/Executables/GrMhd/GhValenciaDivClean/CMakeLists.txt
  src/Evolution/Executables/GrMhd/GhValenciaDivClean/EvolveGhValenciaDivClean.hpp
  src/Evolution/Executables/GrMhd/GhValenciaDivClean/EvolveGhValenciaDivCleanWithHorizon.hpp
  src/Evolution/Executables/GrMhd/GhValenciaDivClean/GhValenciaDivCleanBase.hpp
  tests/InputFiles/GrMhd/GhValenciaDivClean/GhMhdBondiMichel.yaml
  tests/InputFiles/GrMhd/GhValenciaDivClean/GhMhdTovStar.yaml
Labels: new feature

#4510 Fix a bug at roundoff error in block_logical_coords
  src/Domain/BlockLogicalCoordinates.cpp
  src/Domain/BlockLogicalCoordinates.hpp
  tests/Unit/Domain/Test_BlockAndElementLogicalCoordinates.cpp
Labels: bugfix

#4536 Fix bug in rootfind for enthalpy parametrization
  src/PointwiseFunctions/Hydro/EquationsOfState/Enthalpy.cpp
  tests/Unit/PointwiseFunctions/Hydro/EquationsOfState/Test_Enthalpy.cpp
Labels: small, bugfix

#4524 Fix issues with non-owning VectorImpls
  src/DataStructures/VectorImpl.hpp
  src/Evolution/Systems/Cce/PrecomputeCceDependencies.cpp
  tests/Unit/Evolution/Systems/Cce/Test_LinearSolve.cpp
  tests/Unit/Helpers/DataStructures/VectorImplTestHelper.hpp
Labels: bugfix
