Repository sxs-collaboration/spectre, pull requests merged in 2022-11, with the labels that each got.

#4341 Remove FIXMEs from AnalyticData and AnalyticSolutions
  src/PointwiseFunctions/AnalyticData/GrMhd/BondiHoyleAccretion.cpp
  src/PointwiseFunctions/AnalyticData/GrMhd/KhInstability.cpp
  src/PointwiseFunctions/AnalyticData/GrMhd/MagneticFieldLoop.cpp
  src/PointwiseFunctions/AnalyticData/GrMhd/MagneticRotor.cpp
  src/PointwiseFunctions/AnalyticData/GrMhd/OrszagTangVortex.cpp
  src/PointwiseFunctions/AnalyticData/GrMhd/RiemannProblem.cpp
  src/PointwiseFunctions/AnalyticSolutions/GrMhd/BondiMichel.cpp
  src/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/RotatingStar.cpp
  src/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/TovStar.cpp
Labels: small

#4348 Add tnsr::aI and fix GHMHD FD TCI
  src/DataStructures/Tensor/TypeAliases.hpp
  src/Evolution/Systems/GrMhd/GhValenciaDivClean/Subcell/TciOnFdGrid.hpp
Labels: small

#4345 Update conditions in TimescaleTuner
  src/ControlSystem/TimescaleTuner.cpp
  src/ControlSystem/TimescaleTuner.hpp
  tests/Unit/ControlSystem/Test_TimescaleTuner.cpp
Labels: small

#4352 Use lapse and shift to compute the largest char speed in GRMHD
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Characteristics.hpp
Labels: small

#4360 Fix magnetic field sign error in MagnetizedTovStar analytic data
  src/PointwiseFunctions/AnalyticData/GrMhd/MagnetizedTovStar.cpp
  src/PointwiseFunctions/AnalyticData/GrMhd/MagnetizedTovStar.hpp
  tests/Unit/PointwiseFunctions/AnalyticData/GrMhd/Test_MagnetizedTovStar.cpp
Labels: bugfix

#4365 Fix sign error in FixedSpeedCubic 2nd deriv
  src/Domain/FunctionsOfTime/FixedSpeedCubic.cpp
  tests/Unit/Domain/FunctionsOfTime/Test_FixedSpeedCubic.cpp
Labels: bugfix

#4359 Remove backtrace from a simple error message
  src/Parallel/Main.hpp
Labels: small

#4362 Add more observables to BBH
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGhBinaryBlackHole.hpp
  tests/InputFiles/GeneralizedHarmonic/BinaryBlackHole.yaml
Labels: small

#4369 Fix IO volume data docs about tensor component names
  src/DataStructures/Tensor/TensorData.hpp
  src/IO/H5/VolumeData.hpp
Labels: documentation, bugfix

#4375 Fix #4374
  src/Informer/InfoAtLinkExtractFlags.py
Labels: bugfix

#4384 Add ForceFree to the ctest labels
  cmake/SpectreParseTests.py
Labels: small

#4386 Use ccache module on Wheeler
  support/Environments/wheeler_clang.sh
  support/Environments/wheeler_gcc.sh
Labels: small

#4350 Core-collapse Supernova Profile Readin
  docs/References.bib
  src/Evolution/Executables/GrMhd/ValenciaDivClean/CMakeLists.txt
  src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivClean.hpp
  src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivCleanFwd.hpp
  src/PointwiseFunctions/AnalyticData/GrMhd/CMakeLists.txt
  src/PointwiseFunctions/AnalyticData/GrMhd/CcsnCollapse.cpp
  src/PointwiseFunctions/AnalyticData/GrMhd/CcsnCollapse.hpp
  tests/Unit/PointwiseFunctions/AnalyticData/GrMhd/CMakeLists.txt
  tests/Unit/PointwiseFunctions/AnalyticData/GrMhd/CcsnCollapseID.dat
  tests/Unit/PointwiseFunctions/AnalyticData/GrMhd/Test_CcsnCollapse.cpp
Labels: new feature

#4333 Compute gauge constraint terms last in GH RHS
  src/Evolution/Systems/GeneralizedHarmonic/TimeDerivative.cpp
Labels: small

#4390 Add XSIMD and Blaze interoperability
  .github/workflows/Tests.yaml
  cmake/SetupXsimd.cmake
  docs/DevGuide/BuildSystem.md
Labels: small

#4404 Don't dump volume data from the interpolator upon failure
  src/ParallelAlgorithms/Interpolation/Interpolator.hpp
Labels: small, bugfix

#4403 Fix GenerateXdmf for #4378
  src/Visualization/Python/GenerateXdmf.py
Labels: small, bugfix

#4401 Ensure random_lapse is not too close to zero
  tests/Unit/Helpers/PointwiseFunctions/GeneralRelativity/TestHelpers.cpp
Labels: small, bugfix

#4411 Don't print warning about cleanup phase in DistObj
  src/Parallel/DistributedObject.hpp
Labels: small

#4418 Fix output errors on subcell
  src/Evolution/ComputeTags.hpp
  src/Evolution/Executables/Burgers/EvolveBurgers.hpp
  src/Evolution/Executables/GeneralizedHarmonic/GeneralizedHarmonicBase.hpp
  src/Evolution/Executables/GrMhd/GhValenciaDivClean/GhValenciaDivCleanBase.hpp
  src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivClean.hpp
  src/Evolution/Executables/NewtonianEuler/EvolveNewtonianEuler.hpp
  src/Evolution/Executables/RadiationTransport/M1Grey/EvolveM1Grey.hpp
  src/Evolution/Executables/RelativisticEuler/Valencia/EvolveValencia.hpp
  src/Evolution/Executables/ScalarAdvection/EvolveScalarAdvection.hpp
  src/Evolution/Executables/ScalarWave/EvolveScalarWave.hpp
  src/PointwiseFunctions/AnalyticSolutions/Tags.hpp
  tests/Unit/Evolution/Test_ComputeTags.cpp
  tests/Unit/PointwiseFunctions/AnalyticSolutions/Test_Tags.cpp
Labels: bugfix

#4423 Print walltime at phase change
  src/Parallel/Main.hpp
Labels: small

#4396 Use TimeAndPrevious tag for control sys IntrpTargetTags
  src/ControlSystem/ApparentHorizons/Measurements.hpp
Labels: small

#4434 Fix issue with `PY_DEV_MODE`, consistently pass `PYTHONPATH` to unit tests
  CMakeLists.txt
  cmake/AddInputFileTests.cmake
  cmake/FindNumPy.cmake
  cmake/FindPythonModule.cmake
  cmake/SpectreAddCatchTests.cmake
  cmake/SpectrePythonExecutable.sh
  cmake/SpectreSetupPythonPackage.cmake
Labels: bugfix
