Repository sxs-collaboration/spectre, pull requests merged in 2022-08, with the labels that each got.

#4143 Fix formatting in post-release workflow
  .github/workflows/PostRelease.yaml
Labels: small, bugfix

#4154 Fix bug in `test_copy_semantics` where constructor instead of assignment operator is called
  tests/Unit/Framework/TestHelpers.hpp
  tests/Unit/NumericalAlgorithms/SphericalHarmonics/Test_SpherepackIterator.cpp
  tests/Unit/NumericalAlgorithms/SphericalHarmonics/Test_YlmSpherepack.cpp
Labels: small, bugfix

#4161 Assume frustum not invertible below lower bound
  src/Domain/CoordinateMaps/Frustum.cpp
  tests/Unit/Domain/CoordinateMaps/Test_Frustum.cpp
Labels: small

#4170 Fix finding Python on macOS CI
  .github/workflows/Tests.yaml
  support/DevEnvironments/spack.yaml
Labels: bugfix

#4160 Add clang build analysis tools to build optimization docs
  docs/DevGuide/BuildOptimization.md
Labels: documentation

#4173 Fix a check in CubicScale.
  src/Domain/CoordinateMaps/TimeDependent/CubicScale.cpp
  tests/Unit/Domain/CoordinateMaps/TimeDependent/Test_CubicScale.cpp
Labels: small, bugfix

#4072 Set SpherepackIterator by compact index
  src/NumericalAlgorithms/SphericalHarmonics/SpherepackIterator.cpp
  src/NumericalAlgorithms/SphericalHarmonics/SpherepackIterator.hpp
  tests/Unit/NumericalAlgorithms/SphericalHarmonics/Test_SpherepackIterator.cpp
Labels: small

#4159 Conditionally resize LHS Tensors before RHS TensorExpression evaluation
  src/DataStructures/Tensor/Expressions/AddSubtract.hpp
  src/DataStructures/Tensor/Expressions/Contract.hpp
  src/DataStructures/Tensor/Expressions/Divide.hpp
  src/DataStructures/Tensor/Expressions/Evaluate.hpp
  src/DataStructures/Tensor/Expressions/Negate.hpp
  src/DataStructures/Tensor/Expressions/NumberAsExpression.hpp
  src/DataStructures/Tensor/Expressions/Product.hpp
  src/DataStructures/Tensor/Expressions/SquareRoot.hpp
  src/DataStructures/Tensor/Expressions/TensorAsExpression.hpp
  src/DataStructures/Tensor/Expressions/TensorExpression.hpp
  tests/Unit/DataStructures/Tensor/Expressions/Test_Divide.cpp
Labels: bugfix

#4165 AH finder computes inertial AH coords, not inertial Strahlkorper.
  src/ApparentHorizons/ObserveCenters.hpp
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGeneralizedHarmonicWithHorizon.hpp
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGhBinaryBlackHole.hpp
  src/ParallelAlgorithms/Interpolation/Callbacks/FindApparentHorizon.hpp
  src/ParallelAlgorithms/Interpolation/Callbacks/ObserveSurfaceData.hpp
  src/ParallelAlgorithms/Interpolation/Targets/ApparentHorizon.hpp
  tests/Unit/ApparentHorizons/Test_ApparentHorizonFinder.cpp
  tests/Unit/ApparentHorizons/Test_ObserveCenters.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_ObserveTimeSeriesAndSurfaceData.cpp
Labels: bugfix

#4190 Correct name of subcell option struct in docs
  src/Evolution/DgSubcell/NeighborReconstructedFaceSolution.hpp
Labels: documentation, small
