Repository sxs-collaboration/spectre, pull requests merged in 2022-06, with the labels that each got.

#3999 Ignore DataBox warning in gcc 11
  src/DataStructures/DataBox/DataBox.hpp
Labels: small

#4008 Fix missing templates for parallel infos
  src/Parallel/GlobalCache.hpp
  tests/Unit/Parallel/Test_AlgorithmGlobalCache.cpp
Labels: small, bugfix

#3980 Add ResourceInfo for allocating singletons
  src/Parallel/ResourceInfo.hpp
  src/Parallel/Tags/CMakeLists.txt
  src/Parallel/Tags/ResourceInfo.hpp
  src/Parallel/TypeTraits.hpp
  src/Utilities/StdHelpers.hpp
  src/Utilities/StlStreamDeclarations.hpp
  tests/Unit/Parallel/Test_ResourceInfo.cpp
  tests/Unit/Parallel/Test_TypeTraits.cpp
  tests/Unit/Utilities/Test_StdHelpers.cpp
Labels: new design

#4017 Fix ci by adding cache clear
  .github/workflows/ClobberCache.yaml
  .github/workflows/Tests.yaml
Labels: priority

#4026 Remove H5 file after AlgorithmGlobalCache is finished
  tests/Unit/Parallel/Test_AlgorithmGlobalCache.cpp
Labels: small, bugfix

#4010 Handle late calls to InterpolatorReceiveVolumeData
  src/ParallelAlgorithms/Interpolation/Actions/CleanUpInterpolator.hpp
  src/ParallelAlgorithms/Interpolation/Actions/InterpolatorReceiveVolumeData.hpp
  src/ParallelAlgorithms/Interpolation/InterpolatedVars.hpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_CleanUpInterpolator.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_InterpolatorReceiveVolumeData.cpp
Labels: bugfix

#4029 Add ASSERT for checking subcell volume extents and stencil width.
  src/NumericalAlgorithms/FiniteDifference/Reconstruct.tpp
Labels: small

#4031 Disable FPE trapping when calling into python
  tests/Unit/Framework/Pypp.hpp
Labels: bugfix

#4027 Remove colons from control system measurement names
  docs/Tutorials/Visualization.md
  src/ControlSystem/ApparentHorizons/Measurements.hpp
Labels: small, bugfix

#4033 Add a global enum class Phase
  src/Elliptic/Executables/Elasticity/SolveElasticity.hpp
  src/Elliptic/Executables/Poisson/SolvePoisson.hpp
  src/Elliptic/Executables/Xcts/SolveXcts.hpp
  src/Evolution/Executables/Burgers/EvolveBurgers.hpp
  src/Evolution/Executables/Cce/CharacteristicExtract.hpp
  src/Evolution/Executables/CurvedScalarWave/EvolveCurvedScalarWave.hpp
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGhBinaryBlackHole.hpp
  src/Evolution/Executables/GeneralizedHarmonic/GeneralizedHarmonicBase.hpp
  src/Evolution/Executables/GrMhd/GhValenciaDivClean/GhValenciaDivCleanBase.hpp
  src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivClean.hpp
  src/Evolution/Executables/NewtonianEuler/EvolveNewtonianEuler.hpp
  src/Evolution/Executables/RadiationTransport/M1Grey/EvolveM1Grey.hpp
  src/Evolution/Executables/RelativisticEuler/Valencia/EvolveValencia.hpp
  src/Evolution/Executables/ScalarAdvection/EvolveScalarAdvection.hpp
  src/Evolution/Executables/ScalarWave/EvolveScalarWave.hpp
  src/Executables/Examples/HelloWorld/SingletonHelloWorld.hpp
  src/Executables/Examples/ParallelTutorial/MinimalExecutable.hpp
  src/Executables/ExportCoordinates/ExportCoordinates.hpp
  src/Parallel/CMakeLists.txt
  src/Parallel/Phase.cpp
  src/Parallel/Phase.hpp
  tests/Unit/Parallel/CMakeLists.txt
  tests/Unit/Parallel/Test_Phase.cpp
Labels: new feature

#4052 Remove load balancing test
  tests/Unit/Parallel/CMakeLists.txt
Labels: priority, bugfix

#4040 Cleanup execs and libs after running tests
  .github/workflows/Tests.yaml
Labels: small, bugfix

#4044 Interpolation without Interpolator ParallelComponent for time-dependent maps.
  src/ParallelAlgorithms/Interpolation/Actions/ElementReceiveInterpPoints.hpp
  src/ParallelAlgorithms/Interpolation/Actions/InterpolationTargetSendPoints.hpp
  src/ParallelAlgorithms/Interpolation/Actions/InterpolationTargetVarsFromElement.hpp
  src/ParallelAlgorithms/Interpolation/Actions/VerifyTemporalIdsAndSendPoints.hpp
  src/ParallelAlgorithms/Interpolation/Events/InterpolateWithoutInterpComponent.hpp
  src/ParallelAlgorithms/Interpolation/InterpolationTarget.hpp
  src/ParallelAlgorithms/Interpolation/InterpolationTargetDetail.hpp
  src/ParallelAlgorithms/Interpolation/PointInfoTag.hpp
  tests/Unit/Evolution/Systems/Cce/Actions/Test_InterpolateDuringSelfStart.cpp
  tests/Unit/Helpers/ParallelAlgorithms/Interpolation/InterpolateOnElementTestHelpers.hpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_ElementReceiveInterpPoints.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_InterpolationTargetVarsFromElement.cpp
Labels: bugfix

#4063 Fix Charm v7.0.0 AlgorithmArray.def.h patch
  tools/CharmModulePatches/src/Parallel/Algorithms/AlgorithmArray_v7.0.0.def.h.patch
Labels: priority, bugfix

#4065 Increase timeout in RotScaleTrans test
  tests/Unit/ControlSystem/Systems/Test_RotScaleTrans.cpp
Labels: small

#4059 Remove buffer from Ccz4::upper_spatial_z4_constraint
  src/Evolution/Systems/Ccz4/TimeDerivative.cpp
  src/Evolution/Systems/Ccz4/TimeDerivative.hpp
  src/Evolution/Systems/Ccz4/Z4Constraint.cpp
  src/Evolution/Systems/Ccz4/Z4Constraint.hpp
  tests/Unit/Evolution/Systems/Ccz4/Test_TimeDerivative.cpp
  tests/Unit/Evolution/Systems/Ccz4/Z4Constraint.py
Labels: small

#4060 Fix Ccz4 temporary expression calculation
  src/Evolution/Systems/Ccz4/TimeDerivative.cpp
Labels: small

#4061 Forward declare Ccz4 temporary tags
  src/Evolution/Systems/Ccz4/TagsDeclarations.hpp
Labels: small

#3926 Update domain in BBH ID input file
  tests/InputFiles/Xcts/BinaryBlackHole.yaml
Labels: small

#4051 Add to ParallelComponent section of Parallelization DevGuide
  docs/DevGuide/Parallelization.md
  docs/Images/DevGuides/charm_node_structure.png
Labels: documentation

#3842 Enable TensorExpressions to internally split up equations
  src/DataStructures/Tensor/Expressions/AddSubtract.hpp
  src/DataStructures/Tensor/Expressions/Contract.hpp
  src/DataStructures/Tensor/Expressions/Divide.hpp
  src/DataStructures/Tensor/Expressions/Evaluate.hpp
  src/DataStructures/Tensor/Expressions/Negate.hpp
  src/DataStructures/Tensor/Expressions/NumberAsExpression.hpp
  src/DataStructures/Tensor/Expressions/Product.hpp
  src/DataStructures/Tensor/Expressions/SquareRoot.hpp
  src/DataStructures/Tensor/Expressions/TensorAsExpression.hpp
  src/DataStructures/Tensor/Expressions/TensorExpression.hpp
  src/DataStructures/Tensor/Expressions/TensorIndexTransformation.hpp
  src/Evolution/Systems/Ccz4/TimeDerivative.cpp
  tests/Unit/DataStructures/Tensor/Expressions/Test_AddSubtract.cpp
  tests/Unit/DataStructures/Tensor/Expressions/Test_Contract.cpp
  tests/Unit/DataStructures/Tensor/Expressions/Test_Divide.cpp
  tests/Unit/DataStructures/Tensor/Expressions/Test_MixedOperations.cpp
  tests/Unit/DataStructures/Tensor/Expressions/Test_Negate.cpp
  tests/Unit/DataStructures/Tensor/Expressions/Test_Product.cpp
  tests/Unit/DataStructures/Tensor/Expressions/Test_SquareRoot.cpp
Labels: new design

#4074 Shorten rotation control system test
  tests/Unit/ControlSystem/Systems/Test_Rotation.cpp
Labels: small
