Repository sxs-collaboration/spectre, pull requests merged in 2022-10, with the labels that each got.

#4266 Fix bug causing events to be improperly rerun
  src/Evolution/EventsAndDenseTriggers/EventsAndDenseTriggers.hpp
  tests/Unit/Evolution/EventsAndDenseTriggers/Test_EventsAndDenseTriggers.cpp
Labels: bugfix

#4260 Remove GCC7 workaround from GRMHD subcell
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TimeDerivative.hpp
Labels: small

#4258 Allow custom Metavariables in DG boundary condition tests
  tests/Unit/Helpers/Evolution/DiscontinuousGalerkin/BoundaryConditions.hpp
Labels: small

#4270 Fix sign error in ErrorControl
  src/Time/StepChoosers/ErrorControl.hpp
  tests/InputFiles/ScalarWave/PlaneWave2D.yaml
  tests/Unit/Time/StepChoosers/Test_ErrorControl.cpp
Labels: bugfix

#4264 Add more documentation to YlmSpherepack.
  src/NumericalAlgorithms/SphericalHarmonics/YlmSpherepack.hpp
Labels: documentation

#4275 Fix CMake option for enabling profiling
  cmake/SetupProfiling.cmake
Labels: small, bugfix

#4281 Add clangd cache to git ignore files
  .gitignore
Labels: small

#4269 Fix uninitialized timescale tuners from options
  src/ControlSystem/InitialExpirationTimes.hpp
  src/ControlSystem/Tags/FunctionsOfTimeInitialize.hpp
  src/ControlSystem/Tags/MeasurementTimescales.hpp
  tests/Unit/ControlSystem/Tags/Test_FunctionsOfTimeInitialize.cpp
  tests/Unit/ControlSystem/Tags/Test_MeasurementTimescales.cpp
  tests/Unit/ControlSystem/Test_InitialExpirationTimes.cpp
Labels: bugfix

#4297 Minor fixes to FD, remove anon namespace from header & square a term in PPAO
  src/NumericalAlgorithms/FiniteDifference/PositivityPreservingAdaptiveOrder.hpp
  src/NumericalAlgorithms/FiniteDifference/Wcns5z.hpp
  tests/Unit/NumericalAlgorithms/FiniteDifference/PositivityPreservingAdaptiveOrder.py
Labels: small, bugfix

#4304 Suppress g++12 warning about array bounds
  src/Utilities/StaticCache.hpp
Labels: small

#4306 Add Elias to contributors list
  Metadata.yaml
Labels: documentation, small

#4299 Remove CCE dependency from Interpolation
  src/Evolution/Systems/Cce/CMakeLists.txt
  src/Evolution/Systems/Cce/SendGhWorldtubeData.hpp
  src/ParallelAlgorithms/Interpolation/CMakeLists.txt
  src/ParallelAlgorithms/Interpolation/Callbacks/CMakeLists.txt
  tests/Unit/NumericalAlgorithms/Interpolation/Test_SendGhWorldtubeData.cpp
Labels: small

#4307 Ignore architecture flags on "aarch64"
  cmake/SetupCxxFlags.cmake
Labels: small

#4313 Update Beginner Tutorial docs
  docs/Tutorials/BeginnersTutorial.md
Labels: small

#4309 Add missing documentations on electron fraction
  docs/References.bib
  src/Evolution/Systems/GrMhd/GhValenciaDivClean/Subcell/PrimitiveGhostData.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/BoundaryConditions/FreeOutflow.cpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/ConservativeFromPrimitive.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/FiniteDifference/PositivityPreservingAdaptiveOrder.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Fluxes.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Sources.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/InitialDataTci.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/PrimitiveGhostData.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnDgGrid.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnFdGrid.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/System.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Tags.hpp
Labels: help wanted

#4316 Add deduction guidelines for ElementMap
  src/Domain/ElementMap.hpp
  tests/Unit/Domain/Test_ElementMap.cpp
Labels: small

#4323 Link Parallel in MinimalExample executable
  src/Executables/Examples/ParallelTutorial/CMakeLists.txt
Labels: small, bugfix

#4324 Remove unphysical GH+GRMHD solutions again
  tests/Unit/PointwiseFunctions/AnalyticSolutions/GhGrMhd/Test_InstantiateWrappedGr.cpp
Labels: small

#4330 Compute the number of ghost cells in the FD derivatives routine
  src/NumericalAlgorithms/FiniteDifference/PartialDerivatives.cpp
Labels: small

#4331 Print output on failure in Burgers formaline test
  .github/workflows/Tests.yaml
Labels: small
