Repository sxs-collaboration/spectre, pull requests merged in 2023-10, with the labels that each got.

#5522 Fix 1d recovery and 2d atmosphere fixing
  src/Evolution/Systems/GrMhd/ValenciaDivClean/KastaunEtAl.cpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/KastaunEtAlHydro.cpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/PrimitiveFromConservative.cpp
  src/Evolution/Systems/RelativisticEuler/Valencia/System.hpp
  src/Evolution/VariableFixing/FixToAtmosphere.cpp
  src/Evolution/VariableFixing/FixToAtmosphere.hpp
  src/PointwiseFunctions/AnalyticSolutions/GrMhd/SmoothFlow.cpp
  src/PointwiseFunctions/AnalyticSolutions/GrMhd/SmoothFlow.hpp
  src/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/SmoothFlow.cpp
  src/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/SmoothFlow.hpp
  src/PointwiseFunctions/Hydro/EquationsOfState/EquationOfState.hpp
  tests/InputFiles/RelativisticEuler/Valencia/SmoothFlow1D.yaml
  tests/InputFiles/RelativisticEuler/Valencia/SmoothFlow2D.yaml
  tests/InputFiles/RelativisticEuler/Valencia/SmoothFlow3D.yaml
  tests/Unit/Evolution/VariableFixing/Test_FixToAtmosphere.cpp
Labels: priority, bugfix

#5521 Fix sphere optimization
  src/ParallelAlgorithms/Interpolation/Actions/InterpolatorReceiveVolumeData.hpp
  src/ParallelAlgorithms/Interpolation/Events/InterpolateWithoutInterpComponent.hpp
  tests/Unit/Evolution/Systems/Cce/Actions/Test_SendGhVarsToCce.cpp
  tests/Unit/Helpers/ParallelAlgorithms/Interpolation/InterpolateOnElementTestHelpers.hpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_InterpolateWithoutInterpComponent.cpp
Labels: priority, bugfix

#5508 Fix compiling temperature init with analytic solutions
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGhAndCharacteristic.hpp
  src/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/SmoothFlow.hpp
  src/PointwiseFunctions/Hydro/Temperature.hpp
  tests/Unit/PointwiseFunctions/Hydro/Test_Temperature.cpp
Labels: bugfix

#5464 Add transport velocity tag to namespace Hydro and insert Temperature tag to RotatingStar
  src/Evolution/Executables/GrMhd/GhValenciaDivClean/GhValenciaDivCleanBase.hpp
  src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivClean.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Fluxes.cpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Fluxes.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/QuadrupoleFormula.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/TimeDerivativeTerms.cpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/TimeDerivativeTerms.hpp
  src/Evolution/Systems/RelativisticEuler/Valencia/Fluxes.cpp
  src/Evolution/Systems/RelativisticEuler/Valencia/TimeDerivativeTerms.cpp
  src/Evolution/Systems/RelativisticEuler/Valencia/TimeDerivativeTerms.hpp
  src/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/RotatingStar.cpp
  src/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/RotatingStar.hpp
  src/PointwiseFunctions/Hydro/CMakeLists.txt
  src/PointwiseFunctions/Hydro/Tags.hpp
  src/PointwiseFunctions/Hydro/TransportVelocity.cpp
  src/PointwiseFunctions/Hydro/TransportVelocity.hpp
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Test_QuadrupoleFormula.cpp
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Test_TimeDerivativeTerms.cpp
  tests/Unit/Evolution/Systems/RelativisticEuler/Valencia/Test_TimeDerivativeTerms.cpp
  tests/Unit/PointwiseFunctions/Hydro/CMakeLists.txt
  tests/Unit/PointwiseFunctions/Hydro/Test_Tags.cpp
  tests/Unit/PointwiseFunctions/Hydro/Test_TransportVelocity.cpp
  tests/Unit/PointwiseFunctions/Hydro/TransportVelocity.py
Labels: bugfix

#5515 Update some parallel documentation
  docs/DevGuide/Parallelization.md
  tests/Unit/Parallel/Test_DetectHangArray.cpp
Labels: documentation

#5524 Fix Bug in Grmhd BCGhostData
  src/Evolution/Systems/GrMhd/ValenciaDivClean/FiniteDifference/BoundaryConditionGhostData.hpp
Labels: priority, small, bugfix

#5530 Fix linking of ExternalIO on Wheeler
  src/IO/External/CMakeLists.txt
Labels: priority, bugfix, build system

#5539 Add missing header to GR surface tags
  src/PointwiseFunctions/GeneralRelativity/Surfaces/Tags.hpp
Labels: small

#5538 Fix missing lib dependence in ForceFreeAnalyticData
  src/PointwiseFunctions/AnalyticData/ForceFree/CMakeLists.txt
Labels: small

#5534 Temperature updates for param delep 3D EoS
  src/Evolution/VariableFixing/ParameterizedDeleptonization.cpp
  src/Evolution/VariableFixing/ParameterizedDeleptonization.hpp
  tests/Unit/Evolution/VariableFixing/Test_ParameterizedDeleptonization.cpp
Labels: bugfix, auto-merge

#5545 Fix missing include
  tests/Unit/Time/Actions/Test_SelfStartActions.cpp
Labels: priority, bugfix

#5553 Disable building executables on gcc 11 Release
  .github/workflows/Tests.yaml
Labels: priority, ci/cd

#5551 Fix status CLI if user directory can't be read
  tools/Status/Status.py
Labels: bugfix, cli/pybindings

#5547 Minor improvements to Schedule.py
  support/Python/Resubmit.py
  support/Python/Schedule.py
  tests/support/Python/Test_Schedule.py
  tools/Status/Status.py
Labels: cli/pybindings

#5528 Install CI compilers etc on demand to reduce disk space usage on CI
  .github/actions/parse-compiler/action.yaml
  .github/workflows/Tests.yaml
  containers/Dockerfile.buildenv
Labels: ci/cd

#5510 Check FoT before post intrp callbacks and UpdateMessageQueue
  src/ParallelAlgorithms/Actions/CMakeLists.txt
  src/ParallelAlgorithms/Actions/UpdateMessageQueue.hpp
  src/ParallelAlgorithms/Interpolation/Actions/InterpolationTargetReceiveVars.hpp
  src/ParallelAlgorithms/Interpolation/Actions/InterpolationTargetVarsFromElement.hpp
  tests/Unit/ParallelAlgorithms/Actions/CMakeLists.txt
  tests/Unit/ParallelAlgorithms/Actions/Test_UpdateMessageQueue.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_InterpolationTargetReceiveVars.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_InterpolationTargetVarsFromElement.cpp
Labels: bugfix

#5560 Fix script to add Spack version
  .github/workflows/PostRelease.yaml
Labels: bugfix, ci/cd

#5507 Add Render3D command with simple "clip" rendering
  .github/workflows/Tests.yaml
  docs/Installation/Installation.md
  src/Visualization/Python/CMakeLists.txt
  src/Visualization/Python/Render3D/CMakeLists.txt
  src/Visualization/Python/Render3D/Clip.py
  src/Visualization/Python/Render3D/__init__.py
  support/Environments/caltech_hpc_gcc.sh
  support/Environments/wheeler_gcc.sh
  support/Python/__main__.py
  tests/Unit/Visualization/Python/CMakeLists.txt
  tests/Unit/Visualization/Python/Render3D/CMakeLists.txt
  tests/Unit/Visualization/Python/Render3D/Test_Clip.py
Labels: cli/pybindings

#5564 Skip compiling executables in demo container when emulating
  .github/workflows/DemoContainer.yaml
  containers/Dockerfile.buildenv
  docs/Tutorials/BeginnersTutorial.md
Labels: ci/cd

#5571 Use smaller values in scalar wave char test
  tests/Unit/Evolution/Systems/ScalarWave/Test_Characteristics.cpp
Labels: small

#5577 Fix boundary condition bugs for temperature reconstruction
  src/Evolution/Systems/GrMhd/GhValenciaDivClean/BoundaryConditions/DirichletFreeOutflow.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/BoundaryConditions/HydroFreeOutflow.cpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/BoundaryConditions/HydroFreeOutflow.hpp
  tests/Unit/Evolution/Systems/GrMhd/GhValenciaDivClean/BoundaryConditions/Test_DirichletFreeOutflow.cpp
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/FiniteDifference/Test_BoundaryConditionGhostData.cpp
Labels: bugfix

#5601 Prevent operations with DV expressions in translation map
  src/Domain/CoordinateMaps/TimeDependent/Translation.cpp
Labels: bugfix
