Repository sxs-collaboration/spectre, pull requests merged in 2023-02, with the labels that each got.

#4675 Add functions to determine new Mesh after refinement
  src/ParallelAlgorithms/Amr/CMakeLists.txt
  src/ParallelAlgorithms/Amr/Projectors/CMakeLists.txt
  src/ParallelAlgorithms/Amr/Projectors/Mesh.cpp
  src/ParallelAlgorithms/Amr/Projectors/Mesh.hpp
  tests/Unit/ParallelAlgorithms/Amr/CMakeLists.txt
  tests/Unit/ParallelAlgorithms/Amr/Projectors/Test_Mesh.cpp
Labels: auto-merge

#4679 Add function to get refinement levels from an ElementId
  src/Domain/Amr/Helpers.cpp
  src/Domain/Structure/ElementId.hpp
  tests/Unit/Domain/Structure/Test_ElementId.cpp
Labels: auto-merge

#4684 Fix order of objects in Binary initial data
  src/PointwiseFunctions/AnalyticData/Xcts/Binary.hpp
  tests/InputFiles/Xcts/BinaryBlackHole.yaml
  tests/Unit/PointwiseFunctions/AnalyticData/Xcts/Test_Binary.cpp
Labels: bugfix

#4635 Add Punctures analytic data and executable
  docs/References.bib
  src/Elliptic/Executables/CMakeLists.txt
  src/Elliptic/Executables/Punctures/CMakeLists.txt
  src/Elliptic/Executables/Punctures/SolvePunctures.hpp
  src/Elliptic/Executables/Punctures/SolvePuncturesFwd.hpp
  src/Elliptic/Systems/Punctures/Punctures.hpp
  src/PointwiseFunctions/AnalyticData/CMakeLists.txt
  src/PointwiseFunctions/AnalyticData/Punctures/CMakeLists.txt
  src/PointwiseFunctions/AnalyticData/Punctures/MultiplePunctures.cpp
  src/PointwiseFunctions/AnalyticData/Punctures/MultiplePunctures.hpp
  src/PointwiseFunctions/AnalyticSolutions/CMakeLists.txt
  src/PointwiseFunctions/AnalyticSolutions/Punctures/CMakeLists.txt
  src/PointwiseFunctions/AnalyticSolutions/Punctures/Flatness.cpp
  src/PointwiseFunctions/AnalyticSolutions/Punctures/Flatness.hpp
  tests/InputFiles/Punctures/MultiplePunctures.yaml
  tests/Unit/PointwiseFunctions/AnalyticData/CMakeLists.txt
  tests/Unit/PointwiseFunctions/AnalyticData/Punctures/CMakeLists.txt
  tests/Unit/PointwiseFunctions/AnalyticData/Punctures/MultiplePunctures.py
  tests/Unit/PointwiseFunctions/AnalyticData/Punctures/Test_MultiplePunctures.cpp
  tests/Unit/PointwiseFunctions/AnalyticSolutions/CMakeLists.txt
  tests/Unit/PointwiseFunctions/AnalyticSolutions/Punctures/CMakeLists.txt
  tests/Unit/PointwiseFunctions/AnalyticSolutions/Punctures/Test_Flatness.cpp
  tools/CheckOutputFiles.py
Labels: new feature

#4691 Add an AMR refinement criterion useful for testing
  src/Domain/Amr/Flag.cpp
  src/Domain/Amr/Flag.hpp
  src/ParallelAlgorithms/Amr/Criteria/CMakeLists.txt
  src/ParallelAlgorithms/Amr/Criteria/Criterion.hpp
  src/ParallelAlgorithms/Amr/Criteria/DriveToTarget.cpp
  src/ParallelAlgorithms/Amr/Criteria/DriveToTarget.hpp
  tests/Unit/Domain/Amr/Test_Flag.cpp
  tests/Unit/ParallelAlgorithms/Amr/CMakeLists.txt
  tests/Unit/ParallelAlgorithms/Amr/Criteria/Test_DriveToTarget.cpp
Labels: auto-merge

#4682 Fix PiecewisePolytropicFluid Python test, add some bindings
  src/PointwiseFunctions/Hydro/EquationsOfState/Python/Bindings.cpp
  src/PointwiseFunctions/Hydro/EquationsOfState/Python/CMakeLists.txt
  src/PointwiseFunctions/Hydro/EquationsOfState/Python/EquationOfState.cpp
  src/PointwiseFunctions/Hydro/EquationsOfState/Python/PiecewisePolytropicFluid.cpp
  src/PointwiseFunctions/Hydro/EquationsOfState/Python/PolytropicFluid.cpp
  tests/Unit/PointwiseFunctions/Hydro/EquationsOfState/Python/CMakeLists.txt
  tests/Unit/PointwiseFunctions/Hydro/EquationsOfState/Python/Test_PolytropicFluid.py
Labels: bugfix

#4663 Add script to plot power monitors
  src/Domain/Creators/Brick.cpp
  src/Domain/Creators/Brick.hpp
  src/Domain/Python/Domain.cpp
  src/Visualization/Python/CMakeLists.txt
  src/Visualization/Python/InterpolateToCoords.py
  src/Visualization/Python/PlotPowerMonitors.py
  src/Visualization/Python/plots.mplstyle
  support/Python/__main__.py
  tests/Unit/Domain/Creators/Python/Test_Brick.py
  tests/Unit/Domain/Creators/Test_Brick.cpp
  tests/Unit/Domain/Python/Test_Domain.py
  tests/Unit/Visualization/Python/CMakeLists.txt
  tests/Unit/Visualization/Python/Test_PlotPowerMonitors.py
  tests/Unit/Visualization/Python/VolTestData0.h5
  tools/FileTestDefs.sh
Labels: new feature

#4658 Add StaticDeque
  src/DataStructures/CMakeLists.txt
  src/DataStructures/StaticDeque.hpp
  src/Utilities/CMakeLists.txt
  src/Utilities/StlBoilerplate.hpp
  tests/Unit/DataStructures/CMakeLists.txt
  tests/Unit/DataStructures/Test_StaticDeque.cpp
  tests/Unit/Utilities/CMakeLists.txt
  tests/Unit/Utilities/Test_StlBoilerplate.cpp
Labels: auto-merge

#4700 Fix cartesian_product dox
  src/Utilities/CartesianProduct.hpp
  tests/Unit/Domain/CoordinateMaps/Test_Wedge3D.cpp
  tests/Unit/Domain/Creators/Test_Cylinder.cpp
  tests/Unit/Domain/Creators/Test_CylindricalBinaryCompactObject.cpp
  tests/Unit/Domain/Creators/Test_FrustalCloak.cpp
Labels: bugfix, auto-merge

#4702 Fix missing include in AMR code
  src/ParallelAlgorithms/Amr/Projectors/Mesh.cpp
Labels: auto-merge

#4422 Tabulated equation of state
  src/NumericalAlgorithms/Interpolation/MultiLinearSpanInterpolation.hpp
  src/PointwiseFunctions/Hydro/EquationsOfState/CMakeLists.txt
  src/PointwiseFunctions/Hydro/EquationsOfState/EquationOfState.hpp
  src/PointwiseFunctions/Hydro/EquationsOfState/Tabulated3d.cpp
  src/PointwiseFunctions/Hydro/EquationsOfState/Tabulated3d.hpp
  tests/Unit/PointwiseFunctions/Hydro/EquationsOfState/CMakeLists.txt
  tests/Unit/PointwiseFunctions/Hydro/EquationsOfState/Test_Tabulated3D.cpp
Labels: new feature

#4680 Implicitly convert Numpy arrays to Tensors
  src/DataStructures/Python/DataVector.cpp
  src/DataStructures/Tensor/Python/Tensor.cpp
  tests/Unit/DataStructures/Tensor/Python/Test_Tensor.py
  tests/Unit/DataStructures/Test_DataVector.py
  tests/Unit/Domain/Python/Test_JacobianDiagnostic.py
  tests/Unit/PointwiseFunctions/Punctures/Python/Test_Bindings.py
  tests/Unit/Visualization/Python/Test_ApplyPointwise.py
Labels: auto-merge

#4707 Improve documentation for amr::Criterion
  src/ParallelAlgorithms/Amr/Actions/EvaluateRefinementCriteria.hpp
  src/ParallelAlgorithms/Amr/Actions/UpdateAmrDecision.hpp
  src/ParallelAlgorithms/Amr/Criteria/Criterion.hpp
  src/ParallelAlgorithms/Amr/Criteria/Random.hpp
  tests/Unit/ParallelAlgorithms/Amr/CMakeLists.txt
  tests/Unit/ParallelAlgorithms/Amr/Criteria/Test_Criterion.cpp
Labels: documentation

#4467 Add bounds on electron fraction and beta equilibrium Ye
  src/PointwiseFunctions/Hydro/EquationsOfState/EquationOfState.hpp
  src/PointwiseFunctions/Hydro/EquationsOfState/Tabulated3d.cpp
  src/PointwiseFunctions/Hydro/EquationsOfState/Tabulated3d.hpp
Labels: auto-merge

#4714 Add missing include to Test_JacobianDiagnostic.cpp
  tests/Unit/Domain/Test_JacobianDiagnostic.cpp
Labels: bugfix

#1224 Add SlabJet analytic data
  src/Evolution/Executables/GrMhd/ValenciaDivClean/CMakeLists.txt
  src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivClean.hpp
  src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivCleanFwd.hpp
  src/PointwiseFunctions/AnalyticData/GrMhd/CMakeLists.txt
  src/PointwiseFunctions/AnalyticData/GrMhd/SlabJet.cpp
  src/PointwiseFunctions/AnalyticData/GrMhd/SlabJet.hpp
  tests/Unit/PointwiseFunctions/AnalyticData/GrMhd/CMakeLists.txt
  tests/Unit/PointwiseFunctions/AnalyticData/GrMhd/SlabJet.py
  tests/Unit/PointwiseFunctions/AnalyticData/GrMhd/Test_SlabJet.cpp
Labels: auto-merge

#4715 Factor comoving magnetic field into free function, add hydro StressEnergy functions
  src/Evolution/Systems/GrMhd/GhValenciaDivClean/CMakeLists.txt
  src/Evolution/Systems/GrMhd/GhValenciaDivClean/StressEnergy.cpp
  src/PointwiseFunctions/Hydro/CMakeLists.txt
  src/PointwiseFunctions/Hydro/ComovingMagneticField.cpp
  src/PointwiseFunctions/Hydro/ComovingMagneticField.hpp
  src/PointwiseFunctions/Hydro/StressEnergy.cpp
  src/PointwiseFunctions/Hydro/StressEnergy.hpp
  tests/Unit/PointwiseFunctions/Hydro/CMakeLists.txt
  tests/Unit/PointwiseFunctions/Hydro/TestFunctions.py
  tests/Unit/PointwiseFunctions/Hydro/Test_ComovingMagneticField.cpp
  tests/Unit/PointwiseFunctions/Hydro/Test_StressEnergy.cpp
Labels: auto-merge

#4721 Fix bug in GHMHD time derivative
  src/Evolution/Systems/GrMhd/GhValenciaDivClean/Subcell/TimeDerivative.hpp
Labels: bugfix, auto-merge

#4727 Fix component naming in shape control system
  src/ControlSystem/Systems/Shape.hpp
  tests/Unit/ControlSystem/Systems/Test_Shape.cpp
Labels: small, bugfix

#4722 Add `euclidan_surface_element`
  src/Domain/CMakeLists.txt
  src/Domain/SurfaceJacobian.cpp
  src/Domain/SurfaceJacobian.hpp
  tests/Unit/Domain/CMakeLists.txt
  tests/Unit/Domain/Test_SurfaceJacobian.cpp
Labels: auto-merge

#4674 Add new receive_data entry method to DistributedObject
  .github/workflows/Tests.yaml
  cmake/FindCharm.cmake
  docs/DevGuide/Parallelization.md
  src/Evolution/DiscontinuousGalerkin/InboxTags.hpp
  src/Evolution/DiscontinuousGalerkin/Messages/BoundaryMessage.hpp
  src/Parallel/Algorithms/AlgorithmArray.ci
  src/Parallel/CharmRegistration.hpp
  src/Parallel/DistributedObject.hpp
  src/Parallel/Invoke.hpp
  tests/Unit/Parallel/CMakeLists.txt
  tests/Unit/Parallel/Test_AlgorithmCore.cpp
  tests/Unit/Parallel/Test_AlgorithmMessages.cpp
  tools/CharmModulePatches/src/Parallel/Algorithms/AlgorithmArray_v7.0.0.def.h.patch
Labels: new feature

#4740 Revert "Find NumPy with CMake's built-in FindPython"
  cmake/SetupPypp.cmake
Labels: priority, bugfix

#4746 Move ObjectLabel from Domain to DomainStructure
  src/ControlSystem/Actions/Initialization.hpp
  src/ControlSystem/CMakeLists.txt
  src/ControlSystem/ControlErrors/Expansion.hpp
  src/ControlSystem/ControlErrors/Rotation.hpp
  src/ControlSystem/ControlErrors/Shape.hpp
  src/ControlSystem/ControlErrors/Translation.hpp
  src/ControlSystem/Measurements/BothHorizons.hpp
  src/ControlSystem/Measurements/SingleHorizon.hpp
  src/ControlSystem/Systems/Expansion.hpp
  src/ControlSystem/Systems/Rotation.hpp
  src/ControlSystem/Systems/Shape.hpp
  src/ControlSystem/Systems/Translation.hpp
  src/Domain/CMakeLists.txt
  src/Domain/Structure/CMakeLists.txt
  src/Domain/Structure/ObjectLabel.cpp
  src/Domain/Structure/ObjectLabel.hpp
  src/Domain/Tags/ObjectCenter.cpp
  src/Domain/Tags/ObjectCenter.hpp
  src/Executables/FindHorizons/FindHorizons.hpp
  tests/Unit/ControlSystem/ControlErrors/Test_Rotation.cpp
  tests/Unit/ControlSystem/ControlErrors/Test_Shape.cpp
  tests/Unit/ControlSystem/Systems/Test_Shape.cpp
  tests/Unit/ControlSystem/Test_Measurements.cpp
  tests/Unit/Domain/CMakeLists.txt
  tests/Unit/Domain/Structure/CMakeLists.txt
  tests/Unit/Domain/Structure/Test_ObjectLabel.cpp
  tests/Unit/Domain/Test_Tags.cpp
  tests/Unit/Helpers/ControlSystem/Examples.hpp
  tests/Unit/Helpers/ControlSystem/SystemHelpers.hpp
  tests/Unit/Helpers/ControlSystem/TestStructs.hpp
Labels: auto-merge

#4747 Unify naming pattern of excision spheres
  src/ControlSystem/ControlErrors/Shape.hpp
  src/ControlSystem/Tags.hpp
  src/Domain/Creators/BinaryCompactObject.cpp
  src/Domain/Creators/CylindricalBinaryCompactObject.cpp
  src/Domain/Creators/Shell.cpp
  src/Domain/Tags/ObjectCenter.cpp
  tests/Unit/ControlSystem/ControlErrors/Test_Expansion.cpp
  tests/Unit/ControlSystem/ControlErrors/Test_Rotation.cpp
  tests/Unit/ControlSystem/ControlErrors/Test_Shape.cpp
  tests/Unit/ControlSystem/ControlErrors/Test_Translation.cpp
  tests/Unit/ControlSystem/Systems/Test_Expansion.cpp
  tests/Unit/ControlSystem/Systems/Test_Rotation.cpp
  tests/Unit/ControlSystem/Systems/Test_Shape.cpp
  tests/Unit/ControlSystem/Systems/Test_Translation.cpp
  tests/Unit/ControlSystem/Test_Tags.cpp
  tests/Unit/Domain/Creators/Test_BinaryCompactObject.cpp
  tests/Unit/Domain/Creators/Test_CylindricalBinaryCompactObject.cpp
  tests/Unit/Domain/Creators/Test_Shell.cpp
  tests/Unit/Domain/Structure/Test_ExcisionSphere.cpp
  tests/Unit/Domain/Test_SurfaceJacobian.cpp
  tests/Unit/Evolution/Systems/CurvedScalarWave/Worldtube/Test_Tags.cpp
  tests/Unit/Helpers/ControlSystem/SystemHelpers.hpp
Labels: auto-merge

#4733 Add derivation of ConstraintPreserving BCs of CSW to docs and fix typo
  src/Evolution/Systems/CurvedScalarWave/BoundaryConditions/ConstraintPreservingSphericalRadiation.cpp
  src/Evolution/Systems/CurvedScalarWave/BoundaryConditions/ConstraintPreservingSphericalRadiation.hpp
  src/Evolution/Systems/ScalarWave/BoundaryConditions/ConstraintPreservingSphericalRadiation.cpp
  src/Evolution/Systems/ScalarWave/BoundaryConditions/ConstraintPreservingSphericalRadiation.hpp
  tests/Unit/Evolution/Systems/CurvedScalarWave/BoundaryConditions/ConstraintPreservingSphericalRadiation.py
  tests/Unit/Evolution/Systems/ScalarWave/BoundaryConditions/ConstraintPreservingSphericalRadiation.py
Labels: documentation

#4718 Add radial partitions, radial grid point distributions, block names + groups to Sphere domain
  src/Domain/Creators/Python/Sphere.cpp
  src/Domain/Creators/Sphere.cpp
  src/Domain/Creators/Sphere.hpp
  src/Domain/DomainHelpers.cpp
  src/Domain/DomainHelpers.hpp
  tests/InputFiles/Punctures/MultiplePunctures.yaml
  tests/InputFiles/Xcts/TovStar.yaml
  tests/Unit/Domain/Creators/Python/Test_Sphere.py
  tests/Unit/Domain/Creators/Test_Sphere.cpp
  tests/Unit/Domain/Test_DomainHelpers.cpp
  tests/Unit/Helpers/Domain/Creators/TestHelpers.hpp
Labels: new feature, auto-merge

#4750 Further reduce number of allocations in InternalMortarDataImpl
  docs/DevGuide/ImplementingVectors.md
  src/DataStructures/VectorImpl.hpp
  src/Evolution/DiscontinuousGalerkin/Actions/ComputeTimeDerivative.hpp
  src/Evolution/DiscontinuousGalerkin/Actions/InternalMortarDataImpl.hpp
  src/Evolution/DiscontinuousGalerkin/MortarData.hpp
  src/NumericalAlgorithms/DiscontinuousGalerkin/MortarHelpers.hpp
  tests/Unit/DataStructures/Test_ComplexDataVectorAsserts.cpp
  tests/Unit/DataStructures/Test_ComplexDiagonalModalOperator.cpp
  tests/Unit/DataStructures/Test_ComplexModalVector.cpp
  tests/Unit/DataStructures/Test_DataVectorAsserts.cpp
  tests/Unit/DataStructures/Test_DiagonalModalOperator.cpp
  tests/Unit/DataStructures/Test_ModalVector.cpp
  tests/Unit/DataStructures/Test_NonZeroStaticSizeVector.cpp
  tests/Unit/DataStructures/Test_Variables.cpp
  tests/Unit/Evolution/DiscontinuousGalerkin/Test_MortarData.cpp
  tests/Unit/Helpers/DataStructures/VectorImplTestHelper.hpp
Labels: auto-merge

#4738 Cell centered flux tags
  src/Evolution/DgSubcell/Actions/Initialize.hpp
  src/Evolution/DgSubcell/Actions/TciAndSwitchToDg.hpp
  src/Evolution/DgSubcell/SubcellOptions.cpp
  src/Evolution/DgSubcell/SubcellOptions.hpp
  src/Evolution/DgSubcell/Tags/CMakeLists.txt
  src/Evolution/DgSubcell/Tags/CellCenteredFlux.hpp
  tests/InputFiles/Burgers/Step.yaml
  tests/InputFiles/GrMhd/GhValenciaDivClean/GhMhdTovStar.yaml
  tests/InputFiles/GrMhd/ValenciaDivClean/BlastWave.yaml
  tests/InputFiles/GrMhd/ValenciaDivClean/FishboneMoncriefDisk.yaml
  tests/InputFiles/NewtonianEuler/RiemannProblem1D.yaml
  tests/InputFiles/NewtonianEuler/RiemannProblem2D.yaml
  tests/InputFiles/NewtonianEuler/RiemannProblem3D.yaml
  tests/InputFiles/ScalarAdvection/Krivodonova1D.yaml
  tests/InputFiles/ScalarAdvection/Kuzmin2D.yaml
  tests/InputFiles/ScalarAdvection/Sinusoid1D.yaml
  tests/Unit/Evolution/DgSubcell/Actions/Test_Initialize.cpp
  tests/Unit/Evolution/DgSubcell/Actions/Test_TciAndRollback.cpp
  tests/Unit/Evolution/DgSubcell/Actions/Test_TciAndSwitchToDg.cpp
  tests/Unit/Evolution/DgSubcell/Test_SubcellOptions.cpp
  tests/Unit/Evolution/DgSubcell/Test_Tags.cpp
  tests/Unit/Evolution/Systems/Burgers/Subcell/Test_TciOnDgGrid.cpp
  tests/Unit/Evolution/Systems/Burgers/Subcell/Test_TciOnFdGrid.cpp
  tests/Unit/Evolution/Systems/GrMhd/GhValenciaDivClean/Subcell/Test_NeighborPackagedData.cpp
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_NeighborPackagedData.cpp
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_TciOnDgGrid.cpp
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_TciOnFdGrid.cpp
  tests/Unit/Evolution/Systems/NewtonianEuler/Subcell/Test_NeighborPackagedData.cpp
  tests/Unit/Evolution/Systems/NewtonianEuler/Subcell/Test_TciOnDgGrid.cpp
  tests/Unit/Evolution/Systems/NewtonianEuler/Subcell/Test_TciOnFdGrid.cpp
  tests/Unit/Evolution/Systems/ScalarAdvection/Subcell/Test_NeighborPackagedData.cpp
  tests/Unit/Evolution/Systems/ScalarAdvection/Subcell/Test_TciOnDgGrid.cpp
  tests/Unit/Evolution/Systems/ScalarAdvection/Subcell/Test_TciOnFdGrid.cpp
Labels: auto-merge

#4688 Add high order flux correction for Cartesian meshes
  src/NumericalAlgorithms/FiniteDifference/CMakeLists.txt
  src/NumericalAlgorithms/FiniteDifference/HighOrderFluxCorrection.hpp
  tests/Unit/NumericalAlgorithms/FiniteDifference/CMakeLists.txt
  tests/Unit/NumericalAlgorithms/FiniteDifference/Test_HighOrderFluxCorrection.cpp
Labels: auto-merge

#4779 Use iterable approx in control error tests
  tests/Unit/ControlSystem/ControlErrors/Test_Expansion.cpp
  tests/Unit/ControlSystem/ControlErrors/Test_Rotation.cpp
  tests/Unit/ControlSystem/ControlErrors/Test_Shape.cpp
Labels: small

#4790 Fix typo in Kerr Schild comment
  tests/Unit/PointwiseFunctions/AnalyticSolutions/GeneralRelativity/Test_KerrSchild.cpp
Labels: small
