Repository sxs-collaboration/spectre, pull requests merged in 2023-06, with the labels that each got.

#5051 Use correct mesh and jacobian for integrals with subcell
  src/Elliptic/Executables/Elasticity/SolveElasticity.hpp
  src/Elliptic/Executables/Punctures/SolvePunctures.hpp
  src/Evolution/Executables/ScalarWave/EvolveScalarWave.hpp
  src/ParallelAlgorithms/Events/ObserveVolumeIntegrals.hpp
  tests/Unit/ParallelAlgorithms/Events/Test_ObserveVolumeIntegrals.cpp
Labels: priority, bugfix

#5062 Have zero crossing predictor actually return min positive time
  src/NumericalAlgorithms/Interpolation/ZeroCrossingPredictor.cpp
  tests/Unit/NumericalAlgorithms/Interpolation/Test_ZeroCrossingPredictor.cpp
Labels: priority, small, bugfix

#5061 Shorten GH exec file names
  src/Evolution/Executables/GeneralizedHarmonic/CMakeLists.txt
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGhCce.hpp
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGhCceFwd.hpp
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGhNoBlackHole.hpp
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGhNoBlackHoleFwd.hpp
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGhSingleBlackHole.hpp
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGhSingleBlackHoleFwd.hpp
Labels: small

#5060 Add SpEC ID to BBH and GHMHD executables
  src/Evolution/Executables/GeneralizedHarmonic/CMakeLists.txt
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGhBinaryBlackHole.hpp
  src/Evolution/Executables/GrMhd/GhValenciaDivClean/CMakeLists.txt
  src/Evolution/Executables/GrMhd/GhValenciaDivClean/GhValenciaDivCleanBase.hpp
  src/Evolution/Initialization/InitialData.hpp
  src/Evolution/Systems/GrMhd/GhValenciaDivClean/Actions/CMakeLists.txt
  src/Evolution/Systems/GrMhd/GhValenciaDivClean/Actions/SetInitialData.cpp
  src/Evolution/Systems/GrMhd/GhValenciaDivClean/Actions/SetInitialData.hpp
  src/PointwiseFunctions/AnalyticData/GrMhd/SpecInitialData.hpp
  tests/Unit/Evolution/Systems/GrMhd/GhValenciaDivClean/Actions/Test_SetInitialData.cpp
  tests/Unit/Evolution/Systems/GrMhd/GhValenciaDivClean/CMakeLists.txt
Labels: priority

#5067 Fix some TOCs in docs
  docs/DevGuide/AutomaticVersioning.md
  docs/DevGuide/CompilerLinkerErrors.md
  docs/DevGuide/DevGuide.md
  docs/DevGuide/LoadBalancingNotes.md
  docs/Installation/InstallationOnAppleSilicon.md
  docs/Tutorials/EventsAndTriggers.md
Labels: documentation, small, bugfix

#5027 Add size control diagnostics
  src/ControlSystem/ControlErrors/Size/AhSpeed.cpp
  src/ControlSystem/ControlErrors/Size/AhSpeed.hpp
  src/ControlSystem/ControlErrors/Size/CMakeLists.txt
  src/ControlSystem/ControlErrors/Size/DeltaR.cpp
  src/ControlSystem/ControlErrors/Size/DeltaR.hpp
  src/ControlSystem/ControlErrors/Size/Error.cpp
  src/ControlSystem/ControlErrors/Size/Error.hpp
  src/ControlSystem/ControlErrors/Size/Initial.cpp
  src/ControlSystem/ControlErrors/Size/Initial.hpp
  src/ControlSystem/ControlErrors/Size/State.hpp
  tests/Unit/ControlSystem/ControlErrors/CMakeLists.txt
  tests/Unit/ControlSystem/ControlErrors/Test_SizeControlStates.cpp
  tests/Unit/ControlSystem/ControlErrors/Test_SizeError.cpp
Labels: priority

#5075 Allow control sys dense output during first time step
  src/ControlSystem/ExpirationTimes.hpp
  src/ControlSystem/Tags/FunctionsOfTimeInitialize.hpp
  src/ControlSystem/Tags/MeasurementTimescales.hpp
  tests/Unit/ControlSystem/Tags/Test_FunctionsOfTimeInitialize.cpp
  tests/Unit/ControlSystem/Tags/Test_MeasurementTimescales.cpp
  tests/Unit/ControlSystem/Test_ExpirationTimes.cpp
Labels: priority

#5071 Add more size error diagnostics
  src/ControlSystem/ControlErrors/Size/Error.cpp
  src/ControlSystem/ControlErrors/Size/Error.hpp
Labels: priority, small

#5072 Add reset function to size Info
  src/ControlSystem/ControlErrors/Size/Error.cpp
  src/ControlSystem/ControlErrors/Size/Info.cpp
  src/ControlSystem/ControlErrors/Size/Info.hpp
  tests/Unit/ControlSystem/ControlErrors/Test_SizeControlStates.cpp
Labels: priority, small

#5080 Fix input file tests
  cmake/AddInputFileTests.cmake
  cmake/ExecuteCheckOutputFilesAndClean.sh
  cmake/RunInputFileTest.sh
  docs/DevGuide/WritingTests.md
  src/Parallel/PhaseControl/CheckpointAndExitAfterWallclock.hpp
  tests/InputFiles/Cce/AnalyticTestRobinsonTrautman.yaml
  tests/InputFiles/ExampleExecutables/RandomAmr1D.yaml
  tools/CleanOutput.py
Labels: bugfix

#5091 Add missing includes for Utilities/TMPL.hpp
  src/Evolution/BoundaryCorrectionTags.hpp
  src/Evolution/DgSubcell/Tags/ActiveGrid.hpp
Labels: bugfix

#5084 Add size control error
  src/ControlSystem/CMakeLists.txt
  src/ControlSystem/ControlErrors/CMakeLists.txt
  src/ControlSystem/ControlErrors/Expansion.hpp
  src/ControlSystem/ControlErrors/Rotation.hpp
  src/ControlSystem/ControlErrors/Shape.hpp
  src/ControlSystem/ControlErrors/Size.cpp
  src/ControlSystem/ControlErrors/Size.hpp
  src/ControlSystem/ControlErrors/Translation.hpp
  src/ControlSystem/Protocols/ControlError.hpp
  src/ControlSystem/UpdateControlSystem.hpp
  tests/Unit/ControlSystem/ControlErrors/Test_Expansion.cpp
  tests/Unit/ControlSystem/ControlErrors/Test_Rotation.cpp
  tests/Unit/ControlSystem/ControlErrors/Test_Shape.cpp
  tests/Unit/ControlSystem/ControlErrors/Test_SizeError.cpp
  tests/Unit/ControlSystem/ControlErrors/Test_Translation.cpp
  tests/Unit/Helpers/ControlSystem/Examples.hpp
  tests/Unit/Helpers/ControlSystem/TestStructs.hpp
Labels: priority

#5111 Print message upon success of validate CLI
  tools/ValidateInputFile.py
Labels: small

#5113 Fix compiling Transpose.cpp on M2 Mac
  src/DataStructures/Transpose.cpp
Labels: bugfix

#5107 Add some guidelines for writing CLI endpoints
  docs/DevGuide/PythonBindings.md
Labels: documentation

#5124 Status CLI: recover from YAML parse error
  tools/Status/Status.py
Labels: bugfix

#5117 Fix a typo in Poisson system docs
  src/Elliptic/Systems/Poisson/FirstOrderSystem.hpp
Labels: documentation, small, bugfix

#5119 Add size control system
  src/ControlSystem/CMakeLists.txt
  src/ControlSystem/ControlErrors/Size.hpp
  src/ControlSystem/ControlErrors/Size/State.hpp
  src/ControlSystem/IsSize.hpp
  src/ControlSystem/Measurements/CharSpeed.hpp
  src/ControlSystem/Protocols/ControlSystem.hpp
  src/ControlSystem/Systems/CMakeLists.txt
  src/ControlSystem/Systems/Size.hpp
  src/ControlSystem/Tags/QueueTags.hpp
  src/DataStructures/LinkedMessageQueue.hpp
  tests/Unit/ControlSystem/CMakeLists.txt
  tests/Unit/ControlSystem/ControlErrors/Test_SizeError.cpp
  tests/Unit/ControlSystem/Systems/CMakeLists.txt
  tests/Unit/ControlSystem/Systems/Test_Size.cpp
  tests/Unit/ControlSystem/Test_IsSize.cpp
Labels: priority

#5129 Minor fixes
  src/PointwiseFunctions/AnalyticData/GeneralRelativity/InterpolateFromSpec.hpp
  src/Visualization/Python/ReadInputFile.py
Labels: bugfix
