Repository sxs-collaboration/spectre, pull requests merged in 2023-07, with the labels that each got.

#5140 Increase some IO test timeouts
  tests/Unit/IO/H5/Test_Dat.cpp
  tests/Unit/IO/H5/Test_H5File.cpp
  tests/Unit/IO/H5/Test_VolumeData.cpp
  tests/Unit/IO/Observers/Test_ReductionObserver.cpp
Labels: small

#5147 Add Correct Gaussian3 Amplitude in BBH input files
  tests/InputFiles/GeneralizedHarmonic/BinaryBlackHole.yaml
  tests/InputFiles/GeneralizedHarmonic/CylindricalBinaryBlackHole.yaml
Labels: bugfix

#5159 Fix bug in XMF vector
  src/Visualization/Python/GenerateXdmf.py
  tests/Unit/Visualization/Python/VolTestData.xmf
  tests/Unit/Visualization/Python/VolTestData0.h5
Labels: bugfix

#5152 Fix small ghgrmhd things for control systems
  src/ControlSystem/Measurements/BNSCenterOfMass.cpp
  src/ControlSystem/Measurements/BNSCenterOfMass.hpp
  src/Evolution/Executables/GrMhd/GhValenciaDivClean/GhValenciaDivCleanBase.hpp
  tests/Unit/ControlSystem/Test_Measurements.cpp
Labels: small

#5160 Minor changes working towards threaded DG elements
  src/Parallel/AlgorithmMetafunctions.hpp
  src/Parallel/DistributedObject.hpp
  src/Parallel/ParallelComponentHelpers.hpp
  src/Parallel/Reduction.hpp
Labels: priority, small

#5167 Find streamable decls before static assert in stream_obj_to_stream
  src/Parallel/Printf.hpp
Labels: small

#5170 Pin black version
  pyproject.toml
  support/Python/dev_requirements.txt
Labels: priority, bugfix

#5142 Fix bug in computation of zero crossing predictor
  src/ControlSystem/ControlErrors/Size.hpp
  src/ControlSystem/ControlErrors/Size/AhSpeed.cpp
  src/ControlSystem/ControlErrors/Size/DeltaR.cpp
  src/ControlSystem/ControlErrors/Size/Error.cpp
  src/ControlSystem/ControlErrors/Size/Info.cpp
  src/ControlSystem/ControlErrors/Size/Info.hpp
  src/ControlSystem/ControlErrors/Size/Initial.cpp
  src/NumericalAlgorithms/Interpolation/ZeroCrossingPredictor.cpp
  src/NumericalAlgorithms/Interpolation/ZeroCrossingPredictor.hpp
  tests/Unit/ControlSystem/ControlErrors/Test_SizeControlStates.cpp
  tests/Unit/NumericalAlgorithms/Interpolation/Test_ZeroCrossingPredictor.cpp
Labels: bugfix

#5134 Add dox for running on an interactive wheeler node
  docs/Installation/InstallationOnClusters.md
Labels: documentation

#5185 Add Shell0 block group to Sphere for single shell
  src/Domain/Creators/Sphere.cpp
Labels: small

#5164 Reference elliptic papers
  docs/References.bib
  src/Elliptic/DiscontinuousGalerkin/DgOperator.hpp
  src/Elliptic/Executables/NonlinearEllipticSolver.hpp
  src/Elliptic/Protocols/FirstOrderSystem.hpp
  src/Elliptic/Systems/Elasticity/BoundaryConditions/LaserBeam.hpp
Labels: documentation

#5186 Add checkpointing to example BBH input files
  tests/InputFiles/GeneralizedHarmonic/BinaryBlackHole.yaml
  tests/InputFiles/GeneralizedHarmonic/CylindricalBinaryBlackHole.yaml
Labels: small

#5169 Add scalar tensor system and tags
  src/Evolution/Systems/CMakeLists.txt
  src/Evolution/Systems/ScalarTensor/CMakeLists.txt
  src/Evolution/Systems/ScalarTensor/StressEnergy.cpp
  src/Evolution/Systems/ScalarTensor/StressEnergy.hpp
  src/Evolution/Systems/ScalarTensor/System.hpp
  src/Evolution/Systems/ScalarTensor/Tags.hpp
  tests/Unit/Evolution/Systems/CMakeLists.txt
  tests/Unit/Evolution/Systems/ScalarTensor/CMakeLists.txt
  tests/Unit/Evolution/Systems/ScalarTensor/Test_Tags.cpp
Labels: new feature

#5165 Size unused tensor in IntrpTargetDetail
  src/ParallelAlgorithms/Interpolation/InterpolationTargetDetail.hpp
  tests/Unit/ParallelAlgorithms/Interpolation/CMakeLists.txt
  tests/Unit/ParallelAlgorithms/Interpolation/Test_ComputeDestVars.cpp
Labels: priority, bugfix

#5210 Only use BCO domains in BBH exec
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGhBinaryBlackHole.hpp
Labels: small

#5214 Update error tests in Averager
  tests/Unit/ControlSystem/Test_Averager.cpp
Labels: small

#5217 Remove an unused argument in partial_derivative
  src/NumericalAlgorithms/LinearOperators/PartialDerivatives.cpp
  src/NumericalAlgorithms/LinearOperators/PartialDerivatives.hpp
Labels: small

#5190 Make BBH time dependent options optional
  src/Domain/Creators/BinaryCompactObject.cpp
  src/Domain/Creators/BinaryCompactObject.hpp
  src/Domain/Creators/BinaryCompactObjectHelpers.cpp
  src/Domain/Creators/BinaryCompactObjectHelpers.hpp
  src/Domain/Creators/CylindricalBinaryCompactObject.cpp
  src/Domain/Creators/CylindricalBinaryCompactObject.hpp
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGhBinaryBlackHole.hpp
  src/Options/Auto.hpp
  tests/InputFiles/CurvedScalarWave/WorldtubeKerrSchild.yaml
  tests/InputFiles/ExportCoordinates/InputTimeDependent3D.yaml
  tests/InputFiles/GeneralizedHarmonic/BinaryBlackHole.yaml
  tests/InputFiles/GeneralizedHarmonic/CylindricalBinaryBlackHole.yaml
  tests/Unit/Domain/Creators/Test_BinaryCompactObject.cpp
  tests/Unit/Domain/Creators/Test_BinaryCompactObjectHelpers.cpp
  tests/Unit/Domain/Creators/Test_CylindricalBinaryCompactObject.cpp
  tests/Unit/Domain/Test_Domain.cpp
  tests/Unit/Helpers/Evolution/Systems/CurvedScalarWave/Worldtube/TestHelpers.cpp
Labels: priority

#5215 Handle relative paths in GenerateXdmf
  src/Visualization/Python/GenerateXdmf.py
  tests/Unit/Visualization/Python/Test_GenerateXdmf.py
Labels: small, bugfix

#5230 Update Elias' affiliation
  Metadata.yaml
Labels: small

#5236 Recover from permission error in status CLI
  support/SubmitScripts/SubmitTemplateBase.sh
  tools/Status/Status.py
Labels: small

#5156 Add parameterized deleptonization, without entropy
  docs/References.bib
  src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivClean.hpp
  src/Evolution/VariableFixing/CMakeLists.txt
  src/Evolution/VariableFixing/ParameterizedDeleptonization.cpp
  src/Evolution/VariableFixing/ParameterizedDeleptonization.hpp
  tests/Unit/Evolution/VariableFixing/CMakeLists.txt
  tests/Unit/Evolution/VariableFixing/Test_ParameterizedDeleptonization.cpp
Labels: new feature

#5239 Cleanups for starting on FD
  src/Evolution/DgSubcell/Actions/Initialize.hpp
  src/Evolution/DgSubcell/Actions/TakeTimeStep.hpp
  src/Evolution/DgSubcell/NeighborRdmpAndVolumeData.cpp
  src/Evolution/DgSubcell/Tags/Jacobians.hpp
  src/Evolution/DgSubcell/Tags/ObserverCoordinates.hpp
  src/Evolution/Executables/GrMhd/GhValenciaDivClean/GhValenciaDivCleanBase.hpp
  src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivClean.hpp
  src/Evolution/Executables/NewtonianEuler/EvolveNewtonianEuler.hpp
  src/Evolution/Executables/ScalarAdvection/EvolveScalarAdvection.hpp
  src/Evolution/Systems/Burgers/Subcell/InitialDataTci.cpp
  src/Evolution/Systems/Burgers/Subcell/InitialDataTci.hpp
  src/Evolution/Systems/Burgers/Subcell/TimeDerivative.hpp
  src/Evolution/Systems/ForceFree/Subcell/InitialDataTci.cpp
  src/Evolution/Systems/ForceFree/Subcell/InitialDataTci.hpp
  src/Evolution/Systems/GrMhd/GhValenciaDivClean/Subcell/NeighborPackagedData.hpp
  src/Evolution/Systems/GrMhd/GhValenciaDivClean/Subcell/TimeDerivative.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/InitialDataTci.cpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/InitialDataTci.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TimeDerivative.hpp
  src/Evolution/Systems/NewtonianEuler/Subcell/InitialDataTci.cpp
  src/Evolution/Systems/NewtonianEuler/Subcell/InitialDataTci.hpp
  src/Evolution/Systems/NewtonianEuler/Subcell/TimeDerivative.hpp
  src/Evolution/Systems/ScalarAdvection/Subcell/InitialDataTci.cpp
  src/Evolution/Systems/ScalarAdvection/Subcell/InitialDataTci.hpp
  src/Evolution/Systems/ScalarAdvection/Subcell/TimeDerivative.hpp
  src/PointwiseFunctions/AnalyticData/GeneralRelativity/InterpolateFromSpec.hpp
  tests/Unit/Evolution/DgSubcell/Actions/Test_Initialize.cpp
  tests/Unit/Evolution/DgSubcell/Actions/Test_TakeTimeStep.cpp
  tests/Unit/Evolution/DgSubcell/Test_JacobianCompute.cpp
  tests/Unit/Evolution/DgSubcell/Test_Tags.cpp
  tests/Unit/Evolution/Systems/Burgers/Subcell/Test_InitialDataTci.cpp
  tests/Unit/Evolution/Systems/Burgers/Subcell/Test_TimeDerivative.cpp
  tests/Unit/Evolution/Systems/ForceFree/Subcell/Test_InitialDataTci.cpp
  tests/Unit/Evolution/Systems/GrMhd/GhValenciaDivClean/Subcell/Test_TimeDerivative.cpp
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_InitialDataTci.cpp
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_TimeDerivative.cpp
  tests/Unit/Evolution/Systems/NewtonianEuler/Subcell/Test_InitialDataTci.cpp
  tests/Unit/Evolution/Systems/NewtonianEuler/Subcell/Test_TimeDerivative.cpp
  tests/Unit/Evolution/Systems/ScalarAdvection/Subcell/Test_InitialDataTci.cpp
  tests/Unit/Evolution/Systems/ScalarAdvection/Subcell/Test_TimeDerivative.cpp
Labels: priority

#5238 Add Bns executable with control systems
  src/ControlSystem/Event.hpp
  src/ControlSystem/Measurements/BNSCenterOfMass.hpp
  src/ControlSystem/Measurements/BothHorizons.hpp
  src/ControlSystem/Measurements/CharSpeed.hpp
  src/ControlSystem/Measurements/SingleHorizon.hpp
  src/ControlSystem/Metafunctions.hpp
  src/ControlSystem/Protocols/Submeasurement.hpp
  src/DataStructures/DataBox/ObservationBox.hpp
  src/Evolution/Executables/GrMhd/GhValenciaDivClean/CMakeLists.txt
  src/Evolution/Executables/GrMhd/GhValenciaDivClean/EvolveGhValenciaDivClean.hpp
  src/Evolution/Executables/GrMhd/GhValenciaDivClean/EvolveGhValenciaDivCleanFwd.hpp
  src/Evolution/Executables/GrMhd/GhValenciaDivClean/EvolveGhValenciaDivCleanWithHorizon.hpp
  src/Evolution/Executables/GrMhd/GhValenciaDivClean/EvolveGhValenciaDivCleanWithHorizonFwd.hpp
  src/Evolution/Executables/GrMhd/GhValenciaDivClean/GhValenciaDivCleanBase.hpp
  tests/InputFiles/GrMhd/GhValenciaDivClean/BinaryNeutronStar.yaml
  tests/Unit/ControlSystem/Actions/Test_InitializeMeasurements.cpp
  tests/Unit/ControlSystem/Test_Metafunctions.cpp
  tests/Unit/ControlSystem/Test_RunCallbacks.cpp
  tests/Unit/DataStructures/DataBox/Test_ObservationBox.cpp
  tests/Unit/Helpers/ControlSystem/Examples.hpp
Labels: auto-merge

#5252 Fix GH harmonic gauge FPEs
  src/Evolution/DiscontinuousGalerkin/Actions/ComputeTimeDerivative.hpp
  src/Evolution/Systems/GeneralizedHarmonic/GaugeSourceFunctions/Gauges.hpp
  src/Evolution/Systems/GeneralizedHarmonic/GaugeSourceFunctions/Harmonic.cpp
  src/Evolution/Systems/GeneralizedHarmonic/GaugeSourceFunctions/Harmonic.hpp
  src/Evolution/Systems/GeneralizedHarmonic/TimeDerivative.cpp
  src/Evolution/Systems/GrMhd/GhValenciaDivClean/Subcell/TimeDerivative.hpp
  src/Evolution/Systems/GrMhd/GhValenciaDivClean/TimeDerivativeTerms.hpp
  tests/Unit/Evolution/Systems/GeneralizedHarmonic/GaugeSourceFunctions/Test_AnalyticChristoffel.cpp
  tests/Unit/Evolution/Systems/GeneralizedHarmonic/GaugeSourceFunctions/Test_DampedHarmonic.cpp
  tests/Unit/Evolution/Systems/GeneralizedHarmonic/GaugeSourceFunctions/Test_Harmonic.cpp
Labels: priority, bugfix
