Repository sxs-collaboration/spectre, pull requests merged in 2023-09, with the labels that each got.

#5402 Fix race condition inside PiecewisePolynomial
  src/ControlSystem/UpdateFunctionOfTime.cpp
  src/ControlSystem/UpdateFunctionOfTime.hpp
  src/Domain/FunctionsOfTime/FunctionOfTime.hpp
  src/Domain/FunctionsOfTime/FunctionOfTimeHelpers.cpp
  src/Domain/FunctionsOfTime/FunctionOfTimeHelpers.hpp
  src/Domain/FunctionsOfTime/PiecewisePolynomial.cpp
  src/Domain/FunctionsOfTime/PiecewisePolynomial.hpp
  src/Domain/FunctionsOfTime/QuaternionFunctionOfTime.cpp
  src/Domain/FunctionsOfTime/QuaternionFunctionOfTime.hpp
  tests/Unit/ControlSystem/Test_UpdateFunctionOfTime.cpp
  tests/Unit/Domain/FunctionsOfTime/Test_FixedSpeedCubic.cpp
  tests/Unit/Domain/FunctionsOfTime/Test_FunctionOfTimeHelpers.cpp
  tests/Unit/Domain/FunctionsOfTime/Test_FunctionsOfTimeAreReady.cpp
  tests/Unit/Domain/FunctionsOfTime/Test_PiecewisePolynomial.cpp
  tests/Unit/Domain/FunctionsOfTime/Test_QuaternionFunctionOfTime.cpp
  tests/Unit/Domain/FunctionsOfTime/Test_SettleToConstant.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_AddTemporalIdsToInterpolationTarget.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_InterpolationTargetReceiveVars.cpp
Labels: priority, bugfix

#5413 Link libxsmm only in Release mode on ARM Macs
  src/Utilities/CMakeLists.txt
Labels: build system

#5380 Add GitHub workflow to build Docker containers
  .github/workflows/BuildDockerContainer.yaml
  .github/workflows/Tests.yaml
Labels: ci/cd

#5417 Exit on reaching negative pressure in Newman Hamlin solver
  src/Evolution/Systems/GrMhd/ValenciaDivClean/NewmanHamlin.cpp
Labels: bugfix

#5414 Use ccache for building docs on CI
  .github/workflows/Tests.yaml
Labels: ci/cd

#5422 Make Tabulated3D EOS PuPable
  src/PointwiseFunctions/Hydro/EquationsOfState/Tabulated3d.cpp
  src/PointwiseFunctions/Hydro/EquationsOfState/Tabulated3d.hpp
  tests/Unit/PointwiseFunctions/Hydro/EquationsOfState/Test_Tabulated3D.cpp
Labels: small, bugfix

#5415 Add a few more labels to release notes
  tools/CompileReleaseNotes.py
Labels: ci/cd

#5418 Don't save ccache temporary directory on CI
  .github/workflows/Tests.yaml
Labels: ci/cd

#5412 Merge 'combine-h5 {dat,vol}' CLI commands
  src/IO/H5/Python/CombineH5.py
  support/Python/__main__.py
  tests/Unit/IO/H5/Test_CombineH5.py
Labels: cli/pybindings

#5430 Adds more Pybindings for GH.
  src/PointwiseFunctions/GeneralRelativity/GeneralizedHarmonic/Python/Bindings.cpp
  tests/Unit/PointwiseFunctions/GeneralRelativity/Python/Test_GhBindings.py
Labels: cli/pybindings

#5435 Fix root brackets in Tabulated3D also for doubles
  src/PointwiseFunctions/Hydro/EquationsOfState/Tabulated3d.cpp
Labels: small, bugfix

#5433 Drop clang-10
  .github/workflows/Tests.yaml
  docs/DevGuide/QuickStartDockerVSCode.md
  docs/Installation/Installation.md
Labels: ci/cd

#5429 Build multi-platform x86 + ARM containers on CI
  .github/workflows/BuildDockerContainer.yaml
  .github/workflows/DemoContainer.yaml
Labels: ci/cd

#5443 Remove ExtendConnectivity C++ executable
  src/Executables/CMakeLists.txt
  src/Executables/ExtendConnectivity/CMakeLists.txt
  src/Executables/ExtendConnectivity/ExtendConnectivity.cpp
  tests/Unit/Executables/CMakeLists.txt
  tests/Unit/IO/Test_ExtendConnectivity_Data0.h5
Labels: small

#5445 Fix adding Spack version post-release
  .github/workflows/PostRelease.yaml
Labels: bugfix, ci/cd

#5447 Move devcontainer to repo root
  .devcontainer/cmake-kits.json
  .devcontainer/devcontainer.json
  .gitignore
  cmake/SetupFormaline.cmake
  docs/DevGuide/QuickStartDockerVSCode.md
Labels: ci/cd

#5449 Don't run spectre py version test in PY_DEV_MODE
  tests/support/Python/CMakeLists.txt
Labels: bugfix, build system, cli/pybindings

#5432 Speed up building Docker containers, upgrade container to Ubuntu 22.04, test Clang 14
  .devcontainer/cmake-kits.json
  .devcontainer/devcontainer.json
  .github/scripts/requirements-release.txt
  .github/workflows/Tests.yaml
  CMakeLists.txt
  cmake/Findcppcheck.cmake
  cmake/Findcppcheck.cpp
  cmake/SetupCppCheck.cmake
  cmake/SetupXsimd.cmake
  containers/Dockerfile.buildenv
  docs/Installation/Installation.md
  src/PointwiseFunctions/AnalyticData/Xcts/CMakeLists.txt
  tests/InputFiles/Cce/AnalyticTestLinearizedBondiSachs.yaml
  tests/Unit/Evolution/Systems/Cce/Test_SwshDerivatives.cpp
  tools/FileTestDefs.sh
Labels: ci/cd

#5436 Add AdaptiveOrder FD reconstructor to ForceFree system
  src/Evolution/Systems/ForceFree/FiniteDifference/AdaptiveOrder.cpp
  src/Evolution/Systems/ForceFree/FiniteDifference/AdaptiveOrder.hpp
  src/Evolution/Systems/ForceFree/FiniteDifference/CMakeLists.txt
  src/Evolution/Systems/ForceFree/FiniteDifference/Factory.hpp
  src/Evolution/Systems/ForceFree/FiniteDifference/Reconstructor.hpp
  tests/Unit/Evolution/Systems/ForceFree/CMakeLists.txt
  tests/Unit/Evolution/Systems/ForceFree/FiniteDifference/Test_AdaptiveOrder.cpp
Labels: auto-merge

#5454 Ignore some more clang-tidy warnings
  .clang-tidy
Labels: small

#5453 Fix race in list of StoredInfos
  src/Domain/FunctionsOfTime/FunctionOfTimeHelpers.cpp
Labels: bugfix

#5458 Add linear velocity term to BBH initial data
  src/PointwiseFunctions/AnalyticData/Xcts/Binary.cpp
  src/PointwiseFunctions/AnalyticData/Xcts/Binary.hpp
  tests/InputFiles/Xcts/BinaryBlackHole.yaml
  tests/InputFiles/Xcts/HeadOnBns.yaml
  tests/Unit/PointwiseFunctions/AnalyticData/Xcts/Binary.py
  tests/Unit/PointwiseFunctions/AnalyticData/Xcts/Test_Binary.cpp
Labels: small

#4951 Add Variables Temporaries Documentation
  docs/DevGuide/DevGuide.md
  docs/DevGuide/Variables.md
Labels: documentation, auto-merge

#5468 Fix an error message in factory creation
  src/Options/Factory.hpp
Labels: bugfix

#5473 Fix bug in deserialization of old QuaternionFoTs
  src/Domain/FunctionsOfTime/QuaternionFunctionOfTime.cpp
  tests/Unit/Domain/FunctionsOfTime/Test_PiecewisePolynomial.cpp
  tests/Unit/Domain/FunctionsOfTime/Test_QuaternionFunctionOfTime.cpp
Labels: bugfix

#5476 Use consistent memory order in QuatFoT
  src/Domain/FunctionsOfTime/QuaternionFunctionOfTime.cpp
Labels: small, bugfix

#5471 Add docs on building the Docker containers
  containers/Dockerfile.buildenv
Labels: documentation, ci/cd

#5331 Allow overwriting H5 tensor data, add `--force` option to transform-vol CLI
  src/IO/H5/Helpers.cpp
  src/IO/H5/Helpers.hpp
  src/IO/H5/Python/VolumeData.cpp
  src/IO/H5/VolumeData.cpp
  src/IO/H5/VolumeData.hpp
  src/Visualization/Python/TransformVolumeData.py
  tests/Unit/IO/H5/Test_H5.cpp
  tests/Unit/IO/H5/Test_VolumeData.cpp
  tests/Unit/Visualization/Python/Test_TransformVolumeData.py
Labels: cli/pybindings

#5477 Disable clang-tidy trivially-copyable move check
  .clang-tidy
Labels: small

#5469 Increase some test timeouts, fix a tolerance
  tests/InputFiles/Cce/AnalyticTestBouncingBlackHole.yaml
  tests/InputFiles/Cce/AnalyticTestGaugeWave.yaml
  tests/InputFiles/Cce/AnalyticTestRotatingSchwarzschild.yaml
  tests/InputFiles/Cce/AnalyticTestTeukolskyWave.yaml
  tests/Unit/Elliptic/Systems/Elasticity/BoundaryConditions/Test_LaserBeam.cpp
  tests/Unit/ParallelAlgorithms/ApparentHorizonFinder/Test_ApparentHorizonFinder.cpp
Labels: small, bugfix

#5482 Clarify expiration-time calculation documentation
  src/ControlSystem/ExpirationTimes.hpp
Labels: documentation, small

#5481 Install Clang 15 in container, remove Clang 11
  containers/Dockerfile.buildenv
Labels: ci/cd

#5470 Build charm `--with-production` in container
  containers/Dockerfile.buildenv
Labels: ci/cd

#5485 Add clang-tidy annotations on CI, run only over changed lines
  .github/problem_matchers/ClangTidy.json
  .github/workflows/Tests.yaml
Labels: ci/cd

#5493 Fix clang-tidy on CI
  .github/workflows/Tests.yaml
Labels: bugfix, ci/cd

#5434 Make KastaunHydro stable against unphysical energy states
  src/Evolution/Systems/GrMhd/ValenciaDivClean/KastaunEtAlHydro.cpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/KastaunEtAlHydro.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/PrimitiveFromConservative.cpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/PrimitiveFromConservative.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnDgGrid.cpp
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Test_PrimitiveFromConservative.cpp
Labels: small, bugfix

#5496 Make ExtractDat handle extensions and print error
  src/IO/H5/Python/ExtractDatFromH5.py
Labels: small, bugfix, cli/pybindings

#5494 Remove some catastrophic cancellation in prim recovery
  src/Evolution/Systems/GrMhd/ValenciaDivClean/KastaunEtAl.cpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/KastaunEtAl.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/KastaunEtAlHydro.cpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/KastaunEtAlHydro.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/NewmanHamlin.cpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/NewmanHamlin.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/PalenzuelaEtAl.cpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/PalenzuelaEtAl.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/PrimitiveFromConservative.cpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/PrimitiveRecoveryData.hpp
Labels: bugfix

#5501 Add missing include.
  src/Domain/Tags/Faces.hpp
Labels: bugfix

#5502 Report output file path when submitting jobs
  support/Python/Schedule.py
Labels: small, cli/pybindings

#5500 Fix h5 file names in CCE input file
  docs/Tutorials/CCE.md
  tests/InputFiles/Cce/CharacteristicExtract.yaml
Labels: small

#5504 Fix bug in damped harmonic gauge
  src/Evolution/Systems/GeneralizedHarmonic/GaugeSourceFunctions/DampedHarmonic.cpp
  tests/Unit/Evolution/Systems/GeneralizedHarmonic/GaugeSourceFunctions/Test_DampedHarmonic.cpp
Labels: priority, bugfix

#5511 Correct tabulated eos indexing bug
  src/PointwiseFunctions/Hydro/EquationsOfState/Tabulated3d.cpp
  tests/Unit/PointwiseFunctions/Hydro/EquationsOfState/Test_Tabulated3D.cpp
Labels: small, bugfix

#5503 Optimize interpolation onto sphere targets
  src/ControlSystem/Measurements/CharSpeed.hpp
  src/Domain/BlockLogicalCoordinates.cpp
  src/Domain/BlockLogicalCoordinates.hpp
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGhBinaryBlackHole.hpp
  src/Evolution/Executables/GeneralizedHarmonic/GeneralizedHarmonicBase.hpp
  src/ParallelAlgorithms/Interpolation/Events/InterpolateWithoutInterpComponent.hpp
  src/ParallelAlgorithms/Interpolation/InterpolationTargetDetail.hpp
  src/Utilities/Algorithm.hpp
  tests/Unit/Domain/Test_BlockAndElementLogicalCoordinates.cpp
  tests/Unit/Evolution/Systems/Cce/Actions/Test_SendGhVarsToCce.cpp
  tests/Unit/Helpers/ParallelAlgorithms/Interpolation/InterpolateOnElementTestHelpers.hpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_InterpolateWithoutInterpComponent.cpp
  tests/Unit/Utilities/Test_Algorithm.cpp
Labels: enhancement, priority

#5506 Add CAPTURE_FOR_ERROR to print info on failure
  src/Utilities/ErrorHandling/AbortWithErrorMessage.cpp
  src/Utilities/ErrorHandling/CMakeLists.txt
  src/Utilities/ErrorHandling/CaptureForError.cpp
  src/Utilities/ErrorHandling/CaptureForError.hpp
  tests/Unit/Utilities/ErrorHandling/CMakeLists.txt
  tests/Unit/Utilities/ErrorHandling/Test_CaptureForError.cpp
Labels: priority

#5509 Remove abseil checks from clang tidy
  .clang-tidy
Labels: small

#5492 Add Clang 16 to CI container
  containers/Dockerfile.buildenv
Labels: ci/cd

#5495 Work around boost failure to build in clang 15
  cmake/SetupBoost.cmake
Labels: bugfix, build system
