Repository sxs-collaboration/spectre, pull requests merged in 2023-05, with the labels that each got.

#4975 Fix debug print in control system
  src/ControlSystem/UpdateControlSystem.hpp
Labels: small, bugfix

#4976 Fix conflict between merged PRs
  tests/InputFiles/GeneralizedHarmonic/KerrSchild.yaml
Labels: priority

#4971 Filter job steps in status CLI
  tools/Status/Status.py
Labels: small

#4999 Fix bug in filter by block tag creation
  src/Evolution/Tags/Filter.hpp
  tests/Unit/NumericalAlgorithms/LinearOperators/Test_Filtering.cpp
Labels: small, bugfix

#5004 Increase epsilon tolerance of testing TildeJ
  tests/Unit/Evolution/Systems/ForceFree/Test_ElectricCurrentDensity.cpp
Labels: small

#4993 Get CaltechHPC up and running again
  support/Environments/caltech_hpc_gcc.sh
  support/Machines/CaltechHpc.yaml
  support/SubmitScripts/CaltechHpc.sh
Labels: priority

#5007 Make status CLI backwards compatible + some more fixes
  src/Visualization/Python/ReadInputFile.py
  support/Python/requirements.txt
  tools/Status/Status.py
Labels: bugfix

#5016 Prevent density from old value overwrite
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnDgGrid.cpp
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_TciOnDgGrid.cpp
Labels: small, bugfix

#4997 Fix cores/nodes in status CLI when job is pending
  tools/Status/Status.py
Labels: small, bugfix

#5023 Validate user input in CleanOutput, find PhaseChange in input file, add build dir option to CLI
  src/Visualization/Python/ReadInputFile.py
  support/Python/__main__.py
  tests/Unit/Visualization/Python/Test_ReadInputFile.py
  tools/CleanOutput.py
Labels: small, bugfix

#5015 Add memory monitor to GH execs
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGeneralizedHarmonicCce.hpp
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGeneralizedHarmonicNoBlackHole.hpp
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGeneralizedHarmonicSingleBlackHole.hpp
  src/Evolution/Executables/GeneralizedHarmonic/GeneralizedHarmonicBase.hpp
  tests/InputFiles/GeneralizedHarmonic/GaugeWave1D.yaml
  tests/InputFiles/GeneralizedHarmonic/GaugeWave3D.yaml
  tests/InputFiles/GeneralizedHarmonic/KerrSchild.yaml
Labels: small

#5030 Work around H5 issue with signed chars
  src/IO/H5/Type.hpp
Labels: bugfix

#5037 Speed up `InitializeElementFaces` test
  tests/Unit/Evolution/Systems/CurvedScalarWave/Worldtube/SingletonActions/Test_InitializeElementFacesGridCoordinates.cpp
Labels: small

#4989 Add control sys queue tags for size control
  src/ControlSystem/ControlErrors/Shape.hpp
  src/ControlSystem/Systems/Shape.hpp
  src/ControlSystem/Tags/QueueTags.hpp
  tests/Unit/ControlSystem/ControlErrors/Test_Shape.cpp
  tests/Unit/Helpers/ControlSystem/SystemHelpers.hpp
Labels: priority, small

#4986 Pass grid to target velocity in Compute*Quantities
  src/ApparentHorizons/ComputeExcisionBoundaryVolumeQuantities.hpp
  src/ApparentHorizons/ComputeExcisionBoundaryVolumeQuantities.tpp
  src/ApparentHorizons/ComputeHorizonVolumeQuantities.hpp
  src/ApparentHorizons/ComputeHorizonVolumeQuantities.tpp
  src/ParallelAlgorithms/Interpolation/InterpolationTargetDetail.hpp
  src/ParallelAlgorithms/Interpolation/Protocols/ComputeVarsToInterpolate.hpp
  tests/Unit/ApparentHorizons/Test_ComputeExcisionBoundaryVolumeQuantities.cpp
  tests/Unit/ApparentHorizons/Test_ComputeHorizonVolumeQuantities.cpp
  tests/Unit/Helpers/ParallelAlgorithms/Interpolation/Examples.hpp
Labels: priority

#5047 Remove 'A' from names in single BH exec
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGeneralizedHarmonicSingleBlackHole.hpp
  tests/InputFiles/GeneralizedHarmonic/KerrSchild.yaml
Labels: small

#5054 Add `cli` make target
  cmake/SpectreSetupPythonPackage.cmake
Labels: small

#5056 Include cli make target in some docs
  docs/DevGuide/BuildSystem.md
  docs/Installation/Installation.md
  docs/Tutorials/Python.md
Labels: documentation, small

#4994 Account for inverse roundoff in StrahlkorperInDiffFrame
  src/ApparentHorizons/StrahlkorperInDifferentFrame.cpp
Labels: priority, bugfix
