Repository sxs-collaboration/spectre, pull requests merged in 2023-11, with the labels that each got.

#5591 Add deploy container with compiled executables
  .dockerignore
  .github/workflows/DemoContainer.yaml
  containers/Dockerfile.buildenv
Labels: ci/cd

#5607 Register derived parallel callbacks
  src/Parallel/Callback.hpp
  src/Parallel/GlobalCache.hpp
  tests/Unit/Framework/ActionTesting.hpp
  tests/Unit/Parallel/Test_GlobalCache.cpp
Labels: bugfix

#5614 Add ErrorIfDataTooBig Event
  src/ParallelAlgorithms/Events/CMakeLists.txt
  src/ParallelAlgorithms/Events/ErrorIfDataTooBig.hpp
  src/ParallelAlgorithms/Events/Factory.hpp
  tests/Unit/ParallelAlgorithms/Events/CMakeLists.txt
  tests/Unit/ParallelAlgorithms/Events/Test_ErrorIfDataTooBig.cpp
Labels: auto-merge

#5612 Fix Zenodo upload
  .github/scripts/Release.py
Labels: bugfix, ci/cd

#5620 Fix doxygen warnings for certain functions
  src/PointwiseFunctions/GeneralRelativity/InterfaceNullNormal.hpp
  src/PointwiseFunctions/GeneralRelativity/ProjectionOperators.hpp
Labels: priority, bugfix

#5623 Fix interpolation framework when there are no valid points to interpolate
  src/ParallelAlgorithms/Interpolation/Actions/SendPointsToInterpolator.hpp
  src/ParallelAlgorithms/Interpolation/InterpolationTargetDetail.hpp
  tests/Unit/Helpers/IO/VolumeData.cpp
  tests/Unit/Helpers/IO/VolumeData.hpp
  tests/Unit/Helpers/ParallelAlgorithms/Interpolation/InterpolationTargetTestHelpers.hpp
  tests/Unit/IO/Observers/Test_VolumeObserver.cpp
  tests/Unit/ParallelAlgorithms/ApparentHorizonFinder/Test_ApparentHorizonFinder.cpp
  tests/Unit/ParallelAlgorithms/ApparentHorizonFinder/Test_InterpolationTargetApparentHorizon.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_InterpolationTargetKerrHorizon.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_InterpolationTargetLineSegment.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_InterpolationTargetSpecifiedPoints.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_InterpolationTargetSphere.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_InterpolationTargetWedgeSectionTorus.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_ObserveLineSegment.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_ObserveTimeSeriesAndSurfaceData.cpp
Labels: bugfix

#5625 Simplify tmpl::list_contains, add lazy version
  .github/workflows/Tests.yaml
  docs/DevGuide/Brigand.md
  src/DataStructures/DataBox/DataBox.hpp
  src/Utilities/TMPL.hpp
  tests/Unit/DataStructures/DataBox/Test_DataBox.cpp
  tests/Unit/Utilities/Test_TMPLDocumentation.cpp
Labels: auto-merge

#5637 Switch evolved_swsh_dt_tag and evolved_swsh_tag to tmpl::list
  src/Evolution/Executables/Cce/CharacteristicExtractBase.hpp
  src/Evolution/Systems/Cce/Actions/InitializeCharacteristicEvolutionTime.hpp
  src/Evolution/Systems/Cce/Actions/InitializeCharacteristicEvolutionVariables.hpp
  src/Evolution/Systems/Cce/Components/CharacteristicEvolution.hpp
  tests/Unit/Evolution/Systems/Cce/Actions/Test_AnalyticBoundaryCommunication.cpp
  tests/Unit/Evolution/Systems/Cce/Actions/Test_CharacteristicEvolutionBondiCalculations.cpp
  tests/Unit/Evolution/Systems/Cce/Actions/Test_GhBoundaryCommunication.cpp
  tests/Unit/Evolution/Systems/Cce/Actions/Test_H5BoundaryCommunication.cpp
  tests/Unit/Evolution/Systems/Cce/Actions/Test_InitializeCharacteristicEvolution.cpp
  tests/Unit/Evolution/Systems/Cce/Actions/Test_InsertInterpolationScriData.cpp
  tests/Unit/Evolution/Systems/Cce/Actions/Test_RequestBoundaryData.cpp
  tests/Unit/Evolution/Systems/Cce/Actions/Test_ScriObserveInterpolated.cpp
Labels: auto-merge

#5636 Make shape map exactly like the one in SpEC
  src/Domain/CoordinateMaps/TimeDependent/Shape.cpp
  src/Domain/CoordinateMaps/TimeDependent/Shape.hpp
  src/Domain/CoordinateMaps/TimeDependent/ShapeMapTransitionFunctions/ShapeMapTransitionFunction.hpp
  src/Domain/CoordinateMaps/TimeDependent/ShapeMapTransitionFunctions/SphereTransition.cpp
  src/Domain/CoordinateMaps/TimeDependent/ShapeMapTransitionFunctions/SphereTransition.hpp
  src/Domain/CoordinateMaps/TimeDependent/ShapeMapTransitionFunctions/Wedge.cpp
  src/Domain/CoordinateMaps/TimeDependent/ShapeMapTransitionFunctions/Wedge.hpp
  tests/Unit/Domain/CoordinateMaps/TimeDependent/ShapeMapTransitionFunctions/Test_SphereTransition.cpp
  tests/Unit/Domain/CoordinateMaps/TimeDependent/ShapeMapTransitionFunctions/Test_Wedge.cpp
  tests/Unit/Domain/CoordinateMaps/TimeDependent/Test_Shape.cpp
  tests/Unit/Domain/Creators/TimeDependence/Test_Shape.cpp
  tools/FileTestDefs.sh
Labels: priority
