Repository sxs-collaboration/spectre, pull requests merged in 2023-08, with the labels that each got.

#5262 Add data structure and tags for starting on FD
  src/Evolution/DgSubcell/CMakeLists.txt
  src/Evolution/DgSubcell/InitialTciData.cpp
  src/Evolution/DgSubcell/InitialTciData.hpp
  src/Evolution/DgSubcell/Tags/CMakeLists.txt
  src/Evolution/DgSubcell/Tags/InitialTciData.hpp
  src/Evolution/Systems/GrMhd/GhValenciaDivClean/Actions/SetInitialData.hpp
  tests/Unit/Evolution/DgSubcell/CMakeLists.txt
  tests/Unit/Evolution/DgSubcell/Test_InitialTciData.cpp
  tests/Unit/Evolution/Systems/GrMhd/GhValenciaDivClean/Actions/Test_SetInitialData.cpp
Labels: priority

#5279 Support subcell in importers
  src/Evolution/DgSubcell/CMakeLists.txt
  src/Evolution/DgSubcell/GetActiveTag.hpp
  src/Evolution/Executables/GrMhd/GhValenciaDivClean/GhValenciaDivCleanBase.hpp
  src/IO/Importers/Actions/RegisterWithElementDataReader.hpp
  src/IO/Importers/CMakeLists.txt
  tests/Unit/Evolution/DgSubcell/CMakeLists.txt
  tests/Unit/Evolution/DgSubcell/Test_GetActiveTag.cpp
  tests/Unit/IO/Importers/CMakeLists.txt
  tests/Unit/IO/Importers/Test_VolumeDataReaderActions.cpp
Labels: priority

#5257 Add Kerr plus scalar wave initial data for ScalarTensor
  src/Evolution/Systems/GeneralizedHarmonic/AllSolutions.hpp
  src/Evolution/Systems/GeneralizedHarmonic/CMakeLists.txt
  src/PointwiseFunctions/AnalyticData/CMakeLists.txt
  src/PointwiseFunctions/AnalyticData/GhScalarTensor/CMakeLists.txt
  src/PointwiseFunctions/AnalyticData/GhScalarTensor/Factory.hpp
  src/PointwiseFunctions/AnalyticData/GhScalarTensor/InstantiateWrappedGr.cpp
  src/PointwiseFunctions/AnalyticData/ScalarTensor/AnalyticData.hpp
  src/PointwiseFunctions/AnalyticData/ScalarTensor/CMakeLists.txt
  src/PointwiseFunctions/AnalyticData/ScalarTensor/KerrSphericalHarmonic.cpp
  src/PointwiseFunctions/AnalyticData/ScalarTensor/KerrSphericalHarmonic.hpp
  tests/Unit/PointwiseFunctions/AnalyticData/CMakeLists.txt
  tests/Unit/PointwiseFunctions/AnalyticData/ScalarTensor/CMakeLists.txt
  tests/Unit/PointwiseFunctions/AnalyticData/ScalarTensor/KerrSphericalHarmonic.py
  tests/Unit/PointwiseFunctions/AnalyticData/ScalarTensor/Test_KerrSphericalHarmonic.cpp
Labels: auto-merge

#5287 Add ScalarTensor stress energy test to cmake list
  tests/Unit/Evolution/Systems/ScalarTensor/CMakeLists.txt
  tests/Unit/Evolution/Systems/ScalarTensor/Test_StressEnergy.cpp
Labels: small, bugfix

#5298 Don't build same version of CMake twice in container
  containers/Dockerfile.buildenv
Labels: small

#5283 Make DG-FD executables to start on FD
  src/Evolution/DgSubcell/Actions/Initialize.hpp
  src/Evolution/Executables/Burgers/EvolveBurgers.hpp
  src/Evolution/Executables/GrMhd/GhValenciaDivClean/GhValenciaDivCleanBase.hpp
  src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivClean.hpp
  src/Evolution/Executables/NewtonianEuler/EvolveNewtonianEuler.hpp
  src/Evolution/Executables/ScalarAdvection/EvolveScalarAdvection.hpp
  src/Evolution/Systems/Burgers/Subcell/CMakeLists.txt
  src/Evolution/Systems/Burgers/Subcell/SetInitialRdmpData.cpp
  src/Evolution/Systems/Burgers/Subcell/SetInitialRdmpData.hpp
  src/Evolution/Systems/GrMhd/GhValenciaDivClean/Subcell/CMakeLists.txt
  src/Evolution/Systems/GrMhd/GhValenciaDivClean/Subcell/InitialDataTci.cpp
  src/Evolution/Systems/GrMhd/GhValenciaDivClean/Subcell/InitialDataTci.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/CMakeLists.txt
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/InitialDataTci.cpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/InitialDataTci.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/SetInitialRdmpData.cpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/SetInitialRdmpData.hpp
  src/Evolution/Systems/NewtonianEuler/Subcell/CMakeLists.txt
  src/Evolution/Systems/NewtonianEuler/Subcell/SetInitialRdmpData.cpp
  src/Evolution/Systems/NewtonianEuler/Subcell/SetInitialRdmpData.hpp
  src/Evolution/Systems/ScalarAdvection/Subcell/CMakeLists.txt
  src/Evolution/Systems/ScalarAdvection/Subcell/InitialDataTci.cpp
  src/Evolution/Systems/ScalarAdvection/Subcell/SetInitialRdmpData.cpp
  src/Evolution/Systems/ScalarAdvection/Subcell/SetInitialRdmpData.hpp
  tests/InputFiles/Elasticity/HalfSpaceMirror.yaml
  tests/Unit/Evolution/DgSubcell/Actions/Test_Initialize.cpp
  tests/Unit/Evolution/Systems/Burgers/CMakeLists.txt
  tests/Unit/Evolution/Systems/Burgers/Subcell/Test_InitialDataTci.cpp
  tests/Unit/Evolution/Systems/Burgers/Subcell/Test_SetInitialRdmpData.cpp
  tests/Unit/Evolution/Systems/GrMhd/GhValenciaDivClean/CMakeLists.txt
  tests/Unit/Evolution/Systems/GrMhd/GhValenciaDivClean/Subcell/Test_InitialDataTci.cpp
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/CMakeLists.txt
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_InitialDataTci.cpp
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_SetInitialRdmpData.cpp
  tests/Unit/Evolution/Systems/NewtonianEuler/CMakeLists.txt
  tests/Unit/Evolution/Systems/NewtonianEuler/Subcell/Test_InitialDataTci.cpp
  tests/Unit/Evolution/Systems/NewtonianEuler/Subcell/Test_SetInitialRdmpData.cpp
  tests/Unit/Evolution/Systems/ScalarAdvection/CMakeLists.txt
  tests/Unit/Evolution/Systems/ScalarAdvection/Subcell/Test_InitialDataTci.cpp
  tests/Unit/Evolution/Systems/ScalarAdvection/Subcell/Test_SetInitialRdmpData.cpp
  tests/Unit/Framework/MockRuntimeSystem.hpp
Labels: priority

#5212 Add time derivative computation to ScalarTensor
  src/Evolution/Systems/ScalarTensor/CMakeLists.txt
  src/Evolution/Systems/ScalarTensor/System.hpp
  src/Evolution/Systems/ScalarTensor/TimeDerivative.cpp
  src/Evolution/Systems/ScalarTensor/TimeDerivative.hpp
  src/Evolution/Systems/ScalarTensor/VolumeTermsInstantiation.cpp
  tests/Unit/Evolution/Systems/ScalarTensor/CMakeLists.txt
  tests/Unit/Evolution/Systems/ScalarTensor/Test_TimeDerivative.cpp
Labels: auto-merge

#5303 Make namespaces consistent for wrapped initial data lists
  src/Evolution/Systems/GeneralizedHarmonic/AllSolutions.hpp
  src/PointwiseFunctions/AnalyticData/GhGrMhd/Factory.hpp
  src/PointwiseFunctions/AnalyticSolutions/GhGrMhd/Factory.hpp
  src/PointwiseFunctions/AnalyticSolutions/GhRelativisticEuler/Factory.hpp
Labels: small

#5297 Drop Py3.7
  .github/workflows/Tests.yaml
  CMakeLists.txt
  containers/Dockerfile.buildenv
  docs/Installation/Installation.md
  setup.cfg
  src/IO/H5/Python/IterElements.py
  src/Visualization/Python/TransformVolumeData.py
  support/DevEnvironments/spack.yaml
  tests/Unit/Visualization/Python/Test_GenerateXdmf.py
Labels: auto-merge

#5300 Get h5 lock in DumpBondiSachs
  src/Evolution/Systems/Cce/Callbacks/DumpBondiSachsOnWorldtube.hpp
  tests/Unit/Evolution/Systems/Cce/Test_DumpBondiSachsOnWorldtube.cpp
Labels: auto-merge

#5315 Restrict phase changes to slab boundaries
  src/Parallel/PhaseControl/ExecutePhaseChange.hpp
Labels: bugfix

#5309 Allow use of ObservationBox in Intrp events
  src/ParallelAlgorithms/Interpolation/Events/CMakeLists.txt
  src/ParallelAlgorithms/Interpolation/Events/GetComputeItemsOnSource.hpp
  src/ParallelAlgorithms/Interpolation/Events/Interpolate.hpp
  src/ParallelAlgorithms/Interpolation/Events/InterpolateWithoutInterpComponent.hpp
Labels: small

#5313 Fix a GCC warning
  tests/Unit/Helpers/Domain/DomainTestHelpers.cpp
Labels: small

#5314 Fix fm disk compilation & increase Render1D timeout
  src/PointwiseFunctions/AnalyticData/GrMhd/MagnetizedFmDisk.cpp
  src/PointwiseFunctions/AnalyticData/GrMhd/MagnetizedFmDisk.hpp
  src/PointwiseFunctions/AnalyticSolutions/GeneralRelativity/WrappedGr.hpp
  src/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/FishboneMoncriefDisk.hpp
  tests/InputFiles/GrMhd/ValenciaDivClean/FishboneMoncriefDisk.yaml
  tests/Unit/Visualization/Python/CMakeLists.txt
Labels: priority, small, bugfix

#5316 Fix whitespace issues in a DataBox test
  tests/Unit/DataStructures/DataBox/Test_DataBox.cpp
Labels: small, bugfix

#5325 Fix rebase bug in CharSpeed for ObservationValue
  src/ControlSystem/Measurements/CharSpeed.hpp
Labels: small, bugfix

#5327 Add thread-safety docs to some FoTs
  src/Domain/FunctionsOfTime/PiecewisePolynomial.hpp
  src/Domain/FunctionsOfTime/QuaternionFunctionOfTime.hpp
Labels: small

#5332 Add cap to Lorentz factor and temperature minimum to GhGrmhd executable
  src/Evolution/Executables/GrMhd/GhValenciaDivClean/GhValenciaDivCleanBase.hpp
  src/Evolution/VariableFixing/FixToAtmosphere.cpp
  src/Evolution/VariableFixing/FixToAtmosphere.hpp
  tests/InputFiles/GrMhd/GhValenciaDivClean/BinaryNeutronStar.yaml
  tests/InputFiles/GrMhd/GhValenciaDivClean/GhMhdBondiMichel.yaml
  tests/InputFiles/GrMhd/GhValenciaDivClean/GhMhdTovStar.yaml
  tests/Unit/Evolution/VariableFixing/Test_FixToAtmosphere.cpp
Labels: auto-merge

#5319 Mock global cache
  cmake/FindCharm.cmake
  src/Parallel/CharmRegistration.hpp
  src/Parallel/GlobalCache.hpp
  src/ParallelAlgorithms/Amr/Actions/CreateChild.hpp
  src/ParallelAlgorithms/Amr/Actions/CreateParent.hpp
Labels: auto-merge

#5323 Add InversePlasmaBeta to Hydro
  src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivClean.hpp
  src/PointwiseFunctions/Hydro/CMakeLists.txt
  src/PointwiseFunctions/Hydro/InversePlasmaBeta.cpp
  src/PointwiseFunctions/Hydro/InversePlasmaBeta.hpp
  src/PointwiseFunctions/Hydro/Tags.hpp
  src/PointwiseFunctions/Hydro/TagsDeclarations.hpp
  tests/Unit/PointwiseFunctions/Hydro/CMakeLists.txt
  tests/Unit/PointwiseFunctions/Hydro/InversePlasmaBeta.py
  tests/Unit/PointwiseFunctions/Hydro/Test_InversePlasmaBeta.cpp
  tests/Unit/PointwiseFunctions/Hydro/Test_Tags.cpp
Labels: auto-merge

#5317 Avoid FPE for BBH observation horizon finds
  src/ControlSystem/Measurements/CharSpeed.hpp
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGhBinaryBlackHole.hpp
Labels: priority, bugfix

#5351 Run some input files only in one CI build
  .github/workflows/Tests.yaml
  cmake/AddInputFileTests.cmake
  docs/DevGuide/BuildSystem.md
  docs/DevGuide/WritingTests.md
  tests/InputFiles/Burgers/Step.yaml
  tests/InputFiles/Cce/AnalyticTestBouncingBlackHole.yaml
  tests/InputFiles/Cce/AnalyticTestGaugeWave.yaml
  tests/InputFiles/Cce/AnalyticTestLinearizedBondiSachs.yaml
  tests/InputFiles/Cce/AnalyticTestRobinsonTrautman.yaml
  tests/InputFiles/Cce/AnalyticTestRotatingSchwarzschild.yaml
  tests/InputFiles/Cce/AnalyticTestTeukolskyWave.yaml
  tests/InputFiles/Cce/CharacteristicExtract.yaml
  tests/InputFiles/CurvedScalarWave/PlaneWaveMinkowski3D.yaml
  tests/InputFiles/CurvedScalarWave/WorldtubeKerrSchild.yaml
  tests/InputFiles/Elasticity/HalfSpaceMirror.yaml
  tests/InputFiles/ExampleExecutables/HelloWorldNoCharm.yaml
  tests/InputFiles/ExampleExecutables/RandomAmr1D.yaml
  tests/InputFiles/ExampleExecutables/SingletonHelloWorld.yaml
  tests/InputFiles/ExportCoordinates/Input1D.yaml
  tests/InputFiles/ExportCoordinates/Input2D.yaml
  tests/InputFiles/ExportCoordinates/Input3D.yaml
  tests/InputFiles/ExportCoordinates/InputTimeDependent3D.yaml
  tests/InputFiles/ExportEquationOfStateForRotNS/ExportEosForRotNS.yaml
  tests/InputFiles/FindHorizons/FindHorizons3D.yaml
  tests/InputFiles/ForceFree/FastWave.yaml
  tests/InputFiles/GeneralizedHarmonic/BinaryBlackHole.yaml
  tests/InputFiles/GeneralizedHarmonic/CylindricalBinaryBlackHole.yaml
  tests/InputFiles/GeneralizedHarmonic/GaugeWave3D.yaml
  tests/InputFiles/GeneralizedHarmonic/KerrSchild.yaml
  tests/InputFiles/GrMhd/GhValenciaDivClean/BinaryNeutronStar.yaml
  tests/InputFiles/GrMhd/GhValenciaDivClean/GhMhdBondiMichel.yaml
  tests/InputFiles/GrMhd/GhValenciaDivClean/GhMhdTovStar.yaml
  tests/InputFiles/GrMhd/ValenciaDivClean/BlastWave.yaml
  tests/InputFiles/GrMhd/ValenciaDivClean/FishboneMoncriefDisk.yaml
  tests/InputFiles/NewtonianEuler/RiemannProblem3D.yaml
  tests/InputFiles/Poisson/ProductOfSinusoids3D.yaml
  tests/InputFiles/Punctures/MultiplePunctures.yaml
  tests/InputFiles/RadiationTransport/M1Grey/ConstantM1.yaml
  tests/InputFiles/RelativisticEuler/Valencia/SmoothFlow3D.yaml
  tests/InputFiles/ScalarAdvection/Kuzmin2D.yaml
  tests/InputFiles/ScalarWave/PlaneWave1D.yaml
  tests/InputFiles/ScalarWave/PlaneWave1DEventsAndTriggersExample.yaml
  tests/InputFiles/ScalarWave/PlaneWave1DObserveExample.yaml
  tests/InputFiles/Xcts/BinaryBlackHole.yaml
  tests/InputFiles/Xcts/HeadOnBns.yaml
  tests/InputFiles/Xcts/KerrSchild.yaml
  tests/InputFiles/Xcts/TovStar.yaml
  tests/tools/Test_ValidateInputFile.py
Labels: priority

#5301 Build PCH with CMake
  CMakeLists.txt
  cmake/SetupBlaze.cmake
  cmake/SetupCCache.cmake
  cmake/SetupClangTidy.cmake
  cmake/SetupPch.cmake
  cmake/SpectreAddLibraries.cmake
  cmake/SpectreAddTestLibs.cmake
  cmake/SpectreSetupPythonPackage.cmake
  cmake/UpdateAddExecutables.cmake
  tools/SpectrePch.hpp
  tools/WrapPchCompiler.sh
Labels: auto-merge

#5353 Print more information when an exception is caught by DistributedObject
  src/Parallel/DistributedObject.hpp
Labels: auto-merge

#5334 Fix threadsafety of PiecewisePolynomial
  src/Domain/FunctionsOfTime/FunctionOfTimeHelpers.cpp
  src/Domain/FunctionsOfTime/FunctionOfTimeHelpers.hpp
  src/Domain/FunctionsOfTime/PiecewisePolynomial.cpp
  src/Domain/FunctionsOfTime/PiecewisePolynomial.hpp
  src/Domain/FunctionsOfTime/QuaternionFunctionOfTime.cpp
  src/Domain/FunctionsOfTime/QuaternionFunctionOfTime.hpp
  tests/Unit/Domain/FunctionsOfTime/Test_FunctionOfTimeHelpers.cpp
Labels: priority, bugfix

#5270 Inject ExcisionSphere time dep in BCO domains
  src/Domain/Creators/BinaryCompactObject.cpp
  src/Domain/Creators/CylindricalBinaryCompactObject.cpp
  src/Domain/Domain.cpp
  src/Domain/Domain.hpp
  tests/Unit/Domain/Creators/Test_BinaryCompactObject.cpp
  tests/Unit/Domain/Creators/Test_CylindricalBinaryCompactObject.cpp
  tests/Unit/Domain/Test_Domain.cpp
Labels: priority

#5374 Fix running multiple random-value tests in a debugger
  tests/Unit/Framework/CheckWithRandomValues.hpp
  tests/Unit/Framework/SetupLocalPythonEnvironment.cpp
Labels: bugfix

#5255 Smooth horizon coefs in size control
  src/ControlSystem/ControlErrors/Size.cpp
  src/ControlSystem/ControlErrors/Size.hpp
  src/ControlSystem/ControlErrors/Size/Error.cpp
  src/ControlSystem/ControlErrors/Size/Error.hpp
  tests/Unit/ControlSystem/ControlErrors/Test_SizeError.cpp
Labels: priority

#5379 Two minor fixes in FFE code
  tests/Unit/PointwiseFunctions/AnalyticData/ForceFree/CMakeLists.txt
  tests/Unit/PointwiseFunctions/AnalyticData/ForceFree/Test_FfeBreakdown.cpp
Labels: small

#5310 Add MC reconstructor to ForceFree subcell
  src/Evolution/Systems/ForceFree/FiniteDifference/CMakeLists.txt
  src/Evolution/Systems/ForceFree/FiniteDifference/Factory.hpp
  src/Evolution/Systems/ForceFree/FiniteDifference/MonotonisedCentral.cpp
  src/Evolution/Systems/ForceFree/FiniteDifference/MonotonisedCentral.hpp
  src/Evolution/Systems/ForceFree/FiniteDifference/ReconstructWork.hpp
  src/Evolution/Systems/ForceFree/FiniteDifference/ReconstructWork.tpp
  src/Evolution/Systems/ForceFree/FiniteDifference/Reconstructor.hpp
  src/Evolution/Systems/ForceFree/FiniteDifference/RegisterDerivedWithCharm.cpp
  src/Evolution/Systems/ForceFree/FiniteDifference/RegisterDerivedWithCharm.hpp
  tests/Unit/Evolution/Systems/ForceFree/CMakeLists.txt
  tests/Unit/Evolution/Systems/ForceFree/FiniteDifference/Test_MonotonisedCentral.cpp
  tests/Unit/Helpers/Evolution/Systems/ForceFree/FiniteDifference/TestHelpers.hpp
Labels: auto-merge

#5394 Update Bond Sachs interpolation to run on GhMhd executables
  src/ControlSystem/Measurements/CharSpeed.hpp
  src/Evolution/Executables/CurvedScalarWave/EvolveCurvedScalarWave.hpp
  src/Evolution/Executables/CurvedScalarWave/EvolveWorldtubeCurvedScalarWave.hpp
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGhBinaryBlackHole.hpp
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGhSingleBlackHole.hpp
  src/Evolution/Executables/GrMhd/GhValenciaDivClean/GhValenciaDivCleanBase.hpp
  src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivClean.hpp
  src/Evolution/Executables/ScalarTensor/EvolveScalarTensorSingleBlackHole.hpp
  src/Evolution/Systems/Cce/Actions/SendGhVarsToCce.hpp
  src/ParallelAlgorithms/Interpolation/Events/InterpolateWithoutInterpComponent.hpp
  tests/Unit/Evolution/Systems/Cce/Actions/Test_SendGhVarsToCce.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_InterpolateWithoutInterpComponent.cpp
Labels: bugfix

#5409 Fix issue where bounds in Tabulated3D EOS can become zero
  src/PointwiseFunctions/Hydro/EquationsOfState/Tabulated3d.cpp
Labels: small, bugfix
