Repository sxs-collaboration/spectre, pull requests merged in 2023-01, with the labels that each got.

#4530 Fix density and temperature bounds in Compose table reader
  src/IO/ComposeTable.cpp
  tests/Unit/IO/Test_ComposeTable.cpp
Labels: small, bugfix

#4564 Ignore targets that don't use interpolator when cleaning interpolator
  src/ParallelAlgorithms/Interpolation/Actions/CleanUpInterpolator.hpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_CleanUpInterpolator.cpp
Labels: bugfix

#4579 Increase Test_BinaryCompactObject timeout
  tests/Unit/Domain/Creators/Test_BinaryCompactObject.cpp
Labels: small

#4534 Add docs to ah::ObjectLabel
  src/ApparentHorizons/ObjectLabel.hpp
Labels: documentation, small

#4606 Fix spelling in Metadata.yaml
  Metadata.yaml
  tools/CheckMetadata.py
Labels: small, bugfix

#4561 Add ApplyPointwise to Python CLI
  src/IO/H5/Python/VolumeData.cpp
  src/IO/H5/VolumeData.cpp
  src/IO/H5/VolumeData.hpp
  src/Visualization/Python/ApplyPointwise.py
  src/Visualization/Python/CMakeLists.txt
  support/Python/__main__.py
  tests/Unit/Helpers/IO/VolumeData.cpp
  tests/Unit/IO/H5/Test_VolumeData.cpp
  tests/Unit/Visualization/Python/CMakeLists.txt
  tests/Unit/Visualization/Python/Test_ApplyPointwise.py
Labels: new feature

#4607 Pin macOS version on CI
  .github/workflows/Tests.yaml
  src/Visualization/Python/InterpolateToCoords.py
  support/Python/requirements.txt
Labels: small, bugfix

#4616 Fix BoundaryMessage on macOS
  src/Evolution/DiscontinuousGalerkin/Messages/BoundaryMessage.cpp
  src/Evolution/DiscontinuousGalerkin/Messages/BoundaryMessage.hpp
  tests/Unit/Evolution/DiscontinuousGalerkin/Messages/Test_BoundaryMessage.cpp
Labels: bugfix

#4631 Print input file with syntax coloring in Python CLI
  src/IO/H5/Python/ExtractInputSourceYamlFromH5.py
Labels: small

#4654 Add ScalarWaveWorldtube library
  src/Evolution/Systems/CurvedScalarWave/CMakeLists.txt
  src/Evolution/Systems/CurvedScalarWave/Worldtube/CMakeLists.txt
  src/Evolution/Systems/CurvedScalarWave/Worldtube/Tags.cpp
  src/Evolution/Systems/CurvedScalarWave/Worldtube/Tags.hpp
  src/Evolution/Systems/CurvedScalarWave/Worldtube/Worldtube.hpp
Labels: auto-merge

#4638 Add resubmit capability to Wheeler submit script
  support/SubmitScripts/Wheeler.sh
Labels: small

#4667 Increase timeout of control system Shape test
  tests/Unit/ControlSystem/Systems/Test_Shape.cpp
Labels: small

#4653 Add distorted frame to block_logical_coordinates
  src/Domain/Block.hpp
  src/Domain/BlockLogicalCoordinates.cpp
  src/Domain/BlockLogicalCoordinates.hpp
  tests/Unit/Domain/Test_BlockAndElementLogicalCoordinates.cpp
Labels: auto-merge
