Repository sxs-collaboration/spectre, pull requests merged in 2023-12, with the labels that each got.

#5618 Add IMEX protocols
  src/Evolution/CMakeLists.txt
  src/Evolution/Imex/CMakeLists.txt
  src/Evolution/Imex/GuessResult.cpp
  src/Evolution/Imex/GuessResult.hpp
  src/Evolution/Imex/NamespaceDocs.hpp
  src/Evolution/Imex/Protocols/CMakeLists.txt
  src/Evolution/Imex/Protocols/ImexSystem.hpp
  src/Evolution/Imex/Protocols/ImplicitSector.hpp
  src/Evolution/Imex/Protocols/NamespaceDocs.hpp
  tests/Unit/Evolution/CMakeLists.txt
  tests/Unit/Evolution/Imex/CMakeLists.txt
  tests/Unit/Evolution/Imex/Test_GuessResult.cpp
Labels: new design

#5649 Minor db factoring
  src/DataStructures/DataBox/CMakeLists.txt
  src/DataStructures/DataBox/DataBox.hpp
  src/DataStructures/DataBox/IsApplyCallable.hpp
  src/Utilities/PrettyType.hpp
  src/Utilities/TypeTraits/CreateIsCallable.hpp
  tests/Unit/Utilities/Test_PrettyType.cpp
Labels: auto-merge

#5647 Reduce compilation memory of executables
  src/DataStructures/DataBox/DataBox.hpp
  src/Options/OptionsDetails.hpp
  src/Options/ParseOptions.cpp
  src/Options/ParseOptions.hpp
  src/Parallel/CMakeLists.txt
  src/Parallel/CharmRegistration.cpp
  src/Parallel/CharmRegistration.hpp
  src/ParallelAlgorithms/Events/CMakeLists.txt
  src/ParallelAlgorithms/Events/ObserveNorms.cpp
  src/ParallelAlgorithms/Events/ObserveNorms.hpp
Labels: enhancement, priority

#5660 Fix Zenodo upload
  .github/scripts/Release.py
Labels: priority, bugfix, ci/cd

#5661 Fix Spack post-release workflow
  .github/workflows/PostRelease.yaml
Labels: bugfix, ci/cd
