Repository sxs-collaboration/spectre, pull requests merged in 2023-03, with the labels that each got.

#4786 Send cell centered fluxes with FD.
  src/Evolution/DgSubcell/Actions/ReconstructionCommunication.hpp
  src/Evolution/DgSubcell/CMakeLists.txt
  src/Evolution/DgSubcell/CellCenteredFlux.hpp
  tests/Unit/Evolution/DgSubcell/Actions/Test_ReconstructionCommunication.cpp
  tests/Unit/Evolution/DgSubcell/CMakeLists.txt
  tests/Unit/Evolution/DgSubcell/Test_CellCenteredFlux.cpp
Labels: auto-merge

#4784 Use CHECK_ITERABLE_APPROX in TE Product test
  tests/Unit/DataStructures/Tensor/Expressions/Test_Product.cpp
Labels: bugfix

#4796 Ignore FD elements in PlotPowerMonitors
  src/Visualization/Python/PlotPowerMonitors.py
  support/Python/__main__.py
Labels: small, auto-merge

#4793 Add radially compressed coordinates
  src/Domain/CMakeLists.txt
  src/Domain/CoordinateMaps/Python/Bindings.cpp
  src/Domain/Python/Bindings.cpp
  src/Domain/Python/CMakeLists.txt
  src/Domain/Python/RadiallyCompressedCoordinates.cpp
  src/Domain/Python/RadiallyCompressedCoordinates.hpp
  src/Domain/RadiallyCompressedCoordinates.cpp
  src/Domain/RadiallyCompressedCoordinates.hpp
  src/Elliptic/Executables/Poisson/SolvePoisson.hpp
  src/Elliptic/Executables/Xcts/SolveXcts.hpp
  tests/InputFiles/Poisson/ProductOfSinusoids1D.yaml
  tests/InputFiles/Poisson/ProductOfSinusoids2D.yaml
  tests/InputFiles/Poisson/ProductOfSinusoids3D.yaml
  tests/InputFiles/Xcts/BinaryBlackHole.yaml
  tests/InputFiles/Xcts/HeadOnBns.yaml
  tests/InputFiles/Xcts/KerrSchild.yaml
  tests/InputFiles/Xcts/TovStar.yaml
  tests/Unit/Domain/CMakeLists.txt
  tests/Unit/Domain/Python/CMakeLists.txt
  tests/Unit/Domain/Python/Test_RadiallyCompressedCoordinates.py
  tests/Unit/Domain/Test_RadiallyCompressedCoordinates.cpp
Labels: auto-merge

#4802 Add integrands for BNS observers
  src/PointwiseFunctions/Hydro/CMakeLists.txt
  src/PointwiseFunctions/Hydro/MassWeightedFluidItems.cpp
  src/PointwiseFunctions/Hydro/MassWeightedFluidItems.hpp
  tests/Unit/PointwiseFunctions/Hydro/CMakeLists.txt
  tests/Unit/PointwiseFunctions/Hydro/TestFunctions.py
  tests/Unit/PointwiseFunctions/Hydro/Test_MassWeightedFluidItems.cpp
Labels: auto-merge

#4809 High order fd for grmhd
  src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivClean.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TimeDerivative.hpp
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_TimeDerivative.cpp
Labels: auto-merge

#4828 Fix History equality operator
  src/Time/History.hpp
  tests/Unit/Time/Test_History.cpp
Labels: bugfix, auto-merge

#4823 Write control system damping timescales to disk
  src/ControlSystem/UpdateControlSystem.hpp
  src/ControlSystem/WriteData.hpp
  tests/Unit/ControlSystem/Test_WriteData.cpp
Labels: auto-merge

#4822 Improve dox for Shape/Size maps.
  src/Domain/CoordinateMaps/TimeDependent/Shape.hpp
  src/Domain/CoordinateMaps/TimeDependent/SphericalCompression.hpp
  src/Domain/Creators/TimeDependence/Shape.hpp
  src/Domain/Creators/TimeDependence/SphericalCompression.hpp
Labels: documentation

#4713 Add and use weighted element distributions
  src/Domain/ElementDistribution.cpp
  src/Domain/ElementDistribution.hpp
  src/Domain/Structure/CMakeLists.txt
  src/Domain/Structure/ZCurve.cpp
  src/Domain/Structure/ZCurve.hpp
  src/Elliptic/DiscontinuousGalerkin/DgElementArray.hpp
  src/Evolution/DiscontinuousGalerkin/DgElementArray.hpp
  src/ParallelAlgorithms/LinearSolver/Multigrid/ElementsAllocator.hpp
  tests/Unit/Domain/Structure/CMakeLists.txt
  tests/Unit/Domain/Structure/Test_ZCurve.cpp
  tests/Unit/Domain/Test_ElementDistribution.cpp
Labels: enhancement

#4838 Increase test timeout for gcc-10 Debug build
  .github/workflows/Tests.yaml
Labels: auto-merge

#4841 Print pretty walltime in ObserveTimeStep event
  src/ParallelAlgorithms/Events/ObserveTimeStep.hpp
  tests/Unit/ParallelAlgorithms/Events/Test_ObserveTimeStep.cpp
Labels: small

#4842 No fd element with dg block neighbor at initialize
  src/Evolution/DgSubcell/Actions/Initialize.hpp
  src/Evolution/DgSubcell/Actions/TciAndRollback.hpp
  tests/Unit/Evolution/DgSubcell/Actions/Test_TciAndRollback.cpp
Labels: updated, small, bugfix

#4845 Fix evolution DgElementArray round robin proc skipping and info
  src/Evolution/DiscontinuousGalerkin/DgElementArray.hpp
Labels: small, bugfix

#4860 Modernize CSW System
  src/Evolution/Executables/CurvedScalarWave/EvolveCurvedScalarWave.hpp
  src/Evolution/Executables/CurvedScalarWave/EvolveWorldtubeCurvedScalarWave.hpp
  src/Evolution/Systems/CurvedScalarWave/CMakeLists.txt
  src/Evolution/Systems/CurvedScalarWave/Constraints.cpp
  src/Evolution/Systems/CurvedScalarWave/Equations.cpp
  src/Evolution/Systems/CurvedScalarWave/Equations.hpp
  src/Evolution/Systems/CurvedScalarWave/System.hpp
  src/Evolution/Systems/CurvedScalarWave/TimeDerivative.cpp
Labels: auto-merge

#4861 Fix comment in CylBinaryCompactObject
  src/Domain/Creators/CylindricalBinaryCompactObject.cpp
Labels: documentation, small

#4863 Correct name of executable for PlaneWave3D tutorial
  docs/Tutorials/Visualization.md
Labels: documentation, bugfix

#4870 Fix some CMake targets
  src/ControlSystem/Tags/CMakeLists.txt
  src/Domain/Creators/Tags/CMakeLists.txt
  src/Evolution/DiscontinuousGalerkin/Messages/CMakeLists.txt
  tests/Unit/Helpers/IO/Observers/CMakeLists.txt
Labels: bugfix

#4874 Enforce 3-con in GH numeric initial data
  src/Evolution/Systems/GeneralizedHarmonic/Actions/NumericInitialData.hpp
  tests/Unit/Evolution/Systems/GeneralizedHarmonic/Actions/Test_NumericInitialData.cpp
Labels: small

#4876 Allow read access to inboxes in DistributedObject
  src/Parallel/DistributedObject.hpp
Labels: small

#4882 Add missing instantiation to OrszagTangVortex
  src/PointwiseFunctions/AnalyticData/GrMhd/OrszagTangVortex.cpp
Labels: small, bugfix, auto-merge

#4886 Add `TraceSpacetimeChristoffelSecondKind` tag
  src/PointwiseFunctions/GeneralRelativity/Tags.hpp
  src/PointwiseFunctions/GeneralRelativity/TagsDeclarations.hpp
  tests/Unit/PointwiseFunctions/GeneralRelativity/Test_Tags.cpp
Labels: small
