Repository sxs-collaboration/spectre, pull requests merged in 2023-04, with the labels that each got.

#4888 Remove includes of ParseOptions.hpp from some headers
  src/ApparentHorizons/ComputeExcisionBoundaryVolumeQuantities.hpp
  src/DataStructures/CMakeLists.txt
  src/DataStructures/CompressedMatrix.cpp
  src/DataStructures/CompressedMatrix.hpp
  src/DataStructures/CompressedVector.cpp
  src/DataStructures/CompressedVector.hpp
  src/DataStructures/DynamicMatrix.cpp
  src/DataStructures/DynamicMatrix.hpp
  src/DataStructures/DynamicVector.cpp
  src/DataStructures/DynamicVector.hpp
  src/Domain/FunctionsOfTime/ReadSpecPiecewisePolynomial.cpp
  src/Evolution/DgSubcell/ActiveGrid.cpp
  src/Evolution/DgSubcell/ActiveGrid.hpp
  src/Evolution/DgSubcell/Tags/ActiveGrid.hpp
  src/Evolution/Systems/GeneralizedHarmonic/GaugeSourceFunctions/AnalyticChristoffel.cpp
  src/Executables/Benchmark/Benchmark.cpp
  src/IO/Importers/ObservationSelector.hpp
  src/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/Tov.cpp
  src/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/Tov.hpp
  src/PointwiseFunctions/AnalyticSolutions/Xcts/Schwarzschild.hpp
  tests/Unit/Evolution/Initialization/Test_Evolution.cpp
  tests/Unit/Evolution/Initialization/Test_SetVariables.cpp
  tests/Unit/Evolution/Systems/GrMhd/GhValenciaDivClean/FiniteDifference/Test_BoundaryConditionGhostData.cpp
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/FiniteDifference/Test_BoundaryConditionGhostData.cpp
  tests/Unit/Helpers/IO/Observers/MockH5.cpp
  tests/Unit/Helpers/IO/Observers/MockH5.hpp
Labels: auto-merge

#4899 Add `ObserveLineSegment` to worldtube
  src/Evolution/Executables/CurvedScalarWave/EvolveWorldtubeCurvedScalarWave.hpp
  src/ParallelAlgorithms/Interpolation/Targets/LineSegment.hpp
  tests/InputFiles/CurvedScalarWave/WorldtubeKerrSchild.yaml
  tests/Unit/ParallelAlgorithms/Interpolation/Test_ElementReceiveInterpPoints.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_InitializeInterpolationTarget.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_Interpolate.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_InterpolateWithoutInterpComponent.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_InterpolationTargetLineSegment.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_InterpolatorReceiveAndDumpVolumeData.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_InterpolatorReceivePoints.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_ObserveLineSegment.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_ParallelInterpolator.cpp
Labels: auto-merge

#4867 Add ability to filter by block
  src/Evolution/CMakeLists.txt
  src/Evolution/Executables/CurvedScalarWave/EvolveCurvedScalarWave.hpp
  src/Evolution/Executables/CurvedScalarWave/EvolveWorldtubeCurvedScalarWave.hpp
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGeneralizedHarmonicCce.hpp
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGhBinaryBlackHole.hpp
  src/Evolution/Executables/GeneralizedHarmonic/GeneralizedHarmonicBase.hpp
  src/Evolution/Executables/GrMhd/GhValenciaDivClean/GhValenciaDivCleanBase.hpp
  src/Evolution/Executables/ScalarWave/EvolveScalarWave.hpp
  src/Evolution/Tags/CMakeLists.txt
  src/Evolution/Tags/Filter.hpp
  src/NumericalAlgorithms/LinearOperators/CMakeLists.txt
  src/NumericalAlgorithms/LinearOperators/ExponentialFilter.cpp
  src/NumericalAlgorithms/LinearOperators/ExponentialFilter.hpp
  src/NumericalAlgorithms/LinearOperators/FilterAction.hpp
  src/NumericalAlgorithms/LinearOperators/Tags.hpp
  tests/InputFiles/CurvedScalarWave/PlaneWaveMinkowski1D.yaml
  tests/InputFiles/CurvedScalarWave/PlaneWaveMinkowski2D.yaml
  tests/InputFiles/CurvedScalarWave/PlaneWaveMinkowski3D.yaml
  tests/InputFiles/CurvedScalarWave/WorldtubeKerrSchild.yaml
  tests/InputFiles/GeneralizedHarmonic/BinaryBlackHole.yaml
  tests/InputFiles/GeneralizedHarmonic/CylindricalBinaryBlackHole.yaml
  tests/InputFiles/GeneralizedHarmonic/GaugeWave1D.yaml
  tests/InputFiles/GeneralizedHarmonic/GaugeWave3D.yaml
  tests/InputFiles/GeneralizedHarmonic/KerrSchild.yaml
  tests/InputFiles/GrMhd/GhValenciaDivClean/BinaryNeutronStar.yaml
  tests/InputFiles/GrMhd/GhValenciaDivClean/GhMhdTovStar.yaml
  tests/InputFiles/ScalarWave/PlaneWave1D.yaml
  tests/InputFiles/ScalarWave/PlaneWave1DObserveExample.yaml
  tests/InputFiles/ScalarWave/PlaneWave2D.yaml
  tests/InputFiles/ScalarWave/PlaneWave3D.yaml
  tests/Unit/Evolution/CMakeLists.txt
  tests/Unit/Evolution/Test_Tags.cpp
  tests/Unit/NumericalAlgorithms/LinearOperators/Test_Filtering.cpp
Labels: enhancement

#4928 Fix Zenodo references
  .github/scripts/Release.py
  tools/CheckMetadata.py
Labels: priority, bugfix

#4929 Minor fix in ObserveFields
  src/ParallelAlgorithms/Events/ObserveFields.hpp
Labels: small, bugfix, auto-merge

#4932 Fix incorrect header for BBH status
  tests/tools/Test_Status.py
  tools/Status/ExecutableStatus/EvolveGhBinaryBlackHole.py
Labels: small, bugfix

#4916 Load config file in CLI
  support/Python/__main__.py
  tests/support/Python/CMakeLists.txt
  tests/support/Python/Test_Main.py
Labels: auto-merge

#4931 Allow sphere transition inverse to handle epsilon
  src/Domain/CoordinateMaps/TimeDependent/ShapeMapTransitionFunctions/SphereTransition.cpp
  src/Domain/CoordinateMaps/TimeDependent/ShapeMapTransitionFunctions/SphereTransition.hpp
  tests/Unit/Domain/CoordinateMaps/TimeDependent/ShapeMapTransitionFunctions/Test_SphereTransition.cpp
  tests/Unit/Domain/CoordinateMaps/TimeDependent/Test_Shape.cpp
Labels: bugfix

#4910 Add option to use hard coded time dep maps in Sphere
  src/Domain/Creators/CMakeLists.txt
  src/Domain/Creators/Sphere.cpp
  src/Domain/Creators/Sphere.hpp
  src/Domain/Creators/SphereTimeDependentMaps.cpp
  src/Domain/Creators/SphereTimeDependentMaps.hpp
  tests/InputFiles/FindHorizons/FindHorizons3D.yaml
  tests/InputFiles/GeneralizedHarmonic/KerrSchild.yaml
  tests/InputFiles/GrMhd/GhValenciaDivClean/BinaryNeutronStar.yaml
  tests/InputFiles/GrMhd/GhValenciaDivClean/GhMhdBondiMichel.yaml
  tests/InputFiles/Punctures/MultiplePunctures.yaml
  tests/InputFiles/Xcts/KerrSchild.yaml
  tests/InputFiles/Xcts/TovStar.yaml
  tests/Unit/Domain/Creators/CMakeLists.txt
  tests/Unit/Domain/Creators/Test_Sphere.cpp
  tests/Unit/Domain/Creators/Test_SphereTimeDependentMaps.cpp
Labels: updated

#4936 Fix status CLI for jobs running in same work dir
  tools/Status/ExecutableStatus/EvolveGhBinaryBlackHole.py
  tools/Status/ExecutableStatus/EvolveGhSingleBlackHole.py
  tools/Status/ExecutableStatus/ExecutableStatus.py
  tools/Status/Status.py
Labels: bugfix

#4939 Minor fixes on GRMHD TCIs
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnDgGrid.cpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnFdGrid.cpp
Labels: small

#4963 Fix help_option_names in standalone Py scripts
  src/Visualization/Python/PlotDatFile.py
  src/Visualization/Python/Render1D.py
  tools/CharmSimplifyTraces.py
Labels: bugfix
