Repository sxs-collaboration/spectre, pull requests merged in 2024-01, with the labels that each got.

#5690 Remove duplicate entries in clang-format.
  .clang-format
Labels: bugfix

#5691 Add a radial expansion to the BBH ID pipeline
  support/Pipelines/Bbh/InitialData.py
  support/Pipelines/Bbh/InitialData.yaml
  support/Pipelines/Bbh/Inspiral.py
  support/Pipelines/Bbh/Inspiral.yaml
  tests/support/Pipelines/Bbh/Test_InitialData.py
  tests/support/Pipelines/Bbh/Test_Inspiral.py
  tests/support/Pipelines/Bbh/Test_Ringdown.py
Labels: cli/pybindings

#5695 Update Catch module on Wheeler
  support/Environments/wheeler_clang.sh
  support/Environments/wheeler_gcc.sh
Labels: small, bugfix

#5699 Fix ordering of IncludeCategories in clang-format
  .clang-format
Labels: bugfix

#5684 Solve for psi-1 in XCTS system
  src/Elliptic/DiscontinuousGalerkin/DgOperator.hpp
  src/Elliptic/Executables/Xcts/SolveXcts.hpp
  src/Elliptic/Systems/Xcts/BoundaryConditions/ApparentHorizon.cpp
  src/Elliptic/Systems/Xcts/BoundaryConditions/ApparentHorizon.hpp
  src/Elliptic/Systems/Xcts/BoundaryConditions/Flatness.cpp
  src/Elliptic/Systems/Xcts/BoundaryConditions/Flatness.hpp
  src/Elliptic/Systems/Xcts/Equations.cpp
  src/Elliptic/Systems/Xcts/Equations.hpp
  src/Elliptic/Systems/Xcts/FirstOrderSystem.hpp
  src/Elliptic/Systems/Xcts/FluxesAndSources.cpp
  src/Elliptic/Systems/Xcts/FluxesAndSources.hpp
  src/Elliptic/Systems/Xcts/Tags.hpp
  src/PointwiseFunctions/AnalyticData/Xcts/Binary.hpp
  src/PointwiseFunctions/AnalyticData/Xcts/CommonVariables.hpp
  src/PointwiseFunctions/AnalyticData/Xcts/CommonVariables.tpp
  src/PointwiseFunctions/AnalyticSolutions/Poisson/Lorentzian.cpp
  src/PointwiseFunctions/AnalyticSolutions/Poisson/Lorentzian.hpp
  src/PointwiseFunctions/AnalyticSolutions/Xcts/CommonVariables.hpp
  src/PointwiseFunctions/AnalyticSolutions/Xcts/CommonVariables.tpp
  src/PointwiseFunctions/AnalyticSolutions/Xcts/Flatness.hpp
  src/PointwiseFunctions/AnalyticSolutions/Xcts/Schwarzschild.cpp
  src/PointwiseFunctions/AnalyticSolutions/Xcts/Schwarzschild.hpp
  src/PointwiseFunctions/AnalyticSolutions/Xcts/TovStar.cpp
  src/PointwiseFunctions/AnalyticSolutions/Xcts/TovStar.hpp
  src/PointwiseFunctions/AnalyticSolutions/Xcts/WrappedGr.cpp
  src/PointwiseFunctions/AnalyticSolutions/Xcts/WrappedGr.hpp
  src/PointwiseFunctions/Xcts/SpacetimeQuantities.cpp
  src/PointwiseFunctions/Xcts/SpacetimeQuantities.hpp
  src/Utilities/TypeTraits/GetFundamentalType.hpp
  support/Pipelines/Bbh/InitialData.yaml
  tests/InputFiles/Poisson/Lorentzian.yaml
  tests/InputFiles/Xcts/BinaryBlackHole.yaml
  tests/InputFiles/Xcts/KerrSchild.yaml
  tests/InputFiles/Xcts/TovStar.yaml
  tests/Unit/Elliptic/Systems/Xcts/BoundaryConditions/ApparentHorizon.py
  tests/Unit/Elliptic/Systems/Xcts/BoundaryConditions/Test_ApparentHorizon.cpp
  tests/Unit/Elliptic/Systems/Xcts/BoundaryConditions/Test_Flatness.cpp
  tests/Unit/Elliptic/Systems/Xcts/Equations.py
  tests/Unit/Elliptic/Systems/Xcts/Test_Equations.cpp
  tests/Unit/Helpers/PointwiseFunctions/AnalyticSolutions/Xcts/VerifySolution.hpp
  tests/Unit/PointwiseFunctions/AnalyticData/Xcts/Binary.py
  tests/Unit/PointwiseFunctions/AnalyticData/Xcts/Test_Binary.cpp
  tests/Unit/PointwiseFunctions/AnalyticSolutions/Poisson/Lorentzian.py
  tests/Unit/PointwiseFunctions/AnalyticSolutions/Poisson/Test_Lorentzian.cpp
  tests/Unit/PointwiseFunctions/AnalyticSolutions/Xcts/Test_Schwarzschild.cpp
  tests/Unit/PointwiseFunctions/Xcts/Test_SpacetimeQuantities.cpp
Labels: auto-merge

#5706 Update Intel SDE used for Arch tests
  .github/workflows/Tests.yaml
Labels: priority

#5708 Improve documentation of EvenlySpaced TimeSequence
  src/Time/TimeSequence.hpp
Labels: documentation

#5704 Initialize Klein-Gordon CCE variables
  src/Evolution/Systems/Cce/Actions/CMakeLists.txt
  src/Evolution/Systems/Cce/Actions/InitializeKleinGordonVariables.hpp
  src/Evolution/Systems/Cce/Components/KleinGordonCharacteristicEvolution.hpp
  tests/Unit/Evolution/Systems/Cce/Actions/CMakeLists.txt
  tests/Unit/Evolution/Systems/Cce/Actions/Test_InitializeCharacteristicEvolution.cpp
  tests/Unit/Evolution/Systems/Cce/Actions/Test_InitializeKleinGordonCharacteristicEvolution.cpp
  tests/Unit/Helpers/Evolution/Systems/Cce/Actions/CharacteristicInitialization.hpp
Labels: auto-merge

#5714 Handle overflow in ContinuedFractionSummer
  src/Utilities/FractionUtilities.hpp
  tests/Unit/Utilities/Test_FractionUtilities.cpp
Labels: bugfix

#5720 Dump smoothing timescale in size control
  src/ControlSystem/ControlErrors/Size.cpp
  src/ControlSystem/ControlErrors/Size.hpp
Labels: small

#5719 Small Tov documentation typos
  src/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/TovStar.hpp
Labels: documentation, small, bugfix

#5713 Update documentation of Persson TCI
  src/Evolution/DgSubcell/PerssonTci.hpp
Labels: documentation
