Repository sxs-collaboration/spectre, pull requests merged in 2024-09, with the labels that each got.

#6257 Fix COM offset when starting from SpEC ID
  support/Pipelines/Bbh/Inspiral.py
Labels: bugfix

#6258 Fix race condition in exporter
  src/IO/Exporter/Exporter.cpp
Labels: bugfix

#6268 Fix CaltechHPC submit script
  support/SubmitScripts/CaltechHpc.sh
Labels: bugfix, auto-merge

#6266 Fix colorbar in PlotSlice
  src/Visualization/Python/PlotSlice.py
Labels: bugfix, cli/pybindings

#6277 Fix `size_t` underflow in geodesic worldtube evolution
  src/Evolution/Systems/CurvedScalarWave/Worldtube/ElementActions/SendToWorldtube.hpp
  src/Evolution/Systems/CurvedScalarWave/Worldtube/SingletonActions/ReceiveElementData.hpp
  tests/Unit/Evolution/Systems/CurvedScalarWave/Worldtube/ElementActions/Test_Iterations.cpp
Labels: bugfix

#6274 Prevent worldtube observing during substeps
  src/Evolution/Systems/CurvedScalarWave/Worldtube/SingletonActions/ObserveWorldtubeSolution.hpp
  tests/Unit/Evolution/Systems/CurvedScalarWave/Worldtube/SingletonActions/Test_ObserveWorldtubeSolution.cpp
Labels: bugfix

#6243 Add Wedge Offset Option to BCO
  docs/Images/Domain/DomainCreators/binary_compact_object_domain.png
  src/Domain/Creators/BinaryCompactObject.cpp
  src/Domain/Creators/BinaryCompactObject.hpp
  src/Domain/Creators/CylindricalBinaryCompactObject.cpp
  src/Domain/Creators/Sphere.cpp
  src/Domain/Creators/TimeDependentOptions/BinaryCompactObject.cpp
  src/Domain/Creators/TimeDependentOptions/BinaryCompactObject.hpp
  src/Domain/DomainHelpers.cpp
  src/Domain/DomainHelpers.hpp
  support/Pipelines/Bbh/InitialData.yaml
  support/Pipelines/Bbh/Inspiral.yaml
  tests/InputFiles/CurvedScalarWave/WorldtubeKerrSchild.yaml
  tests/InputFiles/ExportCoordinates/InputTimeDependent3D.yaml
  tests/InputFiles/GrMhd/GhValenciaDivClean/BinaryNeutronStar.yaml
  tests/InputFiles/Xcts/BinaryBlackHole.yaml
  tests/InputFiles/Xcts/HeadOnBns.yaml
  tests/Unit/Domain/Creators/Test_BinaryCompactObject.cpp
  tests/Unit/Domain/Creators/Test_Tags.cpp
  tests/Unit/Domain/Creators/TimeDependentOptions/Test_BinaryCompactObject.cpp
  tests/Unit/Domain/Test_Domain.cpp
  tests/Unit/Domain/Test_DomainHelpers.cpp
  tests/Unit/Evolution/Systems/CurvedScalarWave/Worldtube/SingletonActions/Test_InitializeElementFacesGridCoordinates.cpp
  tests/Unit/Helpers/Evolution/Systems/CurvedScalarWave/Worldtube/TestHelpers.cpp
  tests/Unit/Helpers/ParallelAlgorithms/Interpolation/InterpolateOnElementTestHelpers.hpp
  tests/Unit/IO/Exporter/Test_Exporter.cpp
  tests/Unit/IO/Importers/Test_VolumeDataReaderAlgorithm3D.yaml
Labels: priority

#6253 Fix communication race bug in interpolation framework
  src/ParallelAlgorithms/ApparentHorizonFinder/Callbacks/FindApparentHorizon.hpp
  src/ParallelAlgorithms/Interpolation/Actions/AddTemporalIdsToInterpolationTarget.hpp
  src/ParallelAlgorithms/Interpolation/Actions/InitializeInterpolationTarget.hpp
  src/ParallelAlgorithms/Interpolation/Actions/InterpolationTargetReceiveVars.hpp
  src/ParallelAlgorithms/Interpolation/Actions/InterpolationTargetVarsFromElement.hpp
  src/ParallelAlgorithms/Interpolation/Actions/VerifyTemporalIdsAndSendPoints.hpp
  src/ParallelAlgorithms/Interpolation/Callbacks/ObserveTimeSeriesOnSurface.hpp
  src/ParallelAlgorithms/Interpolation/Interpolate.hpp
  src/ParallelAlgorithms/Interpolation/InterpolationTargetDetail.hpp
  src/ParallelAlgorithms/Interpolation/Protocols/ComputeTargetPoints.hpp
  src/ParallelAlgorithms/Interpolation/Tags.hpp
  tests/Unit/Framework/MockRuntimeSystem.hpp
  tests/Unit/Helpers/ParallelAlgorithms/Interpolation/Examples.hpp
  tests/Unit/Helpers/ParallelAlgorithms/Interpolation/InterpolationTargetTestHelpers.hpp
  tests/Unit/ParallelAlgorithms/ApparentHorizonFinder/Test_ApparentHorizonFinder.cpp
  tests/Unit/ParallelAlgorithms/ApparentHorizonFinder/Test_InterpolationTargetApparentHorizon.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_AddTemporalIdsToInterpolationTarget.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_Interpolate.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_InterpolationTargetKerrHorizon.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_InterpolationTargetLineSegment.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_InterpolationTargetReceiveVars.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_InterpolationTargetSpecifiedPoints.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_InterpolationTargetSphere.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_InterpolationTargetVarsFromElement.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_InterpolationTargetWedgeSectionTorus.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_InterpolatorReceiveAndDumpVolumeData.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_ObserveLineSegment.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_ObserveTimeSeriesAndSurfaceData.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_ParallelInterpolator.cpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_Tags.cpp
Labels: bugfix

#6267 Add Perlmutter machine
  cmake/Findccache.cmake
  cmake/SetupCCache.cmake
  support/Environments/perlmutter.sh
  support/Machines/Perlmutter.yaml
  support/SubmitScripts/Perlmutter.sh
Labels: clusters

#6271 Document CCE grid point locations for Ylms
  docs/Tutorials/CCE.md
  tests/Unit/NumericalAlgorithms/SphericalHarmonics/Test_Spherepack.cpp
Labels: documentation, auto-merge

#6270 Add Christoffel symbol and trace to `BackgroundQuantities`
  src/Evolution/Systems/CurvedScalarWave/Worldtube/SingletonActions/UpdateAcceleration.cpp
  src/Evolution/Systems/CurvedScalarWave/Worldtube/SingletonActions/UpdateAcceleration.hpp
  src/Evolution/Systems/CurvedScalarWave/Worldtube/Tags.cpp
  src/Evolution/Systems/CurvedScalarWave/Worldtube/Tags.hpp
  tests/Unit/Evolution/Systems/CurvedScalarWave/Worldtube/ElementActions/Test_SendToWorldtube.cpp
  tests/Unit/Evolution/Systems/CurvedScalarWave/Worldtube/SingletonActions/Test_UpdateAcceleration.cpp
  tests/Unit/Evolution/Systems/CurvedScalarWave/Worldtube/Test_Tags.cpp
Labels: auto-merge

#6282 Fix clang-tidy quirk
  .clang-tidy
Labels: small, bugfix

#6292 Increase a test timeout
  tests/Unit/IO/H5/Test_CheckH5PropertiesMatch.cpp
Labels: small

#6289 TransformVolumeData.py: support ElementId in kernels
  src/Domain/Python/ElementId.cpp
  src/IO/Exporter/Python/__init__.py
  src/Visualization/Python/TransformVolumeData.py
  tests/Unit/Domain/Python/Test_ElementId.py
  tests/Unit/Visualization/Python/Test_TransformVolumeData.py
Labels: cli/pybindings

#6290 Fix output for eccentricity params
  support/Pipelines/EccentricityControl/EccentricityControl.py
Labels: small, bugfix

#6294 Fix release notes for empty PR description
  tests/tools/Test_CompileReleaseNotes.py
  tools/CompileReleaseNotes.py
Labels: bugfix, ci/cd

#6273 Add tags used to smoothly turn on the self force
  src/Evolution/Executables/CurvedScalarWave/EvolveWorldtubeCurvedScalarWave.hpp
  src/Evolution/Systems/CurvedScalarWave/Worldtube/Tags.cpp
  src/Evolution/Systems/CurvedScalarWave/Worldtube/Tags.hpp
  tests/Unit/Evolution/Systems/CurvedScalarWave/Worldtube/Test_Tags.cpp
Labels: auto-merge

#6288 Add documentation and function to make debugging multiple MPI ranks easier
  docs/DevGuide/DebuggingTips.md
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGhBinaryBlackHole.cpp
  src/Utilities/System/AttachDebugger.cpp
  src/Utilities/System/AttachDebugger.hpp
  src/Utilities/System/CMakeLists.txt
  tools/CheckFiles.sh
Labels: documentation

#6304 Hitchhiker’s Guide Update
  docs/Tutorials/BeginnersTutorial.md
Labels: documentation

#6313 Avoid running out of disk space on CI
  .github/workflows/Tests.yaml
Labels: bugfix, ci/cd

#6291 Update Inspiral.yaml
  support/Pipelines/Bbh/Inspiral.py
  support/Pipelines/Bbh/Inspiral.yaml
Labels: auto-merge, cli/pybindings

#6303 Add support for tetrahedral connectivity and use scipy to generate it
  src/Visualization/Python/CMakeLists.txt
  src/Visualization/Python/GenerateTetrahedralConnectivity.py
  src/Visualization/Python/GenerateXdmf.py
  support/Python/__main__.py
  tests/Unit/Visualization/Python/CMakeLists.txt
  tests/Unit/Visualization/Python/Test_GenerateTetrahedralConnectivity.py
  tests/Unit/Visualization/Python/Test_GenerateXdmf.py
  tests/Unit/Visualization/Python/VolTestData0.h5
  tests/Unit/Visualization/Python/VolTestDataTetrahedral.xmf
Labels: cli/pybindings
