Repository sxs-collaboration/spectre, pull requests merged in 2024-07, with the labels that each got.

#6141 Fix Alex Macedo ORCID
  Metadata.yaml
Labels: small

#6145 Update some control system plotting
  src/Visualization/Python/PlotControlSystem.py
  src/Visualization/Python/PlotSizeControl.py
Labels: bugfix, cli/pybindings

#6096 Add TaggedVariant, parsable similarly to a factory
  src/DataStructures/CMakeLists.txt
  src/DataStructures/TaggedVariant.hpp
  tests/Unit/DataStructures/CMakeLists.txt
  tests/Unit/DataStructures/Test_TaggedVariant.cpp
Labels: auto-merge

#6148 InitialData.py: allow to disable param control
  support/Pipelines/Bbh/InitialData.py
Labels: cli/pybindings

#6152 Add environment for Oscar (cluster at Brown)
  cmake/SetupCxxFlags.cmake
  src/DataStructures/Index.hpp
  src/Utilities/ErrorHandling/StrerrorWrapper.c
  support/Environments/oscar.sh
  support/Machines/Oscar.yaml
  support/Python/CliExceptions.py
  support/Python/Schedule.py
  support/SubmitScripts/Oscar.sh
Labels: priority

#6149 Add some pybindings
  src/DataStructures/Tensor/EagerMath/Python/Determinant.cpp
  src/DataStructures/Tensor/Python/Tensor.tpp
  src/NumericalAlgorithms/LinearOperators/Python/PartialDerivatives.cpp
  src/NumericalAlgorithms/Spectral/Python/Mesh.cpp
  tests/Unit/DataStructures/Tensor/Python/Test_Tensor.py
  tests/Unit/NumericalAlgorithms/LinearOperators/Python/Test_PartialDerivatives.py
  tests/Unit/ParallelAlgorithms/ApparentHorizonFinder/Test_ApparentHorizonFinder.cpp
Labels: cli/pybindings

#6162 Maintain initial data resolution in control loop.
  support/Pipelines/Bbh/ControlId.py
  support/Pipelines/Bbh/InitialData.yaml
  support/Pipelines/Bbh/PostprocessId.py
  tests/support/Pipelines/Bbh/Test_InitialData.py
Labels: auto-merge

#6160 Print ElementId in DataTooBig error
  src/ParallelAlgorithms/Events/ErrorIfDataTooBig.hpp
  tests/Unit/ParallelAlgorithms/Events/Test_ErrorIfDataTooBig.cpp
Labels: small

#6158 Allow compiling nodegroup elements and with numerical data (errors for now)
  src/IO/Importers/Actions/ReadVolumeData.hpp
Labels: auto-merge

#6165 Ignore matplotlib font manager debug logging info
  src/Visualization/Python/GenerateXdmf.py
  src/Visualization/Python/Render1D.py
  support/Python/CMakeLists.txt
  support/Python/Logging.py
  support/Python/__main__.py
  tests/Unit/Visualization/Python/Test_GenerateXdmf.py
  tests/Unit/Visualization/Python/Test_InterpolateToMesh.py
  tests/Unit/Visualization/Python/Test_PlotTrajectories.py
  tests/support/Pipelines/Bbh/Test_FindHorizon.py
  tests/support/Pipelines/Bbh/Test_InitialData.py
  tests/support/Pipelines/Bbh/Test_Inspiral.py
  tests/support/Pipelines/Bbh/Test_PostprocessId.py
  tests/support/Pipelines/Bbh/Test_Ringdown.py
  tests/support/Pipelines/EccentricityControl/Test_EccentricityControl.py
  tests/support/Pipelines/EccentricityControl/Test_InitialOrbitalParameters.py
  tests/support/Python/Test_DirectoryStructure.py
  tests/support/Python/Test_RunNext.py
  tests/support/Python/Test_Schedule.py
  tests/tools/Test_Status.py
Labels: cli/pybindings

#6167 Use clang-tidy-16 on CI
  .github/workflows/Tests.yaml
Labels: ci/cd

#6178 Fix minimial executable so it builds
  src/Executables/Examples/ParallelTutorial/MinimalExecutable.cpp
Labels: auto-merge

#6094 Update Ocean submit script
  support/Environments/ocean_gcc.sh
  support/Machines/Ocean.yaml
  support/SubmitScripts/Ocean.sh
  support/SubmitScripts/OceanClang.sh
Labels: auto-merge
