Repository sxs-collaboration/spectre, pull requests merged in 2024-05, with the labels that each got.

#5959 Fix CaltechHPC environment
  docs/Installation/InstallationOnClusters.md
  support/Environments/caltech_hpc_gcc.sh
  support/Environments/caltech_hpc_gcc_icelake.sh
  support/Environments/caltech_hpc_gcc_skylake.sh
  support/Machines/CaltechHpc.yaml
  support/Machines/CaltechHpcIcelake.yaml
  support/Python/Schedule.py
  support/SubmitScripts/CaltechHpc.sh
  support/SubmitScripts/CaltechHpcIcelake.sh
  tests/support/Python/Test_Schedule.py
Labels: priority

#5980 Bump versions of GitHub actions
  .github/workflows/BuildDockerContainer.yaml
  .github/workflows/ClobberCache.yaml
  .github/workflows/DemoContainer.yaml
  .github/workflows/NewContributors.yaml
  .github/workflows/PostRelease.yaml
  .github/workflows/Tests.yaml
Labels: ci/cd

#5984 Fix broken codecov links in Readme
  .github/workflows/Tests.yaml
  README.md
  docs/Main.md
Labels: ci/cd

#5978 Add CLI to plot basic control system quantities
  src/Visualization/Python/CMakeLists.txt
  src/Visualization/Python/PlotControlSystem.py
  src/Visualization/Python/__init__.py
  tests/Unit/Visualization/Python/CMakeLists.txt
  tests/Unit/Visualization/Python/Test_PlotControlSystem.py
Labels: cli/pybindings

#5987 Plot zero crossing time on log scale in PlotSize CLI
  src/Visualization/Python/PlotSizeControl.py
Labels: small, auto-merge, cli/pybindings

#5991 Disable code cov
  .github/workflows/Tests.yaml
Labels: auto-merge

#6007 Plot along line log scale options
  src/Visualization/Python/PlotAlongLine.py
  tests/Unit/Visualization/Python/Test_PlotAlongLine.py
Labels: small, cli/pybindings

#6013 Enable filtering in GH LTS evolutions
  src/Evolution/Executables/GeneralizedHarmonic/GeneralizedHarmonicBase.hpp
  src/Evolution/Executables/ScalarTensor/ScalarTensorBase.hpp
Labels: auto-merge

#6014 Add ErrorIfDataTooBig to BBH pipeline
  support/Pipelines/Bbh/Inspiral.yaml
  support/Pipelines/Bbh/Ringdown.yaml
Labels: small

#6027 More minor code for nodegroup elements
  src/Evolution/DiscontinuousGalerkin/InboxTags.hpp
  src/Evolution/DiscontinuousGalerkin/Initialization/Mortars.hpp
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGhBinaryBlackHole.hpp
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGhNoBlackHole.hpp
  src/Evolution/Executables/GeneralizedHarmonic/EvolveGhSingleBlackHole.hpp
  src/Evolution/Executables/ScalarWave/EvolveScalarWave.hpp
  src/Parallel/DistributedObject.hpp
  tests/Unit/Evolution/DiscontinuousGalerkin/Initialization/Test_Mortars.cpp
  tests/Unit/Evolution/DiscontinuousGalerkin/Messages/Test_InboxTags.cpp
Labels: auto-merge

#6031 Support SpEC initial data in BBH pipeline
  support/Pipelines/Bbh/Inspiral.py
  support/Pipelines/Bbh/Inspiral.yaml
Labels: cli/pybindings
