Repository sxs-collaboration/spectre, pull requests merged in 2024-08, with the labels that each got.

#6171 Reorganize build system docs
  docs/DevGuide/DevGuide.md
  docs/Installation/BuildSystem.md
  docs/Installation/Installation.md
  docs/Main.md
Labels: documentation, priority

#6191 Update Oscar config
  cmake/SetupCCache.cmake
  support/Environments/oscar.sh
Labels: priority, build system

#6189 Add parallelization tutorial executable PiMonteCarlo
  src/Executables/Examples/CMakeLists.txt
  src/Executables/Examples/PiMonteCarlo/CMakeLists.txt
  src/Executables/Examples/PiMonteCarlo/PiMonteCarlo.cpp
  src/Executables/Examples/PiMonteCarlo/PiMonteCarloTutorial.cpp
  tests/InputFiles/ExampleExecutables/PiMonteCarlo.yaml
Labels: priority

#6190 Add some defaults to eccentricity control CLI
  support/Pipelines/EccentricityControl/EccentricityControl.py
Labels: cli/pybindings

#6193 Enforce cascadelake arch on Oscar
  support/Environments/oscar.sh
Labels: priority

#6195 Enable ParaView on Oscar
  support/Environments/oscar.sh
  tools/Status/ExecutableStatus/EvolveGhBinaryBlackHole.py
Labels: priority

#6196 Factor plotting functions out of CLI
  src/Visualization/Python/PlotAlongLine.py
  src/Visualization/Python/PlotSlice.py
Labels: priority, cli/pybindings

#6197 Add zoom to BBH rendering script
  src/Visualization/Python/Render3D/Bbh.py
Labels: priority, cli/pybindings

#6205 Add favicon with spectre logo
  docs/Doxyfile.in
  docs/config/apple-touch-icon.png
  docs/config/favicon-16x16.png
  docs/config/favicon-32x32.png
  docs/config/favicon.ico
  docs/config/header.html
  docs/config/safari-pinned-tab.svg
  tools/FileTestDefs.sh
Labels: documentation

#6206 PlotPowerMonitors: skip filtered modes
  src/Visualization/Python/PlotPowerMonitors.py
Labels: cli/pybindings

#6201 Add link to logos
  README.md
  docs/Doxyfile.in
  docs/Images/banner.png
  docs/Main.md
Labels: documentation, auto-merge

#5956 Download dependencies on demand
  CMakeLists.txt
  cmake/BootstrapPyDeps.cmake
  cmake/FindBlaze.cmake
  cmake/FindLIBXSMM.cmake
  cmake/FindYAMLCPP.cmake
  cmake/SetupBlaze.cmake
  cmake/SetupCatch.cmake
  cmake/SetupLIBXSMM.cmake
  cmake/SetupLinkTimeOptimization.cmake
  cmake/SetupYamlCpp.cmake
  docs/Installation/BuildSystem.md
  docs/Installation/Installation.md
  src/Options/CMakeLists.txt
Labels: priority, build system

#6209 Fix clang-tidy exit codes on CI
  .github/workflows/Tests.yaml
Labels: bugfix, ci/cd

#6211 Clarify error messages in H5 Cce constructor
  src/IO/H5/Cce.cpp
  tests/Unit/IO/H5/Test_Cce.cpp
Labels: small

#6215 Fix typo in BC test.
  tests/Unit/Elliptic/Systems/Poisson/BoundaryConditions/Test_Robin.cpp
Labels: bugfix

#6216 Fix macOS CI
  .github/workflows/Tests.yaml
Labels: bugfix, auto-merge, ci/cd

#6222 Document Exporter namespace
  src/IO/Exporter/Exporter.hpp
Labels: documentation

#6210 Disable LB test in Burgers yaml
  src/Visualization/Python/ReadInputFile.py
  tests/InputFiles/Burgers/Step.yaml
  tests/Unit/Visualization/Python/Test_ReadInputFile.py
Labels: ci/cd

#6226 Fix clang-tidy on CI
  cmake/SetupBlaze.cmake
  src/Utilities/BlazeExceptions.hpp
  src/Utilities/CMakeLists.txt
  tools/SpectrePch.hpp
Labels: bugfix, ci/cd

#6229 Fix clang-tidy errors in PiMonteCarlo example
  src/Executables/Examples/PiMonteCarlo/PiMonteCarlo.cpp
  src/Executables/Examples/PiMonteCarlo/PiMonteCarloTutorial.cpp
Labels: small

#6225 Fix iterations test failure
  tests/Unit/Evolution/Systems/CurvedScalarWave/Worldtube/ElementActions/Test_Iterations.cpp
Labels: small

#6232 Fix compatibility with Numpy 2.1
  src/NumericalAlgorithms/OdeIntegration/OdeIntegration.hpp
  tests/Unit/Framework/PyppFundamentals.hpp
  tests/Unit/Framework/SetupLocalPythonEnvironment.cpp
Labels: priority, bugfix, auto-merge

#6235 Increase timeout in ReadBoundaryDataH5 test
  tests/Unit/Evolution/Systems/Cce/Test_WorldtubeData.cpp
Labels: small

#3825 Blaze: restore support for padding
  cmake/SetupBlaze.cmake
  src/Evolution/DgSubcell/Matrices.cpp
  src/Evolution/DgSubcell/Reconstruction.cpp
  tests/Unit/Evolution/DgSubcell/Test_Matrices.cpp
  tests/Unit/NumericalAlgorithms/Spectral/Test_Spectral.cpp
Labels: auto-merge

#5587 Construct DataVector from STL containers
  src/ControlSystem/CMakeLists.txt
  src/ControlSystem/ControlErrors/Rotation.hpp
  src/ControlSystem/ControlErrors/Translation.hpp
  src/ControlSystem/DataVectorHelpers.cpp
  src/ControlSystem/DataVectorHelpers.hpp
  src/ControlSystem/Systems/Expansion.hpp
  src/ControlSystem/Systems/Rotation.hpp
  src/ControlSystem/Systems/Translation.hpp
  src/DataStructures/VectorImpl.hpp
  src/IO/External/InterpolateFromFuka.cpp
  tests/Unit/ControlSystem/CMakeLists.txt
  tests/Unit/ControlSystem/ControlErrors/Test_Rotation.cpp
  tests/Unit/ControlSystem/ControlErrors/Test_Translation.cpp
  tests/Unit/ControlSystem/Systems/Test_RotScaleTrans.cpp
  tests/Unit/ControlSystem/Systems/Test_Translation.cpp
  tests/Unit/ControlSystem/Test_DataVectorHelpers.cpp
  tests/Unit/Helpers/ControlSystem/SystemHelpers.hpp
  tests/Unit/Helpers/DataStructures/VectorImplTestHelper.hpp
Labels: auto-merge

#5535 Add tutorial for visualizing volume data with Python, update docs
  docs/Tutorials/Cli.md
  docs/Tutorials/Python.md
  docs/Tutorials/Tutorials.md
  docs/Tutorials/Visualization.md
  docs/Tutorials/VisualizationWithPython.ipynb
Labels: documentation, cli/pybindings

#6234 Allow offset in Wedge transition function
  docs/Images/Domain/CoordinateMaps/WedgeTransition.jpg
  src/Domain/CoordinateMaps/TimeDependent/ShapeMapTransitionFunctions/Wedge.cpp
  src/Domain/CoordinateMaps/TimeDependent/ShapeMapTransitionFunctions/Wedge.hpp
  src/Domain/Creators/TimeDependentOptions/BinaryCompactObject.cpp
  tests/Unit/Domain/CoordinateMaps/TimeDependent/ShapeMapTransitionFunctions/Test_Wedge.cpp
  tests/Unit/Helpers/Domain/CoordinateMaps/TestMapHelpers.hpp
  tools/FileTestDefs.sh
Labels: priority

#6250 Fix infinite loop time step rejection
  .clang-tidy
  src/Time/Actions/ChangeStepSize.hpp
  src/Time/ChooseLtsStepSize.cpp
  tests/Unit/Time/Actions/Test_ChangeStepSize.cpp
Labels: bugfix

#6214 Enable Wedges to have a focal offset
  docs/Images/Domain/CoordinateMaps/Wedge3D/FocalOffset.jpg
  src/Domain/CoordinateMaps/Wedge.cpp
  src/Domain/CoordinateMaps/Wedge.hpp
  tests/Unit/Domain/CoordinateMaps/Test_Wedge2D.cpp
  tests/Unit/Domain/CoordinateMaps/Test_Wedge3D.cpp
  tests/Unit/Domain/Creators/Test_CylindricalBinaryCompactObject.cpp
Labels: priority, auto-merge
