Repository sxs-collaboration/spectre, pull requests merged in 2024-02, with the labels that each got.

#5723 Add CLI to plot size control diagnostics
  src/Visualization/Python/CMakeLists.txt
  src/Visualization/Python/PlotSizeControl.py
  support/Python/__main__.py
  tests/Unit/Visualization/Python/CMakeLists.txt
  tests/Unit/Visualization/Python/Test_PlotSizeControl.py
Labels: cli/pybindings

#5738 Add LTO support
  CMakeLists.txt
  cmake/SetupLinkTimeOptimization.cmake
  docs/DevGuide/BuildSystem.md
Labels: build system

#5746 Fix a minus sign in puncture equations
  src/Elliptic/Systems/Punctures/Sources.cpp
  src/Elliptic/Systems/Punctures/Sources.hpp
  tests/Unit/Elliptic/Systems/Punctures/Equations.py
Labels: bugfix

#5743 Find ParaView properly in build system
  .github/workflows/Tests.yaml
  CMakeLists.txt
  cmake/FindParaView.cmake
  cmake/FindPythonModule.cmake
  cmake/SetupDoxygen.cmake
  cmake/SetupParaView.cmake
  cmake/SetupPypp.cmake
  cmake/SpectrePythonExecutable.sh
  cmake/SpectreSetupPythonPackage.cmake
  docs/DevGuide/BuildSystem.md
  tests/Unit/Visualization/Python/Render3D/CMakeLists.txt
Labels: build system

#5751 Fix error in FindPythonModule
  cmake/FindPythonModule.cmake
Labels: bugfix, build system

#5755 Turn finding ParaView off by default
  cmake/SetupParaView.cmake
  docs/DevGuide/BuildSystem.md
  support/Environments/caltech_hpc_gcc_icelake.sh
  support/Environments/caltech_hpc_gcc_skylake.sh
Labels: bugfix, auto-merge, build system

#5761 Add #s to the check for an error message in the validate CLI
  tools/ValidateInputFile.py
Labels: small, cli/pybindings

#5773 Fix ParaView rendering on CI by avoiding apt update
  .github/workflows/Tests.yaml
Labels: priority, bugfix, auto-merge, ci/cd

#5780 Disable paraview rendering tests on CI temporarily
  .github/workflows/Tests.yaml
Labels: priority, bugfix, ci/cd

#5779 Use multiple highest modes for Persson TCI and remove initial data TCI
  src/Evolution/DgSubcell/Actions/Initialize.hpp
  src/Evolution/DgSubcell/PerssonTci.cpp
  src/Evolution/DgSubcell/PerssonTci.hpp
  src/Evolution/DgSubcell/SubcellOptions.cpp
  src/Evolution/DgSubcell/SubcellOptions.hpp
  src/Evolution/Systems/Burgers/Subcell/TciOnDgGrid.cpp
  src/Evolution/Systems/Burgers/Subcell/TciOnFdGrid.cpp
  src/Evolution/Systems/ForceFree/Subcell/TciOnDgGrid.cpp
  src/Evolution/Systems/ForceFree/Subcell/TciOnFdGrid.cpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnDgGrid.cpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnFdGrid.cpp
  src/Evolution/Systems/NewtonianEuler/Subcell/TciOnDgGrid.cpp
  src/Evolution/Systems/NewtonianEuler/Subcell/TciOnFdGrid.cpp
  src/Evolution/Systems/ScalarAdvection/Subcell/TciOnDgGrid.cpp
  src/Evolution/Systems/ScalarAdvection/Subcell/TciOnFdGrid.cpp
  tests/InputFiles/Burgers/Step.yaml
  tests/InputFiles/GrMhd/GhValenciaDivClean/BinaryNeutronStar.yaml
  tests/InputFiles/GrMhd/GhValenciaDivClean/GhMhdTovStar.yaml
  tests/InputFiles/GrMhd/ValenciaDivClean/BlastWave.yaml
  tests/InputFiles/GrMhd/ValenciaDivClean/FishboneMoncriefDisk.yaml
  tests/InputFiles/NewtonianEuler/RiemannProblem1D.yaml
  tests/InputFiles/NewtonianEuler/RiemannProblem2D.yaml
  tests/InputFiles/NewtonianEuler/RiemannProblem3D.yaml
  tests/InputFiles/ScalarAdvection/Krivodonova1D.yaml
  tests/InputFiles/ScalarAdvection/Kuzmin2D.yaml
  tests/InputFiles/ScalarAdvection/Sinusoid1D.yaml
  tests/Unit/Evolution/DgSubcell/Actions/Test_Initialize.cpp
  tests/Unit/Evolution/DgSubcell/Actions/Test_TciAndRollback.cpp
  tests/Unit/Evolution/DgSubcell/Actions/Test_TciAndSwitchToDg.cpp
  tests/Unit/Evolution/DgSubcell/Test_CellCenteredFlux.cpp
  tests/Unit/Evolution/DgSubcell/Test_PerssonTci.cpp
  tests/Unit/Evolution/DgSubcell/Test_PrepareNeighborData.cpp
  tests/Unit/Evolution/DgSubcell/Test_SubcellOptions.cpp
  tests/Unit/Evolution/DgSubcell/Test_Tags.cpp
  tests/Unit/Evolution/Systems/Burgers/Subcell/Test_TciOnDgGrid.cpp
  tests/Unit/Evolution/Systems/Burgers/Subcell/Test_TciOnFdGrid.cpp
  tests/Unit/Evolution/Systems/ForceFree/Subcell/Test_NeighborPackagedData.cpp
  tests/Unit/Evolution/Systems/ForceFree/Subcell/Test_TciOnDgGrid.cpp
  tests/Unit/Evolution/Systems/ForceFree/Subcell/Test_TciOnFdGrid.cpp
  tests/Unit/Evolution/Systems/GrMhd/GhValenciaDivClean/Subcell/Test_NeighborPackagedData.cpp
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_NeighborPackagedData.cpp
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_TciOnDgGrid.cpp
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_TciOnFdGrid.cpp
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_TimeDerivative.cpp
  tests/Unit/Evolution/Systems/NewtonianEuler/Subcell/Test_NeighborPackagedData.cpp
  tests/Unit/Evolution/Systems/NewtonianEuler/Subcell/Test_TciOnDgGrid.cpp
  tests/Unit/Evolution/Systems/NewtonianEuler/Subcell/Test_TciOnFdGrid.cpp
  tests/Unit/Evolution/Systems/ScalarAdvection/Subcell/Test_NeighborPackagedData.cpp
  tests/Unit/Evolution/Systems/ScalarAdvection/Subcell/Test_TciOnDgGrid.cpp
  tests/Unit/Evolution/Systems/ScalarAdvection/Subcell/Test_TciOnFdGrid.cpp
Labels: new feature

#5783 Fix an unchaged filtering extent in PerssonTci
  src/Evolution/DgSubcell/PerssonTci.cpp
  tests/Unit/Evolution/DgSubcell/Test_PerssonTci.cpp
Labels: priority

#5794 Increase PerssonTci test timeout
  tests/Unit/Evolution/DgSubcell/Test_PerssonTci.cpp
Labels: ci/cd

#5749 Add CLI tool to plot volume data along a line, group plotting commands in CLI
  docs/Tutorials/Visualization.md
  src/Visualization/Python/CMakeLists.txt
  src/Visualization/Python/PlotAlongLine.py
  src/Visualization/Python/PlotDatFile.py
  src/Visualization/Python/PlotPowerMonitors.py
  src/Visualization/Python/PlotSizeControl.py
  src/Visualization/Python/__init__.py
  support/Python/__main__.py
  tests/Unit/Visualization/Python/CMakeLists.txt
  tests/Unit/Visualization/Python/Test_PlotAlongLine.py
Labels: cli/pybindings

#5763 Prevent events used in control system from being factory creatable
  src/ControlSystem/Measurements/BothHorizons.hpp
  src/ControlSystem/Measurements/CMakeLists.txt
  src/ControlSystem/Measurements/CharSpeed.hpp
  src/ControlSystem/Measurements/NonFactoryCreatable.hpp
  src/ControlSystem/Measurements/SingleHorizon.hpp
  src/ParallelAlgorithms/Interpolation/Events/Interpolate.hpp
  tests/Unit/ControlSystem/Test_Measurements.cpp
Labels: bugfix

#5806 Update ocean charm module for move to C++20
  support/Environments/ocean_gcc.sh
Labels: priority, small

#5768 Support older control system output in size plotting
  src/ControlSystem/ControlErrors/Size.cpp
  src/ControlSystem/ControlErrors/Size.hpp
  src/Visualization/Python/PlotSizeControl.py
  tests/Unit/ControlSystem/ControlErrors/Test_SizeError.cpp
Labels: cli/pybindings

#5804 Add error if RotNS file does not exist
  src/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/RotatingStar.cpp
  tests/Unit/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/Test_RotatingStar.cpp
Labels: small

#5810 Fix a typo in elliptic status CLI
  tools/Status/ExecutableStatus/ExecutableStatus.py
Labels: bugfix, cli/pybindings
