Repository sxs-collaboration/spectre, pull requests merged in 2024-11, with the labels that each got.

#6339 Numeric ID importer: support p-refinement
  src/IO/Importers/Actions/ReadVolumeData.hpp
  src/IO/Importers/Actions/RegisterWithElementDataReader.hpp
  src/IO/Importers/Tags.hpp
  support/Pipelines/Bbh/Inspiral.yaml
  support/Pipelines/Bbh/Ringdown.yaml
  tests/InputFiles/GeneralizedHarmonic/CylindricalBinaryBlackHole.yaml
  tests/InputFiles/GrMhd/GhValenciaDivClean/BinaryNeutronStar.yaml
  tests/Unit/Evolution/Systems/GeneralizedHarmonic/Actions/Test_SetInitialData.cpp
  tests/Unit/Evolution/Systems/GrMhd/GhValenciaDivClean/Actions/Test_SetInitialData.cpp
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Actions/Test_NumericInitialData.cpp
  tests/Unit/IO/Importers/Test_Tags.cpp
  tests/Unit/IO/Importers/Test_VolumeDataReaderActions.cpp
  tests/Unit/IO/Importers/Test_VolumeDataReaderAlgorithm.hpp
  tests/Unit/IO/Importers/Test_VolumeDataReaderAlgorithm1D.yaml
  tests/Unit/IO/Importers/Test_VolumeDataReaderAlgorithm2D.yaml
  tests/Unit/IO/Importers/Test_VolumeDataReaderAlgorithm3D.yaml
Labels: auto-merge

#6358 Fix bugs in RefineMesh Event
  docs/DevGuide/Amr.md
  src/ParallelAlgorithms/Amr/Events/RefineMesh.hpp
  src/ParallelAlgorithms/Amr/Policies/EnforcePolicies.cpp
  src/ParallelAlgorithms/Amr/Policies/EnforcePolicies.hpp
  src/ParallelAlgorithms/Amr/Policies/Limits.cpp
  src/ParallelAlgorithms/Amr/Policies/Limits.hpp
  support/Pipelines/Bbh/InitialData.yaml
  support/Pipelines/Bbh/Inspiral.yaml
  support/Pipelines/Bbh/Ringdown.yaml
  tests/InputFiles/Elasticity/BentBeam.yaml
  tests/InputFiles/Elasticity/HalfSpaceMirror.yaml
  tests/InputFiles/Elasticity/SingleCoatingMirror.yaml
  tests/InputFiles/ExampleExecutables/RandomAmr1D.yaml
  tests/InputFiles/ExportCoordinates/Input1D.yaml
  tests/InputFiles/ExportCoordinates/Input2D.yaml
  tests/InputFiles/ExportCoordinates/Input3D.yaml
  tests/InputFiles/ExportCoordinates/InputTimeDependent3D.yaml
  tests/InputFiles/GeneralizedHarmonic/CylindricalBinaryBlackHole.yaml
  tests/InputFiles/GeneralizedHarmonic/GaugeWave1D.yaml
  tests/InputFiles/GeneralizedHarmonic/GaugeWave3D.yaml
  tests/InputFiles/GeneralizedHarmonic/KerrSchild.yaml
  tests/InputFiles/Poisson/Lorentzian.yaml
  tests/InputFiles/Poisson/ProductOfSinusoids1D.yaml
  tests/InputFiles/Poisson/ProductOfSinusoids2D.yaml
  tests/InputFiles/Poisson/ProductOfSinusoids3D.yaml
  tests/InputFiles/Punctures/MultiplePunctures.yaml
  tests/InputFiles/ScalarWave/PlaneWave1D.yaml
  tests/InputFiles/ScalarWave/PlaneWave1DEventsAndTriggersExample.yaml
  tests/InputFiles/ScalarWave/PlaneWave1DObserveExample.yaml
  tests/InputFiles/ScalarWave/PlaneWave2D.yaml
  tests/InputFiles/ScalarWave/PlaneWave3D.yaml
  tests/InputFiles/Xcts/BinaryBlackHole.yaml
  tests/InputFiles/Xcts/HeadOnBns.yaml
  tests/InputFiles/Xcts/KerrSchild.yaml
  tests/InputFiles/Xcts/TovStar.yaml
  tests/Unit/ParallelAlgorithms/Amr/Events/Test_RefineMesh.cpp
  tests/Unit/ParallelAlgorithms/Amr/Policies/Test_EnforcePolicies.cpp
  tests/Unit/ParallelAlgorithms/Amr/Policies/Test_Limits.cpp
  tests/Unit/ParallelAlgorithms/Amr/Policies/Test_Policies.cpp
Labels: bugfix

#6357 TransformVolumeData.py: support instance methods as kernels
  src/Visualization/Python/TransformVolumeData.py
  tests/Unit/Visualization/Python/Test_TransformVolumeData.py
Labels: cli/pybindings

#6366 Bind PN BinaryTrajectories in Python
  tests/Unit/ControlSystem/Systems/Test_Expansion.cpp
  tests/Unit/ControlSystem/Systems/Test_RotScaleTrans.cpp
  tests/Unit/ControlSystem/Systems/Test_Rotation.cpp
  tests/Unit/ControlSystem/Systems/Test_Translation.cpp
  tests/Unit/Helpers/ControlSystem/SystemHelpers.hpp
  tests/Unit/Helpers/PointwiseFunctions/PostNewtonian/BinaryTrajectories.cpp
  tests/Unit/Helpers/PointwiseFunctions/PostNewtonian/BinaryTrajectories.hpp
  tests/Unit/Helpers/PointwiseFunctions/PostNewtonian/CMakeLists.txt
  tests/Unit/Helpers/PointwiseFunctions/PostNewtonian/Python/Bindings.cpp
  tests/Unit/Helpers/PointwiseFunctions/PostNewtonian/Python/CMakeLists.txt
  tests/Unit/Helpers/PointwiseFunctions/PostNewtonian/Python/__init__.py
  tests/Unit/Helpers/Tests/PointwiseFunctions/PostNewtonian/BinaryTrajectories.py
  tests/Unit/Helpers/Tests/PointwiseFunctions/PostNewtonian/CMakeLists.txt
  tests/Unit/Helpers/Tests/PointwiseFunctions/PostNewtonian/Test_BinaryTrajectories.cpp
  tests/Unit/Helpers/Tests/PointwiseFunctions/PostNewtonian/Test_BinaryTrajectories.py
  tests/Unit/Visualization/Python/Test_PlotTrajectories.py
  tests/support/Pipelines/Bbh/Test_EccentricityControl.py
Labels: cli/pybindings

#6379 Update directory structure of ID parameter control
  support/Pipelines/Bbh/ControlId.py
  support/Pipelines/Bbh/InitialData.py
  tests/support/Pipelines/Bbh/Test_InitialData.py
Labels: cli/pybindings

#6380 TransformVol.py: add start, stop, stride
  src/IO/H5/Python/IterElements.py
  src/Visualization/Python/TransformVolumeData.py
  tests/Unit/Visualization/Python/Test_TransformVolumeData.py
Labels: cli/pybindings

#6381 Fix machine config files
  support/Machines/CaltechHpc.yaml
  support/Machines/Mbot.yaml
  support/Machines/Ocean.yaml
  support/Machines/Oscar.yaml
  support/Machines/Perlmutter.yaml
  support/Machines/Sonic.yaml
  support/Python/Machines.py
  tests/support/Python/Test_Machines.py
Labels: bugfix

#6378 Damp initial iterations of Broyden's method used in ID parameter control
  support/Pipelines/Bbh/ControlId.py
Labels: cli/pybindings
