Repository sxs-collaboration/spectre, pull requests merged in 2024-12, with the labels that each got.

#6388 Add an input file for KG CCE
  tests/InputFiles/Cce/KleinGordonCharacteristicExtract.yaml
Labels: small

#6390 Constraint damping gaussian's amplitudes are exchanged
  support/Pipelines/Bbh/Inspiral.yaml
Labels: small, bugfix

#6395 Fix shape map loaded from file
  src/Domain/Creators/TimeDependentOptions/ShapeMap.cpp
  src/Domain/Creators/TimeDependentOptions/ShapeMap.hpp
  tests/Unit/Domain/Creators/TimeDependentOptions/Test_ShapeMap.cpp
Labels: bugfix

#6391 Add acceleration terms to iterations
  src/Evolution/Systems/CurvedScalarWave/Worldtube/ElementActions/IteratePunctureField.hpp
  src/Evolution/Systems/CurvedScalarWave/Worldtube/SingletonActions/CMakeLists.txt
  src/Evolution/Systems/CurvedScalarWave/Worldtube/SingletonActions/IterateAccelerationTerms.cpp
  src/Evolution/Systems/CurvedScalarWave/Worldtube/SingletonActions/IterateAccelerationTerms.hpp
  src/Evolution/Systems/CurvedScalarWave/Worldtube/SingletonActions/SendAccelerationTerms.hpp
  src/Evolution/Systems/CurvedScalarWave/Worldtube/SingletonChare.hpp
  src/Evolution/Systems/CurvedScalarWave/Worldtube/Tags.hpp
  tests/Unit/Evolution/Systems/CurvedScalarWave/Worldtube/CMakeLists.txt
  tests/Unit/Evolution/Systems/CurvedScalarWave/Worldtube/ElementActions/Test_Iterations.cpp
  tests/Unit/Evolution/Systems/CurvedScalarWave/Worldtube/ElementActions/Test_SendToWorldtube.cpp
  tests/Unit/Evolution/Systems/CurvedScalarWave/Worldtube/SelfForce.py
  tests/Unit/Evolution/Systems/CurvedScalarWave/Worldtube/SingletonActions/Test_IterateAccelerationTerms.cpp
  tests/Unit/Evolution/Systems/CurvedScalarWave/Worldtube/Test_Tags.cpp
Labels: auto-merge

#6409 Add `InsideHorizon` trigger for worldtube excision
  src/Evolution/Systems/CurvedScalarWave/Worldtube/CMakeLists.txt
  src/Evolution/Systems/CurvedScalarWave/Worldtube/Triggers/CMakeLists.txt
  src/Evolution/Systems/CurvedScalarWave/Worldtube/Triggers/InsideHorizon.cpp
  src/Evolution/Systems/CurvedScalarWave/Worldtube/Triggers/InsideHorizon.hpp
  tests/Unit/Evolution/Systems/CurvedScalarWave/Worldtube/CMakeLists.txt
  tests/Unit/Evolution/Systems/CurvedScalarWave/Worldtube/Test_Triggers.cpp
Labels: auto-merge

#6398 Update ReduceCceWorldtube with new features
  .github/workflows/DeployStaticExecutables.yaml
  cmake/AddInputFileTests.cmake
  containers/Dockerfile.buildenv
  docs/Tutorials/CCE.md
  src/Evolution/Systems/Cce/OptionTags.hpp
  src/Evolution/Systems/Cce/WorldtubeBufferUpdater.hpp
  src/Evolution/Systems/Cce/WorldtubeDataManager.cpp
  src/Evolution/Systems/Cce/WorldtubeDataManager.hpp
  src/Executables/CMakeLists.txt
  src/Executables/PreprocessCceWorldtube/CMakeLists.txt
  src/Executables/PreprocessCceWorldtube/PreprocessCceWorldtube.cpp
  src/Executables/ReduceCceWorldtube/ReduceCceWorldtube.cpp
  tests/InputFiles/PreprocessCceWorldtube/PreprocessCceWorldtube.yaml
  tests/InputFiles/ReduceCceWorldtube/ReduceCceWorldtube.yaml
  tests/Unit/Evolution/Systems/Cce/Test_WorldtubeData.cpp
  tests/Unit/Executables/CMakeLists.txt
  tests/Unit/Executables/Test_PreprocessCceWorldtube.cpp
Labels: auto-merge

#6416 Make small tweaks to CCE tutorial
  docs/Tutorials/CCE.md
Labels: documentation

#6417 Couple quick fixes to allow static execs to build after Release
  containers/Dockerfile.buildenv
  src/Domain/Structure/SegmentId.cpp
Labels: priority, bugfix

#6423 Fix yaml-cpp git tag
  cmake/SetupYamlCpp.cmake
Labels: bugfix, build system
