Repository sxs-collaboration/spectre, pull requests merged in 2024-04, with the labels that each got.

#5882 Fix a bug in Equilibrium3D EoS
  src/PointwiseFunctions/Hydro/EquationsOfState/EquationOfState.hpp
  src/PointwiseFunctions/Hydro/EquationsOfState/Equilibrium3D.cpp
  tests/Unit/PointwiseFunctions/Hydro/EquationsOfState/Test_Equilibrium3D.cpp
Labels: bugfix

#5908 Fix workflow to deploy release container
  .github/workflows/DemoContainer.yaml
Labels: bugfix, ci/cd

#5759 Add IMEX tutorial
  docs/References.bib
  docs/Tutorials/Imex.md
  docs/Tutorials/Tutorials.md
  src/Evolution/Imex/Protocols/ImexSystem.hpp
  src/Evolution/Imex/Protocols/ImplicitSector.hpp
  tests/Unit/Evolution/Imex/Test_SolveImplicitSector.cpp
  tests/Unit/Helpers/Evolution/Imex/DoImplicitStepSector.hpp
Labels: documentation

#5858 Add an observer for tracking the size of DataBox items
  src/DataStructures/DataBox/DataBox.hpp
  src/ParallelAlgorithms/Events/CMakeLists.txt
  src/ParallelAlgorithms/Events/ObserveDataBox.cpp
  src/ParallelAlgorithms/Events/ObserveDataBox.hpp
  tests/Unit/DataStructures/DataBox/Test_DataBox.cpp
Labels: auto-merge

#5917 Clarify use of 'multiple' options in some CLI functions
  src/IO/H5/Python/DeleteSubfiles.py
  src/IO/H5/Python/ExtractDatFromH5.py
  src/Visualization/Python/InterpolateToMesh.py
  src/Visualization/Python/PlotDatFile.py
  src/Visualization/Python/PlotPowerMonitors.py
  src/Visualization/Python/TransformVolumeData.py
  support/Python/Schedule.py
Labels: cli/pybindings

#5925 Fix rebase issue from #5877
  tests/Unit/Evolution/Particles/MonteCarlo/Test_Scattering.cpp
Labels: priority, bugfix

#5624 Add a reflective boundary condition
  docs/References.bib
  src/Evolution/Systems/GrMhd/ValenciaDivClean/BoundaryConditions/CMakeLists.txt
  src/Evolution/Systems/GrMhd/ValenciaDivClean/BoundaryConditions/Factory.hpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/BoundaryConditions/Reflective.cpp
  src/Evolution/Systems/GrMhd/ValenciaDivClean/BoundaryConditions/Reflective.hpp
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/BoundaryConditions/Reflective.py
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/BoundaryConditions/Test_Reflective.cpp
  tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/CMakeLists.txt
Labels: auto-merge

#5930 Document extract-dat to standard output
  src/IO/H5/Python/ExtractDatFromH5.py
Labels: documentation, cli/pybindings

#5914 Fix race condition when updating FoTs
  src/Domain/FunctionsOfTime/PiecewisePolynomial.cpp
  src/Domain/FunctionsOfTime/PiecewisePolynomial.hpp
  src/Domain/FunctionsOfTime/QuaternionFunctionOfTime.cpp
  src/Domain/FunctionsOfTime/QuaternionFunctionOfTime.hpp
  tests/Unit/Domain/FunctionsOfTime/PiecewisePolynomial.serializations
  tests/Unit/Domain/FunctionsOfTime/QuaternionFunctionOfTime.serializations
  tests/Unit/Domain/FunctionsOfTime/Test_PiecewisePolynomial.cpp
  tests/Unit/Domain/FunctionsOfTime/Test_QuaternionFunctionOfTime.cpp
Labels: bugfix

#5924 Normalize subfile path in H5 lib
  src/IO/Exporter/Exporter.cpp
  src/IO/Exporter/Exporter.hpp
  src/IO/H5/File.hpp
  src/IO/H5/Python/CombineH5.py
  src/IO/H5/Python/ExtendConnectivityData.py
  src/Visualization/Python/OpenVolfiles.py
  src/Visualization/Python/Render1D.py
  src/Visualization/Python/TransformVolumeData.py
  tests/Unit/IO/H5/Test_Dat.cpp
  tests/Unit/IO/H5/Test_VolumeData.cpp
Labels: auto-merge

#5944 Change translation control to work like SpEC
  src/ControlSystem/ControlErrors/Translation.hpp
  tests/Unit/ControlSystem/ControlErrors/Test_Translation.cpp
Labels: auto-merge

#5919 Bind horizon finder in Python
  src/IO/Exporter/Python/__init__.py
  src/IO/H5/Python/File.cpp
  src/NumericalAlgorithms/SphericalHarmonics/CMakeLists.txt
  src/NumericalAlgorithms/SphericalHarmonics/Python/Bindings.cpp
  src/NumericalAlgorithms/SphericalHarmonics/Python/CMakeLists.txt
  src/NumericalAlgorithms/SphericalHarmonics/Python/Strahlkorper.cpp
  src/NumericalAlgorithms/SphericalHarmonics/Python/Strahlkorper.hpp
  src/NumericalAlgorithms/SphericalHarmonics/Python/StrahlkorperFunctions.cpp
  src/NumericalAlgorithms/SphericalHarmonics/Python/StrahlkorperFunctions.hpp
  src/NumericalAlgorithms/SphericalHarmonics/Python/__init__.py
  src/NumericalAlgorithms/SphericalHarmonics/StrahlkorperFunctions.cpp
  src/NumericalAlgorithms/SphericalHarmonics/StrahlkorperFunctions.hpp
  src/ParallelAlgorithms/ApparentHorizonFinder/CMakeLists.txt
  src/ParallelAlgorithms/ApparentHorizonFinder/Python/Bindings.cpp
  src/ParallelAlgorithms/ApparentHorizonFinder/Python/CMakeLists.txt
  src/ParallelAlgorithms/ApparentHorizonFinder/Python/__init__.py
  src/Visualization/Python/OpenVolfiles.py
  support/Pipelines/Bbh/CMakeLists.txt
  support/Pipelines/Bbh/FindHorizon.py
  support/Pipelines/Bbh/__init__.py
  tests/Unit/IO/Exporter/Python/Test_InterpolateToPoints.py
  tests/Unit/NumericalAlgorithms/SphericalHarmonics/CMakeLists.txt
  tests/Unit/NumericalAlgorithms/SphericalHarmonics/Python/CMakeLists.txt
  tests/Unit/NumericalAlgorithms/SphericalHarmonics/Python/Test_Strahlkorper.py
  tests/Unit/NumericalAlgorithms/SphericalHarmonics/Test_StrahlkorperFunctions.cpp
  tests/Unit/ParallelAlgorithms/ApparentHorizonFinder/CMakeLists.txt
  tests/Unit/ParallelAlgorithms/ApparentHorizonFinder/Python/CMakeLists.txt
  tests/Unit/ParallelAlgorithms/ApparentHorizonFinder/Python/Test_FastFlow.py
  tests/support/Pipelines/Bbh/CMakeLists.txt
  tests/support/Pipelines/Bbh/Test_FindHorizon.py
Labels: cli/pybindings

#5954 Log scale in PlotSizeControl.py
  src/Visualization/Python/PlotSizeControl.py
Labels: auto-merge, cli/pybindings
