Repository sxs-collaboration/spectre, pull requests merged in 2024-10, with the labels that each got.

#6311 Add Sonic HPC
  docs/Installation/InstallationOnClusters.md
  support/Environments/sonic.sh
  support/Machines/Sonic.yaml
  support/SubmitScripts/Sonic.sh
Labels: clusters

#6318 Fix a typo in docs
  src/ParallelAlgorithms/NonlinearSolver/NewtonRaphson/LineSearch.hpp
Labels: documentation, bugfix, auto-merge

#6317 Render Domain.py: specify background color
  src/Visualization/Python/Render3D/Domain.py
  support/Python/Logging.py
  support/Python/__main__.py
Labels: cli/pybindings

#6325 Cmake `yaml-cpp` package name fix
  cmake/SetupYamlCpp.cmake
Labels: bugfix

#6330 Update installation instructions
  README.md
  cmake/SetupYamlCpp.cmake
  docs/Installation/Installation.md
  docs/Installation/InstallationOnAppleSilicon.md
Labels: documentation

#6336 Add PiecewisePolynomial, QuaternionFunctionofTime, and Serialize Pybindings
  src/Domain/Python/FunctionsOfTime.cpp
  tests/Unit/Domain/Python/Test_FunctionsOfTime.py
Labels: cli/pybindings

#6332 Update gallery with BBH paper, link from front page
  README.md
  docs/Gallery.md
  docs/Main.md
  docs/References.bib
  src/Evolution/Particles/MonteCarlo/CouplingTermsForPropagation.hpp
  src/Evolution/Particles/MonteCarlo/Scattering.hpp
  src/Evolution/Particles/MonteCarlo/TemplatedLocalFunctions.hpp
Labels: documentation

#6295 Single iteration of eccentricity control reduction
  support/Pipelines/Bbh/CMakeLists.txt
  support/Pipelines/Bbh/EccentricityControl.py
  support/Pipelines/Bbh/Inspiral.py
  support/Pipelines/Bbh/Inspiral.yaml
  tests/support/Pipelines/Bbh/CMakeLists.txt
  tests/support/Pipelines/Bbh/Test_EccentricityControl.py
Labels: cli/pybindings

#6334 Allow multiple callbacks on same component
  src/Parallel/Callback.hpp
  src/Parallel/GlobalCache.hpp
  src/Parallel/ParallelComponentHelpers.hpp
  tests/Unit/Parallel/Test_Callback.cpp
  tests/Unit/Parallel/Test_GlobalCache.ci
  tests/Unit/Parallel/Test_GlobalCache.cpp
  tests/Unit/Parallel/Test_GlobalCache.hpp
Labels: bugfix
