Repository sxs-collaboration/spectre, pull requests merged in 2025-05, with the labels that each got.

#6616 Fix typo in latex equation of loehner_smoothness_indicator
  src/ParallelAlgorithms/Amr/Criteria/Loehner.hpp
Labels: small

#6612 Add variable-order support to the Adams time steppers
  src/Time/TimeSteppers/AdamsBashforth.cpp
  src/Time/TimeSteppers/AdamsBashforth.hpp
  src/Time/TimeSteppers/AdamsMoultonPc.cpp
  src/Time/TimeSteppers/AdamsMoultonPc.hpp
  src/Time/TimeSteppers/TimeStepper.hpp
  tests/Unit/Helpers/Time/TimeSteppers/LtsHelpers.cpp
  tests/Unit/Helpers/Time/TimeSteppers/LtsHelpers.hpp
  tests/Unit/Time/TimeSteppers/Test_AdamsBashforth.cpp
  tests/Unit/Time/TimeSteppers/Test_AdamsMoultonPc.cpp
Labels: auto-merge

#6577 Fix CI Py3.8 test
  .github/workflows/Tests.yaml
Labels: ci/cd

#6628 Add missing option for skew map on input file
  support/Pipelines/Bbh/Inspiral.yaml
Labels: small, bugfix

#6184 Add Urania machine and validate flag to scheduler
  support/Environments/urania.sh
  support/Machines/Urania.yaml
  support/Python/Schedule.py
  support/SubmitScripts/Urania.sh
  tests/support/Python/Test_Schedule.py
Labels: cli/pybindings, clusters

#6633 Add Viper machine
  support/Environments/viper.sh
  support/Machines/Viper.yaml
  support/SubmitScripts/Viper.sh
Labels: dependent

#6652 Fix bug in AH finder initial guess
  src/ParallelAlgorithms/ApparentHorizonFinder/Callbacks/ErrorOnFailedApparentHorizon.hpp
  src/ParallelAlgorithms/ApparentHorizonFinder/Callbacks/FindApparentHorizon.hpp
  src/ParallelAlgorithms/ApparentHorizonFinder/Callbacks/IgnoreFailedApparentHorizon.hpp
  src/ParallelAlgorithms/ApparentHorizonFinder/InterpolationTarget.hpp
  src/ParallelAlgorithms/Interpolation/InterpolationTargetDetail.hpp
  src/ParallelAlgorithms/Interpolation/Protocols/ComputeTargetPoints.hpp
  tests/Unit/ParallelAlgorithms/ApparentHorizonFinder/Test_ApparentHorizonFinder.cpp
Labels: bugfix
