Repository sxs-collaboration/spectre, pull requests merged in 2025-08, with the labels that each got.

#6798 Change ringdown gauge parameters to match inspiral
  support/Pipelines/Bbh/Ringdown.yaml
Labels: small, bugfix

#6815 Add BCO Python Binding
  src/Domain/Creators/Python/BinaryCompactObject.cpp
  src/Domain/Creators/Python/BinaryCompactObject.hpp
  src/Domain/Creators/Python/Bindings.cpp
  src/Domain/Creators/Python/CMakeLists.txt
  tests/Unit/Domain/Creators/Python/CMakeLists.txt
  tests/Unit/Domain/Creators/Python/Test_BinaryCompactObject.py
Labels: cli/pybindings

#6679 Add smoothstep_deriv function
  src/ControlSystem/Controller.cpp
  src/PointwiseFunctions/ScalarTensor/RampUpFunction.cpp
  src/PointwiseFunctions/ScalarTensor/RampUpFunction.hpp
  src/PointwiseFunctions/ScalarTensor/SourceTags.hpp
  src/Utilities/ConstantExpressions.hpp
  src/Utilities/Math.hpp
  tests/InputFiles/ScalarTensor/KerrSchildSphericalHarmonic.yaml
  tests/Unit/PointwiseFunctions/ScalarTensor/Test_RampUpFunction.cpp
  tests/Unit/PointwiseFunctions/ScalarTensor/Test_SourceTags.cpp
  tests/Unit/Utilities/Test_ConstantExpressions.cpp
  tests/Unit/Utilities/Test_Math.cpp
Labels: small
