Repository sxs-collaboration/spectre, pull requests merged in 2025-06, with the labels that each got.

#6638 Add callback to dump scalar variables together with metric variables on worldtube
  src/Evolution/Executables/ScalarTensor/CMakeLists.txt
  src/Evolution/Executables/ScalarTensor/EvolveScalarTensorSingleBlackHole.hpp
  src/Evolution/Systems/Cce/BoundaryData.cpp
  src/Evolution/Systems/Cce/BoundaryData.hpp
  src/Evolution/Systems/Cce/Callbacks/DumpBondiSachsOnWorldtube.hpp
  src/Evolution/Systems/Cce/WorldtubeModeRecorder.cpp
  tests/InputFiles/ScalarTensor/KerrSchildSphericalHarmonic.yaml
  tests/Unit/Evolution/Systems/Cce/BoundaryData.py
  tests/Unit/Evolution/Systems/Cce/Test_BoundaryData.cpp
  tests/Unit/Evolution/Systems/Cce/Test_DumpBondiSachsOnWorldtube.cpp
Labels: auto-merge

#6683 Fix a Py test on macOS CI
  src/Visualization/Python/PlotPowerMonitors.py
Labels: bugfix, ci/cd

#6686 Change polytropic to tab EOS for CCSN initialize
  src/PointwiseFunctions/AnalyticData/GrMhd/CcsnCollapse.cpp
  src/PointwiseFunctions/AnalyticData/GrMhd/CcsnCollapse.hpp
  tests/Unit/PointwiseFunctions/AnalyticData/GrMhd/Test_CcsnCollapse.cpp
Labels: enhancement

#6639 Change background GR variable in MC to match GhGrMhd
  src/Evolution/Executables/RadiationTransport/MonteCarlo/EvolveMonteCarlo.hpp
  src/Evolution/Particles/MonteCarlo/Actions/InitializeMonteCarlo.hpp
  src/Evolution/Particles/MonteCarlo/Actions/TimeStepActions.hpp
  src/Evolution/Particles/MonteCarlo/CMakeLists.txt
  src/Evolution/Particles/MonteCarlo/SwapGrTags.cpp
  src/Evolution/Particles/MonteCarlo/SwapGrTags.hpp
  src/Evolution/Particles/MonteCarlo/System.hpp
  src/Evolution/Particles/MonteCarlo/TakeTimeStep.tpp
  tests/Unit/Evolution/Particles/MonteCarlo/CMakeLists.txt
  tests/Unit/Evolution/Particles/MonteCarlo/Test_InitializeAction.cpp
  tests/Unit/Evolution/Particles/MonteCarlo/Test_SwapGrTags.cpp
  tests/Unit/Evolution/Particles/MonteCarlo/Test_TimeStepAction.cpp
Labels: auto-merge

#6691 Add 1D Cartoon Expansion Calculation
  src/PointwiseFunctions/GeneralRelativity/GeneralizedHarmonic/CMakeLists.txt
  src/PointwiseFunctions/GeneralRelativity/GeneralizedHarmonic/Expansion1D.cpp
  src/PointwiseFunctions/GeneralRelativity/GeneralizedHarmonic/Expansion1D.hpp
  tests/Unit/PointwiseFunctions/GeneralRelativity/Surfaces/CMakeLists.txt
  tests/Unit/PointwiseFunctions/GeneralRelativity/Surfaces/Test_GrSurfaces.cpp
Labels: new feature, auto-merge

#6697 Add \Psi_2 in CCE volume
  src/Evolution/Systems/Cce/Events/ObserveFields.hpp
  src/Evolution/Systems/Cce/LinearOperators.hpp
  src/Evolution/Systems/Cce/NewmanPenrose.cpp
  src/Evolution/Systems/Cce/NewmanPenrose.hpp
  src/Evolution/Systems/Cce/SwshDerivatives.hpp
  tests/InputFiles/Cce/AnalyticTestVolumeNewmanPenroseSpinCoefficientsRhoGammaMu.py
  tests/InputFiles/Cce/AnalyticTestVolumeUtils.py
  tests/InputFiles/Cce/AnalyticTestVolumeWeylPsi2.py
  tests/InputFiles/Cce/AnalyticTestVolumeWeylScalars.yaml
  tests/Unit/Evolution/Systems/Cce/Events/Test_ObserveFields.cpp
  tests/Unit/Evolution/Systems/Cce/NewmanPenrose.py
  tests/Unit/Evolution/Systems/Cce/Test_NewmanPenrose.cpp
  tests/Unit/Evolution/Systems/Cce/Test_PreSwshDerivatives.cpp
  tests/Unit/Evolution/Systems/Cce/Test_SwshDerivatives.cpp
Labels: auto-merge
