Repository sxs-collaboration/spectre, pull requests merged in 2025-02, with the labels that each got.

#6470 Ignore projectile and CMakeUserPreset.json
  .gitignore
Labels: small

#6445 BBH pipeline: store target params, continue from evolution data for PBJ
  support/Pipelines/Bbh/ControlId.py
  support/Pipelines/Bbh/EccentricityControl.py
  support/Pipelines/Bbh/InitialData.py
  support/Pipelines/Bbh/InitialData.yaml
  support/Pipelines/Bbh/Inspiral.py
  support/Pipelines/Bbh/Inspiral.yaml
  support/Pipelines/Bbh/PostprocessId.py
  support/Pipelines/Bbh/Ringdown.py
  support/Pipelines/Bbh/Ringdown.yaml
  support/Pipelines/EccentricityControl/EccentricityControlParams.py
  support/Pipelines/EccentricityControl/InitialOrbitalParameters.py
  support/Python/Schedule.py
  tests/support/Pipelines/Bbh/Test_EccentricityControl.py
  tests/support/Pipelines/Bbh/Test_InitialData.py
  tests/support/Pipelines/Bbh/Test_Inspiral.py
  tests/support/Pipelines/Bbh/Test_PostprocessId.py
  tests/support/Pipelines/Bbh/Test_Ringdown.py
  tests/support/Pipelines/EccentricityControl/Test_EccentricityControlParams.py
  tests/support/Pipelines/EccentricityControl/Test_InitialOrbitalParameters.py
  tools/Status/Dashboard.py
Labels: cli/pybindings

#6468 BBH pipeline: write eccentricity params to file, add CLI to compute params & plot
  src/Visualization/Python/CMakeLists.txt
  src/Visualization/Python/PlotEccentricityControl.py
  src/Visualization/Python/__init__.py
  support/Pipelines/Bbh/EccentricityControl.py
  support/Pipelines/Bbh/Inspiral.yaml
  support/Pipelines/EccentricityControl/EccentricityControlParams.py
  support/Python/CMakeLists.txt
  support/Python/Schedule.py
  support/Python/Yaml.py
  support/Python/__main__.py
  tests/Unit/Visualization/Python/CMakeLists.txt
  tests/Unit/Visualization/Python/Test_PlotEccentricityControl.py
  tests/support/Pipelines/Bbh/Test_Inspiral.py
  tests/support/Pipelines/EccentricityControl/Test_EccentricityControlParams.py
Labels: cli/pybindings

#6473 Add ability to list files to copy in input file tests
  cmake/AddInputFileTests.cmake
  cmake/RunInputFileTest.sh
Labels: build system

#6488 Use match time as initial time in Ringdown pipeline
  support/Pipelines/Bbh/Ringdown.yaml
Labels: small, cli/pybindings

#5750 Add mbot installation shell script
  support/Environments/setup/mbot_install.sh
  tools/FileTestDefs.sh
Labels: clusters

#6496 Link jemalloc only into executables
  cmake/PrintUsefulCMakeInfo.cmake
  cmake/SetupJemalloc.cmake
  cmake/SpectreAddLibraries.cmake
  cmake/SpectreSetupPythonPackage.cmake
  docs/Tutorials/Python.md
Labels: build system

#6498 Update broken libxsmm URL, pin a docker version
  .github/workflows/BuildDockerContainer.yaml
  cmake/FindLIBXSMM.cmake
  containers/Dockerfile.buildenv
  docs/Installation/Installation.md
  docs/Installation/InstallationOnAppleSilicon.md
  support/Environments/setup/anvil_gcc.sh
  support/Environments/setup/frontera_gcc.sh
  support/Environments/setup/mbot_install.sh
Labels: bugfix, ci/cd

#6489 Fix some BNS ID docs
  src/Elliptic/Systems/BnsInitialData/Equations.hpp
  src/Elliptic/Systems/BnsInitialData/FirstOrderSystem.hpp
  src/Elliptic/Systems/BnsInitialData/Tags.hpp
  src/PointwiseFunctions/Hydro/InitialData/IrrotationalBns.hpp
Labels: documentation, bugfix
