Repository sxs-collaboration/spectre, pull requests merged in 2025-07, with the labels that each got.

#6744 Fix KappaLimiting documentation
  src/Evolution/VariableFixing/FixToAtmosphere.hpp
Labels: small

#6738 Add Wigner 3j symbols.
  external/CMakeLists.txt
  external/slatec/CMakeLists.txt
  external/slatec/LICENSE.txt
  external/slatec/README.txt
  external/slatec/drc3jj.f
  src/NumericalAlgorithms/SphericalHarmonics/CMakeLists.txt
  src/NumericalAlgorithms/SphericalHarmonics/WignerThreeJ.cpp
  src/NumericalAlgorithms/SphericalHarmonics/WignerThreeJ.hpp
  tests/Unit/NumericalAlgorithms/SphericalHarmonics/CMakeLists.txt
  tests/Unit/NumericalAlgorithms/SphericalHarmonics/Test_WignerThreeJ.cpp
Labels: new feature

#6753 Support linking device code in static libraries
  .github/workflows/Tests.yaml
  cmake/EnableWarnings.cmake
  cmake/SetupCxxFlags.cmake
  cmake/SetupKokkos.cmake
  docs/DevGuide/GpuSupport.md
  src/Parallel/Main.hpp
  src/Utilities/StaticCache.hpp
  tests/Unit/Helpers/DataStructures/CMakeLists.txt
  tests/Unit/Utilities/CMakeLists.txt
  tests/Unit/Utilities/Kokkos/CMakeLists.txt
  tests/Unit/Utilities/Kokkos/TestKernel.cpp
  tests/Unit/Utilities/Kokkos/TestKernel.hpp
  tests/Unit/Utilities/Kokkos/Test_Kokkos.cpp
  tools/CheckFiles.sh
  tools/WrapExecutableLinker.sh
Labels: build system

#6774 Add a Ccz4 wrapper class around gr solutions
  src/PointwiseFunctions/AnalyticSolutions/GeneralRelativity/CMakeLists.txt
  src/PointwiseFunctions/AnalyticSolutions/GeneralRelativity/Ccz4WrappedGr.cpp
  src/PointwiseFunctions/AnalyticSolutions/GeneralRelativity/Ccz4WrappedGr.hpp
  src/PointwiseFunctions/AnalyticSolutions/GeneralRelativity/Ccz4WrappedGr.tpp
  tests/Unit/PointwiseFunctions/AnalyticSolutions/GeneralRelativity/CMakeLists.txt
  tests/Unit/PointwiseFunctions/AnalyticSolutions/GeneralRelativity/Test_Ccz4WrappedGr.cpp
Labels: auto-merge
