Repository sxs-collaboration/spectre, pull requests merged in 2025-01, with the labels that each got.

#6432 Speed up `list_observation_ids()`
  src/IO/H5/VolumeData.cpp
Labels: small

#6406 Eccentricity Reduction Automation
  support/Pipelines/Bbh/EccentricityControl.py
  support/Pipelines/Bbh/InitialData.py
  support/Pipelines/Bbh/InitialData.yaml
  support/Pipelines/Bbh/Inspiral.py
  support/Pipelines/Bbh/Inspiral.yaml
  support/Pipelines/Bbh/PostprocessId.py
  support/Python/DirectoryStructure.py
  tests/support/Pipelines/Bbh/Test_EccentricityControl.py
  tests/support/Pipelines/Bbh/Test_InitialData.py
  tests/support/Pipelines/Bbh/Test_Inspiral.py
  tests/support/Python/Test_DirectoryStructure.py
Labels: cli/pybindings

#6333 Use SpEC's eccentricity control
  cmake/SetupSpec.cmake
  support/Pipelines/Bbh/EccentricityControl.py
  support/Pipelines/Bbh/Inspiral.yaml
  support/Pipelines/Bbh/__init__.py
  support/Pipelines/EccentricityControl/CMakeLists.txt
  support/Pipelines/EccentricityControl/EccentricityControl.py
  support/Pipelines/EccentricityControl/EccentricityControlParams.py
  support/Pipelines/EccentricityControl/__init__.py
  support/Python/__main__.py
  tests/support/Pipelines/Bbh/CMakeLists.txt
  tests/support/Pipelines/Bbh/Test_EccentricityControl.py
  tests/support/Pipelines/Bbh/Test_Inspiral.py
  tests/support/Pipelines/EccentricityControl/CMakeLists.txt
  tests/support/Pipelines/EccentricityControl/Test_EccentricityControl.py
  tests/support/Pipelines/EccentricityControl/Test_EccentricityControlParams.py
  tests/tools/Test_Status.py
  tools/Status/Dashboard.py
  tools/Status/ExecutableStatus/CharacteristicExtract.py
  tools/Status/ExecutableStatus/EvolveGhBinaryBlackHole.py
  tools/Status/ExecutableStatus/ExecutableStatus.py
  tools/Status/ExecutableStatus/SolveXcts.py
  tools/Status/Status.py
Labels: cli/pybindings

#6443 Fix CI for Python 3.9
  .github/workflows/Tests.yaml
Labels: bugfix, ci/cd

#6431 Clean up ringdown script
  src/Evolution/Ringdown/Python/Bindings.cpp
  src/Evolution/Ringdown/Python/CMakeLists.txt
  src/Evolution/Ringdown/Python/ComputeAhCCoefsInRingdownDistortedFrame.py
  src/Evolution/Ringdown/Python/FunctionsOfTimeFromVolume.py
  src/Evolution/Ringdown/StrahlkorperCoefsInRingdownDistortedFrame.cpp
  src/Evolution/Ringdown/StrahlkorperCoefsInRingdownDistortedFrame.hpp
  src/IO/H5/Python/CMakeLists.txt
  src/IO/H5/Python/FunctionsOfTimeFromVolume.py
  support/Pipelines/Bbh/Ringdown.py
  support/Pipelines/Bbh/Ringdown.yaml
  tests/Unit/Evolution/Ringdown/Python/Test_ComputeAhCCoefsInRingdownDistortedFrame.py
  tests/Unit/IO/H5/Python/CMakeLists.txt
  tests/Unit/IO/H5/Python/Test_FunctionsOfTimeFromVolume.py
Labels: cli/pybindings

#6442 Status CLI: fix speed measurement
  support/Pipelines/EccentricityControl/EccentricityControlParams.py
  tests/tools/Test_Status.py
  tools/Status/ExecutableStatus/ExecutableStatus.py
Labels: cli/pybindings

#6441 Fix compiling StaticCache with nvcc
  src/Domain/Creators/TimeDependentOptions/ShapeMap.cpp
  src/Utilities/StaticCache.hpp
Labels: bugfix

#6452 Fix running on CaltechHPC: disable ParaView env vars
  cmake/SpectreSetupPythonPackage.cmake
Labels: bugfix, clusters

#6459 Fix bug in PreprocessCceWorldtube
  docs/Tutorials/CCE.md
  src/Evolution/Systems/Cce/WorldtubeBufferUpdater.cpp
  src/Evolution/Systems/Cce/WorldtubeBufferUpdater.hpp
  src/Executables/PreprocessCceWorldtube/PreprocessCceWorldtube.cpp
  tests/InputFiles/PreprocessCceWorldtube/PreprocessCceWorldtube.yaml
  tests/Unit/Evolution/Systems/Cce/Test_WorldtubeData.cpp
  tests/Unit/Executables/Test_PreprocessCceWorldtube.cpp
  tests/Unit/Helpers/Evolution/Systems/Cce/BoundaryTestHelpers.hpp
  tests/Unit/Helpers/Evolution/Systems/Cce/WriteToWorldtubeH5.hpp
Labels: bugfix

#6461 BBH pipeline: small ecc control fixes
  support/Pipelines/Bbh/EccentricityControl.py
Labels: bugfix

#6463 Status CLI / dashboard: handle pending jobs better, plot simulation time over calendar time
  src/Parallel/PhaseControl/CheckpointAndExitAfterWallclock.hpp
  src/Utilities/CMakeLists.txt
  src/Utilities/UtcTime.cpp
  src/Utilities/UtcTime.hpp
  tools/Status/ExecutableStatus/EvolveGhBinaryBlackHole.py
  tools/Status/ExecutableStatus/ExecutableStatus.py
  tools/Status/Status.py
Labels: cli/pybindings
