Repository sxs-collaboration/spectre, pull requests merged in 2025-04, with the labels that each got.

#5480 Add calculation of $\Psi_1$ in the CCE volume
  src/Evolution/Systems/Cce/Events/ObserveFields.hpp
  src/Evolution/Systems/Cce/NewmanPenrose.cpp
  src/Evolution/Systems/Cce/NewmanPenrose.hpp
  tests/InputFiles/Cce/AnalyticTestVolumeWeylScalars.yaml
  tests/Unit/Evolution/Systems/Cce/Events/Test_ObserveFields.cpp
  tests/Unit/Evolution/Systems/Cce/NewmanPenrose.py
  tests/Unit/Evolution/Systems/Cce/Test_GaugeTransformBoundaryData.cpp
  tests/Unit/Evolution/Systems/Cce/Test_NewmanPenrose.cpp
  tests/Unit/Helpers/Evolution/Systems/Cce/VolumeTestHelpers.hpp
Labels: auto-merge

#6549 Refactor TimeDerivativeTerms for GhGrMHD
  src/Evolution/Systems/GrMhd/GhValenciaDivClean/TimeDerivativeTerms.hpp
Labels: small

#6490 BBH pipeline: set time bounds in ecc control
  support/Pipelines/Bbh/EccentricityControl.py
  support/Pipelines/Bbh/Inspiral.py
  support/Pipelines/Bbh/Inspiral.yaml
  support/Pipelines/EccentricityControl/EccentricityControlParams.py
  tools/Status/ExecutableStatus/EvolveGhBinaryBlackHole.py
Labels: cli/pybindings

#6578 Sort files before concatenating for eccentricity control
  support/Pipelines/EccentricityControl/EccentricityControlParams.py
Labels: small, bugfix

#6580 PySphericalHarmonics: instantiate another transform function
  src/Domain/Python/StrahlkorperTransformations.cpp
  tests/Unit/Domain/Python/Test_StrahlkorperTransformations.py
Labels: cli/pybindings

#6587 Fix macOS build on CI
  .github/workflows/Tests.yaml
Labels: ci/cd

#6591 Add Henry Huang to SpECTRE contributor list
  Metadata.yaml
Labels: small

#6596 Add evolution and parameter tags for the CCZ4 system
  src/Evolution/Systems/Ccz4/Tags.hpp
  src/Evolution/Systems/Ccz4/TagsDeclarations.hpp
  tests/Unit/Evolution/Systems/Ccz4/Test_Tags.cpp
Labels: small

#6597 Add more docs and fix typo in TimeDerivative.hpp/cpp in the CCZ4 system
  src/Evolution/Systems/Ccz4/TimeDerivative.cpp
  src/Evolution/Systems/Ccz4/TimeDerivative.hpp
Labels: small

#6604 Docfix ComputeBondiIntegrand<Tags::PoleOfIntegrand<Tags::BondiH>>
  src/Evolution/Systems/Cce/Equations.hpp
Labels: documentation, small

#6598 Generalize DerivLapse in the CCZ4 system to allow more tensor symmetry
  src/Evolution/Systems/Ccz4/DerivLapse.cpp
  src/Evolution/Systems/Ccz4/DerivLapse.hpp
  tests/Unit/Evolution/Systems/Ccz4/Test_DerivLapse.cpp
Labels: small

#6599 Fix possible small memory leak in interpolator
  src/ParallelAlgorithms/Interpolation/Actions/InterpolatorReceivePoints.hpp
  tests/Unit/ParallelAlgorithms/Interpolation/Test_InterpolatorReceivePoints.cpp
Labels: bugfix
